### ISSUE TITLE
Video link displayed twice, first one with ?theater

### ISSUE THREAD

**Issue by Smile4ever** [dequis/purple-facebook#187]
Here I am again.

I found another case of duplicate messages: video links. I'm not sure if you want to solve it though:
(15:54:07) person: https://www.facebook.com/1420819151499426/videos/1714252692156069/?theater
(15:54:07) person: https://www.facebook.com/1420819151499426/videos/1714252692156069/

First link is the same with ?theater, next link is the same without ?theater.

The parameter ?theater has no effect. This is due to thumbnails displaying.

You can solve all these thumbnail issues all at once, I believe:
- if you receive a message, check if the previous message is from facebook and contains a question mark.
- if so, find the position of the question mark
- if not from facebook, but it is still an url, just do the compare on the last char of the link (the char before \n or the char before the space)
- do a substring on the previous message from the start of "http" to the question mark
- if that substring is equal to the current message, do not add the current message (the URL without question mark) to the conversation window

I believe this covers almost all cases, including this one:
(16:07:29) Smile4ever: look at this :p https://www.facebook.com/1420819151499426/videos/1714252692156069/?theater
(16:07:29) Smile4ever: https://www.facebook.com/1420819151499426/videos/1714252692156069/
(as you can see, the substring starting with http is equal to the next message)

This is the opposite approach of what you once suggested (you suggested removing the parameters from the URL, but objected because they are sometimes needed).

Looking forward to your reaction.

**Comment by dequis** [comment]
0.9.0
