### ISSUE TITLE
repo for rhel/centos

### ISSUE THREAD

**Issue by typekpb** [dequis/purple-facebook#213]
any chance for providing the rhel/centos repository? I'm on 7.2 version. thanks

**Comment by dequis** [comment]
Unlikely. Just follow the build instructions, it's not a big deal.

**Comment by jgeboski** [comment]
I have just added a [repository](http://download.opensuse.org/repositories/home:/jgeboski/CentOS_7/) for this. Would you mind being a test subject for it?

**Comment by typekpb** [comment]
@jgeboski Thanks a lot! Just tried and it works OK for me (I run: RHEL 7.2). 
Any chance for official docs on this one?

**Comment by jgeboski** [comment]
Yup. I will add it to jgeboski.github.io after I get some of the other distributions tested.

**Comment by tkontogi** [comment]
Just used it in Fedora23.. It installs and runs... Looks like it works perfectly.
Thank you for this repo.

**Comment by mcepl** [comment]
Just to say, that there is [another repo](https://copr.fedorainfracloud.org/coprs/mcepl/spectrum2/build/201111/) where these packages are maintained as part of [spectrum2](http://spectrum.im/) packages.
