### ISSUE TITLE
purple-facebook and openSUSe 42.1

### ISSUE THREAD

**Issue by dormonster** [dequis/purple-facebook#215]
Does anyone have any thoughts on how to install the plugin for Pidgin 2.10.11 running in openSuSe 42.1

Thanks everyone.

**Comment by LinAGKar** [comment]
You can install it from the home:jgeboski repo. https://build.opensuse.org/project/show/home:jgeboski.

Or for a one-click-install:
https://software.opensuse.org/ymp/home:jgeboski/openSUSE_Leap_42.1/purple-facebook.ymp?base=openSUSE%3ALeap%3A42.1&query=purple-facebook

**Comment by Mailaender** [comment]
I just submitted https://build.opensuse.org/request/show/406200 which should now finally update properly. See https://github.com/dequis/purple-facebook/issues/242 for the upstream issue. Once the mirrors sync https://software.opensuse.org/package/purple-facebook should give you the right button to click.
