### ISSUE TITLE
How implement mark as read

### ISSUE THREAD

**Issue by petr-stety-stetka** [dequis/purple-facebook#218]
Hi,
How can I implement a mark as read? What is name of function or signal, which I must call to mark messages as read?
Thanks for any reply :)

**Comment by jgeboski** [comment]
It is already implemented?

**Comment by jgeboski** [comment]
I think you might be interested in #221.

**Comment by petr-stety-stetka** [comment]
It looks good :) but how can I mark messages as read? (just as it does pidgin) 
Have I use this?
"It needs to support the conversation-updated signal, the deleting-conversation signal, and purple_conversation_has_focus()."

**Comment by dequis** [comment]
Sounds like you answered your own question. Either way this tracker isn't meant for support when writing libpurple based clients, so i'm closing this.
