### ISSUE TITLE
Show unsupported message types

### ISSUE THREAD

**Issue by jkufner** [dequis/purple-facebook#223]
When someone sends to purple-facebook client a message which is not supported by purple-facebook, a placeholder message should be displayed, so recipient knows, that something arrived and he should take a better look via web. It will save a lot of misunderstandings.

Something like `[message of unsupported type]` is enough. Just don't drop anything without telling user about it.

**Comment by dequis** [comment]
Could you be more specific? It already does this for a bunch of things

**Comment by jgeboski** [comment]
As @dequis mentioned, this is done for all unknown XMA message types. What version of the plugin are you using?

**Comment by dequis** [comment]
Ping

**Comment by dequis** [comment]
Closing due to lack of response
