### ISSUE TITLE
Mixed Hebrew/Latin text is displayed in the wrong order (LTR instead of RTL) when the main language is Hebrew.

### ISSUE THREAD

**Issue by shlomif** [dequis/purple-facebook#233]
Hi all - thanks for purple-facebook. I'm using it to chat with my facebook friends using pidgin-2.10.12-1.mga6 on Mageia Linux x86-64 v6. However, since I'm an Israeli and some of my friends and I communicate in mixed Hebrew/Latin text, then often when the primary language of the paragraph is Hebrew, the text gets displayed in the wrong order (left-to-right or LTR) instead of right-to-life or RTL.

Now, facebook handles it fine in its web interface and I recall it sometimes being fine in XMPP/Jabber chats.

Please look into correcting it and let me know if I can be of further assistance.

**Comment by dequis** [comment]
>recall it sometimes being fine in XMPP/Jabber chats.

...sometimes?

Could you try again with any other protocol to confirm?

**Comment by shlomif** [comment]
@dequis: sorry for the late response. I'm trying to find someone else to talk with on some online forums. And what do you mean by 'any other protocol'? a protocol other  than what exactly?

**Comment by dequis** [comment]
Other than this one. XMPP is fine.

**Comment by shlomif** [comment]
@dequis: Ok, thanks for the update.

**Comment by shlomif** [comment]
![pidgin](https://cloud.githubusercontent.com/assets/3150/14145630/39539620-f69d-11e5-853c-781dcb46f847.png)

Hi @dequis ! It seems to be working fine in XMPP/Jabber over GMail (when both endpoints are pidgin) as this screenshot of a conversation shows. I am shlomif and the other party is borissh and as you can see the mixed Hebrew/Latin text not only is in RTL direction but also aligned to the right of the window. So it seems to be a quirk of the purple-facebook plugin.

Regards, -- @shlomif

**Comment by dequis** [comment]
Can I have a screenshot of it being rendered incorrectly, when using this plugin? And copy a text version of the conversation.

This looks good to me:

![](https://cloud.githubusercontent.com/assets/94108/14401702/b30b3a4a-fdf0-11e5-8a55-dfea3a5db455.png)

**Comment by dequis** [comment]
@shtrb you mentioned a similar issue with a different plugin, how does this work for you?

**Comment by shlomif** [comment]
@dequis: 

I've attached a screenshot of a facebook conversation:

![pidgin-screenshot](https://cloud.githubusercontent.com/assets/3150/14402665/3b6af7e6-fe45-11e5-8687-bcaf9a5e70e6.png)

As you can see - my (= Shlomi Fish's) text which starts with Hebrew is right-aligned and has an RTL direction and it says "starts with hebrew, goes to English(in English and returns to hebrew). On the other hand, the same text as typed from my recipient is left-aligned and in an LTR paragraph direction. The key here is that the starting words should be in Hebrew so ought to be aligned and directed properly.

**Comment by shlomif** [comment]
Just a note - my facebook recipient's name is written using Latin/English letters (completely).

**Comment by dequis** [comment]
Fixed with https://bitbucket.org/pidgin/main/pull-requests/35/gtkconv-fix-alignment-of-incoming-rtl - should be included in the next pidgin release

(I forgot to close this ticket before)

**Comment by dequis** [comment]
Pidgin 2.11.0 is out
