### ISSUE TITLE
removing contact does not unfriend

### ISSUE THREAD

**Issue by shtrb** [dequis/purple-facebook#234]
Using 1af1f6f709910a02a0a3093c75bae839a1d4fcd8 (git) VERSION file have 92885e0456ed

When I remove a contact from pidgin (by clicking on remove) it is not removed from facebook friends.

Pidgin 2.10.11 (libpurple 2.10.11) Debian

**Comment by auscompgeek** [comment]
I believe this is a limitation of the protocol itself. Facebook Messenger doesn't give you the ability to unfriend people.

**Comment by dequis** [comment]
As stated above, if the facebook messenger android app doesn't do it, we can't do it.
