### ISSUE TITLE
configure doesn't check for zlib.h

### ISSUE THREAD

**Issue by rstory** [dequis/purple-facebook#238]
latest release and git reference ZLIB_LIBS in configure.ac, but don't test that zlib header is available. so configure will succeed, but make will fail.

**Comment by dequis** [comment]
From a quick googling it looks like using `PKG_CHECK_MODULES` to check for zlib is not reliable across platforms - adding it would break the build in some of them.

This isn't a huge issue and I don't think fixing it is worth the hassle, so i'll just go ahead and close it.
