### ISSUE TITLE
Can't view photos/photos links

### ISSUE THREAD

**Issue by Gronekmaster** [dequis/purple-facebook#240]
I can't view photo or hyperlink to fbcdn. Can you fix it?

**Comment by dequis** [comment]
Is this still happening? Any errors?

**Comment by karakartala** [comment]
![dbojz_x](https://cloud.githubusercontent.com/assets/8956434/15516783/1fd475b2-21fd-11e6-8f02-5ffa0a20cc6c.png)
Same issue. I tried delete&re-add account. Not solved. How to solve this issue?

**Comment by Gronekmaster** [comment]
@dequis unfortunetly, all the time

**Comment by dequis** [comment]
Does anything appear in `help menu -> debug window` when trying to load an image? (no need to enable full debug logs as mentioned in the wiki)

Do you need to use a proxy to connect?

**Comment by ratapan** [comment]
@dequis  I do not use a proxy.
 Debug window appears

> Pidgin 2.10.9 (libpurple 2.10.9)
> unknown
> 
> İnşa bilgisi
>   Arguments to ./configure:   '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=${prefix}/lib/pidgin' '--disable-maintainer-mode' '--disable-dependency-tracking' '--disable-silent-rules' '--disable-gevolution' '--enable-cap' '--with-system-ssl-certs=/etc/ssl/certs' '--enable-perl' '--with-zephyr=/usr' '--enable-dbus' '--enable-gnutls=no' '--enable-nss=yes' '--enable-cyrus-sasl' '--enable-vv' '--enable-farsight' '--enable-tcl' '--enable-tk' '--with-tclconfig=/usr/lib/x86_64-linux-gnu' '--with-dynamic-prpls=bonjour,gg,irc,jabber,msn,myspace,mxit,novell,oscar,sametime,simple,yahoo,zephyr' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wall' 'LDFLAGS=-Wl,--as-needed' 'CPPFLAGS=-D_FORTIFY_SOURCE=2'
>   Print debugging messages: No
>   Plugins: Enabled
>   SSL: SSL support is present.
> 
>   Library Support
>     Cyrus SASL: Enabled
>     D-Bus: Enabled
>     Evolution Addressbook: Disabled
>     Gadu-Gadu library (libgadu): Internal
>     GtkSpell: Enabled
>     GnuTLS: Disabled
>     GStreamer: Enabled
>     Mono: Disabled
>     NetworkManager: Enabled
>     Network Security Services (NSS): Enabled
>     Perl: Enabled
>     Tcl: Enabled
>     Tk: Enabled
>     UTF-8 DNS (IDN): Enabled
>     Voice and Video: Enabled
>     X Session Management: Enabled
>     XScreenSaver: Enabled
>     Zephyr library (libzephyr): External
>     Zephyr uses Kerberos: No
>

**Comment by dequis** [comment]
@ratapan  That's not the debug window. That's the build information window.

**Comment by ratapan** [comment]
debug window appears

> (09:43:33) util: Writing file prefs.xml to directory /home/mint/.purple
(09:43:33) util: Writing file /home/mint/.purple/prefs.xml

**Comment by dequis** [comment]
Weird. That looks like downloading the image worked.

What distro?

**Comment by karakartala** [comment]
ratapan uses LinuxMint 17.3 Cinnamon x64 .

**Comment by dequis** [comment]
Are you all in the same network or something?

**Comment by ratapan** [comment]
different network

**Comment by Mattie432** [comment]
Looks like this is similar to my issue #255

**Comment by dequis** [comment]
Has anyone checked that ^?

>It seems that the plugin Conversation Colors v2.11.0's setting of "Ignore incoming format" disables images from being shown from FB. Disabling this option fixed my issue.

If it's not that, post plugin lists.

**Comment by EionRobb** [comment]
@dequis yes, I've checked this. Conversation Colors eats images

**Comment by dequis** [comment]
@EionRobb silly eionrobb, not you, the people with the bug

**Comment by dequis** [comment]
Wait why did you close this? No one answered my question :(

**Comment by Gronekmaster** [comment]
It's caused by this, I forgot to answer last time, sorry ;)

**Comment by Mattie432** [comment]
See solution inside my issue #255
