### ISSUE TITLE
Installing on Windows?

### ISSUE THREAD

**Issue by HammyHavoc** [dequis/purple-facebook#241]
Is there a Windows release? If not, how do I go about compiling this on Windows?

**Comment by dequis** [comment]
https://github.com/dequis/purple-facebook/wiki/Installing-on-Windows

**Comment by HammyHavoc** [comment]
Followed that and it isn't showing up in Pidgin despite restarting Pidgin and restarting the computer. Other plugin installs are working. Not seeing the protocol in accounts, nor the plugin in the list.

**Comment by dequis** [comment]
What other plugins?

Have you read #204? Please try the same stuff that was suggested there.

**Comment by dequis** [comment]
Hello?

**Comment by dequis** [comment]
Are you still there?

**Comment by dequis** [comment]
[Shutting down][1]

[1]: http://i1.theportalwiki.net/img/0/04/Turret_turret_disabled_4.wav
