### ISSUE TITLE
configure missing from release tarball

### ISSUE THREAD

**Issue by acli** [dequis/purple-facebook#243]
According to https://github.com/dequis/purple-facebook/wiki/Building-on-*NIX the release tarball should already contain the "configure" script. However, in the latest release tarball (https://github.com/dequis/purple-facebook/wiki/Building-on-*NIX) the configure script is missing.

**Comment by dequis** [comment]
You downloaded the wrong one. Get `purple-facebook-66ee77378d82.tar.gz`, the other one is autogenerated by github and we can't get rid of it.

**Comment by acli** [comment]
Thanks! Maybe a note can be added to the wiki to clarify this? Maybe something like “(Make sure to download the first file and ignore the two labelled “Source code”.”?

**Comment by dequis** [comment]
Done
