### ISSUE TITLE
Can not compile

### ISSUE THREAD

**Issue by tkontogi** [dequis/purple-facebook#247]
Hello all.

I am trying to compile from git pull, on Fedora23

The error I get is:

```
./autogen.sh 
pulling from https://bitbucket.org/pidgin/main
searching for changes
no changes found
resolving manifests
0 files updated, 0 files merged, 0 files removed, 0 files unresolved
patching file libpurple/protocols/facebook/Makefile.am
patching file libpurple/protocols/facebook/Makefile.mingw
patching file libpurple/glibcompat.h
patching file libpurple/protocols/facebook/facebook.c
patching file libpurple/protocols/facebook/facebook.h
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -Im4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
configure.ac:34: error: possibly undefined macro: AC_DISABLE_STATIC
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:35: error: possibly undefined macro: AC_PROG_LIBTOOL
autoreconf: /usr/bin/autoconf failed with exit status: 1

```

Any ideas?

Appreciated.

**Comment by jgeboski** [comment]
Install `libtool`.

**Comment by tkontogi** [comment]
Thank you for quick follow up.

I will keep on posting, to help you to help us.

New error after libtool installed:

`./autogen.sh 
pulling from https://bitbucket.org/pidgin/main
searching for changes
no changes found
resolving manifests
0 files updated, 0 files merged, 0 files removed, 0 files unresolved
patching file libpurple/protocols/facebook/Makefile.am
patching file libpurple/protocols/facebook/Makefile.mingw
patching file libpurple/glibcompat.h
patching file libpurple/protocols/facebook/facebook.c
patching file libpurple/protocols/facebook/facebook.h
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -Im4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: configure.ac: not using Autoheader
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:31: installing 'build-aux/compile'
configure.ac:29: installing 'build-aux/missing'
pidgin/libpurple/protocols/facebook/Makefile.am: installing 'build-aux/depcomp'
autoreconf: Leaving directory `.'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... no
checking whether make supports nested variables... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... none
checking dependency style of gcc... none
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking whether make supports nested variables... (cached) no
./configure: line 11961: syntax error near unexpected token `GLIB,'
./configure: line 11961: `PKG_CHECK_MODULES(GLIB, glib-2.0 >= 2.28.0 gio-2.0 gobject-2.0)'
`

The compiling environment is a Fedora23 container. So guidance will be needed as errors come in.

Appreciated.

**Comment by dequis** [comment]
Or you could read the docs https://github.com/dequis/purple-facebook/wiki/Building-on-*NIX

Or you could google the error message https://www.google.com/search?q=syntax+error+near+unexpected+token+`GLIB,%27

**Comment by icarito** [comment]
I also can't compile and I have RTFD, it looks to me like a bug:
Help is appreciated. Thanks in advance.
```
make[1]: Entering directory '/home/icarito/Proyectos/purple-facebook/pidgin/libpurple/protocols/facebook'
  CC       libfacebook_la-api.lo
In file included from id.h:28:0,
                 from api.h:29,
                 from api.c:26:
util.h:58:15: error: unknown type name 'PurpleDebugLevel'
 fb_util_debug(PurpleDebugLevel level, const gchar *format, ...)
               ^
util.h:62:16: error: unknown type name 'PurpleDebugLevel'
 fb_util_vdebug(PurpleDebugLevel level, const gchar *format, va_list ap);
                ^
util.h:85:23: error: unknown type name 'PurpleDebugLevel'
 fb_util_debug_hexdump(PurpleDebugLevel level, const GByteArray *bytes,
                       ^
api.c: In function 'fb_api_http_chk':
util.h:28:30: error: 'PURPLE_DEBUG_INFO' undeclared (first use in this function)
 #define FB_UTIL_DEBUG_INFO ( PURPLE_DEBUG_INFO | FB_UTIL_DEBUG_FLAG_UNSAFE | FB_UTIL_DEBUG_FLAG_VERBOSE )
                              ^
api.c:381:16: note: in expansion of macro 'FB_UTIL_DEBUG_INFO'
  fb_util_debug(FB_UTIL_DEBUG_INFO, "HTTP Response (%p):", con);
                ^
util.h:28:30: note: each undeclared identifier is reported only once for each function it appears in
 #define FB_UTIL_DEBUG_INFO ( PURPLE_DEBUG_INFO | FB_UTIL_DEBUG_FLAG_UNSAFE | FB_UTIL_DEBUG_FLAG_VERBOSE )
                              ^
api.c:381:16: note: in expansion of macro 'FB_UTIL_DEBUG_INFO'
  fb_util_debug(FB_UTIL_DEBUG_INFO, "HTTP Response (%p):", con);
                ^
api.c: In function 'fb_api_http_req':
util.h:28:30: error: 'PURPLE_DEBUG_INFO' undeclared (first use in this function)
 #define FB_UTIL_DEBUG_INFO ( PURPLE_DEBUG_INFO | FB_UTIL_DEBUG_FLAG_UNSAFE | FB_UTIL_DEBUG_FLAG_VERBOSE )
                              ^
api.c:459:16: note: in expansion of macro 'FB_UTIL_DEBUG_INFO'
  fb_util_debug(FB_UTIL_DEBUG_INFO, "HTTP Request (%p):", ret);
                ^
api.c: In function 'fb_api_cb_mqtt_publish':
util.h:28:30: error: 'PURPLE_DEBUG_INFO' undeclared (first use in this function)
 #define FB_UTIL_DEBUG_INFO ( PURPLE_DEBUG_INFO | FB_UTIL_DEBUG_FLAG_UNSAFE | FB_UTIL_DEBUG_FLAG_VERBOSE )
                              ^
api.c:881:24: note: in expansion of macro 'FB_UTIL_DEBUG_INFO'
  fb_util_debug_hexdump(FB_UTIL_DEBUG_INFO, bytes,
                        ^
api.c: In function 'fb_api_publish':
util.h:28:30: error: 'PURPLE_DEBUG_INFO' undeclared (first use in this function)
 #define FB_UTIL_DEBUG_INFO ( PURPLE_DEBUG_INFO | FB_UTIL_DEBUG_FLAG_UNSAFE | FB_UTIL_DEBUG_FLAG_VERBOSE )
                              ^
api.c:1236:24: note: in expansion of macro 'FB_UTIL_DEBUG_INFO'
  fb_util_debug_hexdump(FB_UTIL_DEBUG_INFO, bytes,
                        ^
Makefile:537: recipe for target 'libfacebook_la-api.lo' failed
```

**Comment by dequis** [comment]
Those are very different errors. Something is likely to be broken with your libpurple installation, it's missing declarations that have been available since pidgin got renamed from gaim back in 2007.

What distro is this?

**Comment by icarito** [comment]
It's Debian 8 Jessie.
I'm working from an updated git head, but i realized it's pulling other stuff onto .pidgin and it's not merging. Finally I grabbed the tarball of the latest release and got that working. Thanks for the prompt response! I guess you can close this one.

**Comment by dequis** [comment]
Huh. Well, okay.
