### ISSUE TITLE
Disconnected with "No matches for $.hugePictureUrl.uri"

### ISSUE THREAD

**Issue by osund** [dequis/purple-facebook#249]
I got disconnected with the error message "No matches for $.hugePictureUrl.uri"

Version: 66ee77378d82

`connection: Connection error on 0x1f18580 (reason: 0 description: No matches for $.hugePictureUrl.uri)`

**Comment by mykhi** [comment]
Same happend to me just a while ago.

**Comment by osund** [comment]
Now I was able to log in again.

**Comment by dequis** [comment]
Closing because it was a temporary server issue (i got it too, it lasted 30 mins)
