### ISSUE TITLE
Unknown HTTP error

### ISSUE THREAD

**Issue by psyc0** [dequis/purple-facebook#250]
Since yesterday I'm receiving '#account disconnected - Unknown HTTP error'. 
I´ve tried clearing (marking all as read) in the chat from fb webui , for some errors like images this helps but not this time.

after the move to dequis repo i dont have the sources (running kubuntu 16.04) so currently running 'Version: 20160409~2a24dff~66ee77378d82~110'. 

couldnt find any better logging in pidgin for the plugin, tips on getting better logs? or solving the problem :)

**Comment by dequis** [comment]
>after the move to dequis repo i dont have the sources

What?

>so currently running 'Version: 20160409~2a24dff~66ee77378d82~110'. 

That's the latest version.

>tips on getting better logs?

https://github.com/dequis/purple-facebook/wiki/Debugging-Logs

**Comment by psyc0** [comment]
in apt, since i still have the instructions from 'https://github.com/dequis/purple-facebook/wiki/Installing-on-*NIX' and it points to repositories/home:/jgeboski/ , but maybe they are updated aswell?

the problem resolved itself after 2 days, without intervention, but will have the debugging ready for next time, thx.

**Comment by dequis** [comment]
The apt repo url is the same because opensuse doesn't automatically add redirects like github does, so changing repos would break things.
