### ISSUE TITLE
connection:Connection error on 0xc15530 (reason: 0 description: Invalid username or email address (400))

### ISSUE THREAD

**Issue by ahmedkbn** [dequis/purple-facebook#251]
I have configured prpl-facebook as per online guides but still it's throwing errors with correct credentials. Can someone tell me what's wrong with it?

Below is my configuration.

```
backend_host = localhost

backend_port=10001

users_per_backend=10

backend= /usr/bin/spectrum2_libpurple_backend

protocol=prpl-facebook


[identity]
name=Spectrum Facebook Transport

type=facebook


[logging]
config = /etc/spectrum2/logging.cfg

backend_config = /etc/spectrum2/backend-logging.cfg

[database]
type = mysql

database = xxxxx

server = localhost

port = 3306

user = xxxxx

password = xxxx

prefix = facebook__


[registration]
enable_public_registration=1

username_label=Jabber JID (e.g. user@server.tld):
instructions=Enter your remote jabber JID and password as well as your local username and password
username_mask=$username@chat.facebook.com
```

**Comment by EionRobb** [comment]
You're using an old guide that's trying to use XMPP to connect to Facebook, instead of using the Facebook plugin.  See if there's another guide that was written in the last 12 months instead.

**Comment by vitalyster** [comment]
> prpl-facebook
It is new plugin. Need to see error logs

**Comment by vitalyster** [comment]
> username_mask=$username@chat.facebook.com

Delete this line and it should work after

**Comment by ahmedkbn** [comment]
@vitalyster 

Thanks. It worked after removing that line.
