### ISSUE TITLE
https://dl.voidium.net/pidgin/libfacebook.dll download isn't working

### ISSUE THREAD

**Issue by richardlampitt** [dequis/purple-facebook#252]
Trying to access https://dl.voidium.net/pidgin/libfacebook.dll results in a connection timeout currently.

**Comment by jgeboski** [comment]
Server is being migrated currently. Should be back within a few hours.

**Comment by jgeboski** [comment]
The server is back online.

**Comment by groovenectar** [comment]
It seems to be offline again

**Comment by dequis** [comment]
Yeah, server migration that is taking a way too long :(

I uploaded the dll to https://github.com/dequis/purple-facebook/releases

**Comment by groovenectar** [comment]
Heck yeah, that worked, thank you!
