### ISSUE TITLE
Crash in 14.04

### ISSUE THREAD

**Issue by Thedemon007** [dequis/purple-facebook#253]
I attach Log crash i use xubuntu 14.04
[_usr_bin_pidgin.1000.crash.zip](https://github.com/dequis/purple-facebook/files/329561/_usr_bin_pidgin.1000.crash.zip)

**Comment by dequis** [comment]
There's nothing in that crash indicating that the crash is in this plugin. It happens in the middle of glib. There's also other third party plugins. What were you doing when this happened?

**Comment by Thedemon007** [comment]
I execute pidgin whith account of facebook and crash, i deactivate account and working fine with others plugins irc, xmpp....

**Comment by EionRobb** [comment]
Try using the instructions at https://developer.pidgin.im/wiki/GetABacktrace to get a backtrace.  I second what @dequis says, that in what you've attached there's nothing about the facebook plugin, and hardly a mention of pidgin either.

**Comment by Thedemon007** [comment]
https://github.com/dequis/purple-facebook/issues/253#issuecomment-228268709

Thanks for the help, ok i install packages of debugging symbols libglib2.0-0-dbg follow instructions and get this backtrace:

Program received signal SIGSEGV, Segmentation fault.
g_main_dispatch (context=0x555555864200)
    at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:3019
3019	/build/buildd/glib2.0-2.40.2/./glib/gmain.c: No such file or directory.
(gdb) bt full
#0  g_main_dispatch (context=0x555555864200)
    at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:3019
        source = 0x555557217d40
        current = 0x555555de7a10
        i = 2
#1  g_main_context_dispatch (context=context@entry=0x555555864200)
    at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:3663
No locals.
#2  0x00007ffff53a9048 in g_main_context_iterate (context=0x555555864200, 
    block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:3734
        max_priority = 0
        timeout = 0
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = 8
        fds = 0x555556851d60
#3  0x00007ffff53a930a in g_main_loop_run (loop=0x55555684eab0)
    at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:3928
        __FUNCTION__ = "g_main_loop_run"
#4  0x00007ffff6632447 in gtk_main ()
   from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
No symbol table info available.
#5  0x000055555558f369 in main ()
No symbol table info available.

After i install the other debugging symbols libgtk2.0-0-dbg i can use pidgin 2 or 3 times fine only get a error of certified a time, and in a test crash but is captured for the tool of ubuntu:

![screenshot_](https://cloud.githubusercontent.com/assets/1224021/16353315/32dc42f4-3a42-11e6-8e93-7391bb5369fe.png)
[_usr_bin_pidgin.1000.crash.zip](https://github.com/dequis/purple-facebook/files/332794/_usr_bin_pidgin.1000.crash.zip)

I will continue testing soon i install gtk debugging symbols and try reproduce crash again....

**Comment by Thedemon007** [comment]
Ok the crash no reproduce sometimes add LAN=en in commands, i add this before for obtain stdout in english and not in spanish, out of force english i get backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
g_main_dispatch (context=0x555555864ed0) at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:3019
3019	/build/buildd/glib2.0-2.40.2/./glib/gmain.c: No existe el archivo o el directorio.
(gdb) bt full
#0  g_main_dispatch (context=0x555555864ed0) at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:3019
        source = 0x555556e488f0
        current = 0x555555e23310
        i = 3
#1  g_main_context_dispatch (context=context@entry=0x555555864ed0) at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:3663
No locales.
#2  0x00007ffff53a9048 in g_main_context_iterate (context=0x555555864ed0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:3734
        max_priority = 0
        timeout = 0
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = 8
        fds = 0x5555563aee70
#3  0x00007ffff53a930a in g_main_loop_run (loop=0x555555d86a70) at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:3928
        __FUNCTION__ = "g_main_loop_run"
#4  0x00007ffff6632447 in IA__gtk_main () at /build/gtk+2.0-KsZSEA/gtk+2.0-2.24.23/gtk/gtkmain.c:1271
        tmp_list = 0x0
        functions = 0x0
        init = <optimized out>
        loop = 0x555555d86a70
#5  0x000055555558f369 in main ()
No symbol table info available.
```
"No symbol table info available." i no known what pakages of debugging symbols install for obtain more info......

**Comment by Thedemon007** [comment]
:D i install package pidgin-dbg and now get a bactrace with more info:

```
#0  g_main_dispatch (context=0x555555864200) at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:3019
        source = 0x5555575416b0
        current = 0x555555df0d10
        i = 3
#1  g_main_context_dispatch (context=context@entry=0x555555864200) at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:3663
No locals.
#2  0x00007ffff53a9048 in g_main_context_iterate (context=0x555555864200, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:3734
        max_priority = 0
        timeout = 0
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = 8
        fds = 0x55555593e4b0
#3  0x00007ffff53a930a in g_main_loop_run (loop=0x555555c3eaa0) at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:3928
        __FUNCTION__ = "g_main_loop_run"
#4  0x00007ffff6632447 in IA__gtk_main () at /build/gtk+2.0-KsZSEA/gtk+2.0-2.24.23/gtk/gtkmain.c:1271
        tmp_list = 0x0
        functions = 0x0
        init = <optimized out>
        loop = 0x555555c3eaa0
#5  0x000055555558f369 in main (argc=1, argv=0x7fffffffe008) at /build/buildd/pidgin-2.10.9/./pidgin/gtkmain.c:880
        opt_force_online = 0
        opt_help = <optimized out>
        opt_login = 0
        opt_nologin = 0
        opt_version = <optimized out>
        opt_si = <optimized out>
        opt_config_dir_arg = <optimized out>
        opt_login_arg = <optimized out>
        opt_session_arg = <optimized out>
        search_path = <optimized out>
        accounts = <optimized out>
        sig_indx = 1
        sigset = {__val = {16390, 0 <repeats 15 times>}}
        errmsg = '\000' <repeats 1208 times>...
        signal_channel = <optimized out>
        signal_status = <optimized out>
        signal_channel_watcher = 1
        segfault_message_tmp = <optimized out>
        error = 0x0
        opt = <optimized out>
        gui_check = <optimized out>
        debug_enabled = <optimized out>
        migration_failed = <optimized out>
        active_accounts = <optimized out>
        st = {st_dev = 0, st_ino = 0, st_nlink = 0, st_mode = 0, st_uid = 0, st_gid = 0, __pad0 = 0, st_rdev = 0, st_size = 0, st_blksize = 0, st_blocks = 0, st_atim = {
            tv_sec = 0, tv_nsec = 0}, st_mtim = {tv_sec = 0, tv_nsec = 0}, st_ctim = {tv_sec = 0, tv_nsec = 0}, __glibc_reserved = {0, 0, 0}}
        long_options = {{name = 0x5555556296ad "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x555555617d79 "debug", has_arg = 0, flag = 0x0, val = 100}, {
            name = 0x5555556256d4 "force-online", has_arg = 0, flag = 0x0, val = 102}, {name = 0x5555556198fa "help", has_arg = 0, flag = 0x0, val = 104}, {
            name = 0x55555562559d "login", has_arg = 2, flag = 0x0, val = 108}, {name = 0x5555556256e1 "multiple", has_arg = 0, flag = 0x0, val = 109}, {
            name = 0x5555556256ea "nologin", has_arg = 0, flag = 0x0, val = 110}, {name = 0x5555556296a3 "session", has_arg = 1, flag = 0x0, val = 115}, {
            name = 0x55555561c17a "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x5555556296b6 "display", has_arg = 1, flag = 0x0, val = 68}, {
            name = 0x5555556261c5 "sync", has_arg = 0, flag = 0x0, val = 83}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
```

**Comment by EionRobb** [comment]
Doesn't look like it's to do with facebook. Try disable the libnotify plugin?

**Comment by Thedemon007** [comment]
Yes i try disable plugin give 2 o 3 crash and more later not can reproduce crash again after active libnotify again and work fine........

**Comment by dequis** [comment]
FWIW I looked at the coredump and the GSource that crashed was some dns query related function. But it's probably unrelated, just some random memory corruption.

**Comment by Thedemon007** [comment]
Mmm i reproduce crash once and, try again disable the libnotify plugin and try reproduce again but nothing, in a try pidgin show error of certificate ssl in fbcdn-profile-a.akamaihd.net msg in spanish: "El certificado por fbcdn-profile-a.akamaihd.net no pudo ser validado. La cadena de certificación presentada es inválida."  https://developer.pidgin.im/ticket/17055
