### ISSUE TITLE
Support unknown messages

### ISSUE THREAD

**Issue by jkufner** [dequis/purple-facebook#254]
When someone sends me some wierd stuff like stickers or big smiles, I see nothing in my client, which leads to wierd situations and missed answers.

Even when purple-facebook does not support a received message, it should show at least something, a warning or a note about the wierd/unsupported message. The I can open web browser and take a look. But when purple-facebook silently drops it, I have no idea I've got a response.

**Comment by dequis** [comment]
Please provide a debug log https://github.com/dequis/purple-facebook/wiki/Debugging-Logs

**Comment by jkufner** [comment]
I found the message:

`4757: 2016-06-23 16:54:15,310 INFO  libpurple: facebook:  Response Data: {"126******600":{"__type__":{"name":"Sticker"},"id":"126*****600","pack":{"id":"126*****943"},"thread_image":{"uri":"https:\/\/scontent.xx.fbcdn.net\/t39.1997-6\/p128x128\/8*****5_126*****933_20*****02_n.png?_nc_ad=z-m"},"animated_image":null,"preview_image":{"uri":"https:\/\/scontent.xx.fbcdn.net\/t39.1997-6\/p200x200\/8*****5_126*****933_20*****02_n.png?_nc_ad=z-m"}}}
`

And then to XMPP server it is sent as:

`2016-06-23 16:54:15,426 INFO  Component.RAW: RAW DATA OUT <message from="1***9@facebook.*****.net/bot" to="*****@*****/Gajim" type="chat"><body></body></message>`

So the sticker is translated into an empty message.

**Comment by dequis** [comment]
Are you sure this isn't your client stripping images? Can you confirm this with pidgin?

**Comment by EionRobb** [comment]
The "Conversation Colours" plugin is known to strip inline images

**Comment by dequis** [comment]
@EionRobb i think this is spectrum. Okay i should have specified, by client i meant spectrum. That's not exactly obvious.

**Comment by jkufner** [comment]
It is Spectrum. The empty message is logged on the server before it gets to a client.

**Comment by jkufner** [comment]
Any idea how to check what is sent between libpurple and spectrum? Can't find anything useful in logs.

**Comment by dequis** [comment]
Dunno, you'd have to ask the spectrum people about that. It would be ideal if you could try to reproduce this issue in pidgin instead.

**Comment by jkufner** [comment]
I was thinking more about some debug messages of what purple-facebook is sending to pidgin/spectrum/whatever is outside.

**Comment by dequis** [comment]
There's no debug for that. It would be ideal if you could try to reproduce this issue in pidgin instead.

**Comment by dequis** [comment]
After several headaches I got spectrum2 working and it's not our bug.

See http://spectrum.im/documentation/configuration/web_storage.html

This is mentioned in the libpurple backend page of the spectrum docs ("Facebook stickers are supported using Web Storage.")

See also #257
