### ISSUE TITLE
Certificate spam reject accept

### ISSUE THREAD

**Issue by cmislin** [dequis/purple-facebook#256]
I'm not sure how to do the debug stuff yet but certificates for aim yahoo and facebook have been coming up alot.

**Comment by cmislin** [comment]
Meant to add sometimes I have to accept them up to 3 times if I reject any its disconnects that chat service.

**Comment by cmislin** [comment]
Meant to add sometimes I have to accept them up to 3 times if I reject any its disconnects that chat service.

**Comment by cmislin** [comment]
14:34:48) nss: partial certificate chain
(14:34:48) certificate/x509/tls_cached: Starting verify for graph.facebook.com
(14:34:48) certificate/x509/tls_cached: Checking for cached cert...
(14:34:48) certificate/x509/tls_cached: ...Found cached cert
(14:34:48) nss/x509: Loading certificate from C:\Users\chris\AppData\Roaming\.purple\certificates\x509\tls_peers\graph.facebook.com
(14:34:48) certificate/x509/tls_cached: Peer cert did NOT match cached
(14:34:48) nss: CERT 0. CN=*.facebook.com,C=US :
(14:34:48) nss:   ERROR -8179: SEC_ERROR_UNKNOWN_ISSUER
(14:34:49) certificate/x509/tls_cached: User ACCEPTED cert
Caching first in chain for future use as graph.facebook.com...
(14:34:49) nss/x509: Exporting certificate to C:\Users\chris\AppData\Roaming\.purple\certificates\x509\tls_peers\graph.facebook.com
(14:34:49) util: Writing file C:\Users\chris\AppData\Roaming\.purple\certificates\x509\tls_peers\graph.facebook.com
(14:34:49) nss: Trusting CN=*.facebook.com,C=US
(14:34:49) certificate: Successfully verified certificate for graph.facebook.com
(14:34:49) proxy: Windows Proxy Settings set to autodetect (not supported).

**Comment by cmislin** [comment]
(15:45:08) account: Connecting to account cmislin.
(15:45:08) connection: Connecting. gc = 05D770C0
(15:45:08) http: Performing new request 05BC2078 to graph.facebook.com.
(15:45:08) proxy: Windows Proxy Settings set to autodetect (not supported).
(15:45:08) proxy: No environment settings found, not using a proxy
(15:45:08) dnsquery: Performing DNS lookup for graph.facebook.com
(15:45:08) proxy: Windows Proxy Settings set to autodetect (not supported).
(15:45:08) proxy: No environment settings found, not using a proxy
(15:45:08) dnsquery: IP resolved for graph.facebook.com
(15:45:08) proxy: Attempting connection to 31.13.73.1
(15:45:08) proxy: Connecting to graph.facebook.com:443 with no proxy
(15:45:08) proxy: Connection in progress
(15:45:08) proxy: Connecting to graph.facebook.com:443.
(15:45:08) proxy: Connected to graph.facebook.com:443.
(15:45:08) nss: SSL version 3.3 using 128-bit AES-GCM with 128-bit AEAD MAC
Server Auth: 2048-bit RSA, Key Exchange: 256-bit ECDHE, Compression: NULL
Cipher Suite Name: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
(15:45:08) nss: subject=CN=*.facebook.com,C=US issuer=E=support-team@digitalreflectionpanel.com,CN=Digital Reflection,OU=Digital Reflection Certificate Authority,O=Digital Reflection,L=Reston,ST=Virginia,C=US
(15:45:08) nss: partial certificate chain
(15:45:08) certificate/x509/tls_cached: Starting verify for graph.facebook.com
(15:45:08) certificate/x509/tls_cached: Checking for cached cert...
(15:45:08) certificate/x509/tls_cached: ...Found cached cert
(15:45:08) nss/x509: Loading certificate from C:\Users\chris\AppData\Roaming\.purple\certificates\x509\tls_peers\graph.facebook.com
(15:45:08) certificate/x509/tls_cached: Peer cert did NOT match cached
(15:45:08) nss: CERT 0. CN=*.facebook.com,C=US :
(15:45:08) nss:   ERROR -8179: SEC_ERROR_UNKNOWN_ISSUER
(15:45:09) certificate/x509/tls_cached: User ACCEPTED cert
Caching first in chain for future use as graph.facebook.com...
(15:45:09) nss/x509: Exporting certificate to C:\Users\chris\AppData\Roaming\.purple\certificates\x509\tls_peers\graph.facebook.com
(15:45:09) util: Writing file C:\Users\chris\AppData\Roaming\.purple\certificates\x509\tls_peers\graph.facebook.com
(15:45:09) nss: Trusting CN=*.facebook.com,C=US
(15:45:09) certificate: Successfully verified certificate for graph.facebook.com
(15:45:09) proxy: Windows Proxy Settings set to autodetect (not supported).
(15:45:09) proxy: No environment settings found, not using a proxy
(15:45:10) http: Request 05BC2078 performed successfully.
(15:45:10) http: Performing new request 05E210A0 to graph.facebook.com.
(15:45:10) proxy: Windows Proxy Settings set to autodetect (not supported).
(15:45:10) proxy: No environment settings found, not using a proxy
(15:45:10) dnsquery: Performing DNS lookup for graph.facebook.com
(15:45:10) proxy: Windows Proxy Settings set to autodetect (not supported).
(15:45:10) proxy: No environment settings found, not using a proxy
(15:45:10) dnsquery: IP resolved for graph.facebook.com
(15:45:10) proxy: Attempting connection to 31.13.73.1
(15:45:10) proxy: Connecting to graph.facebook.com:443 with no proxy
(15:45:10) proxy: Connection in progress
(15:45:10) proxy: Connecting to graph.facebook.com:443.
(15:45:10) proxy: Connected to graph.facebook.com:443.
(15:45:11) nss: SSL version 3.3 using 128-bit AES-GCM with 128-bit AEAD MAC
Server Auth: 2048-bit RSA, Key Exchange: 256-bit ECDHE, Compression: NULL
Cipher Suite Name: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
(15:45:11) nss: subject=CN=*.facebook.com,C=US issuer=E=support-team@digitalreflectionpanel.com,CN=Digital Reflection,OU=Digital Reflection Certificate Authority,O=Digital Reflection,L=Reston,ST=Virginia,C=US
(15:45:11) nss: partial certificate chain
(15:45:11) certificate/x509/tls_cached: Starting verify for graph.facebook.com
(15:45:11) certificate/x509/tls_cached: Checking for cached cert...
(15:45:11) certificate/x509/tls_cached: ...Found cached cert
(15:45:11) nss/x509: Loading certificate from C:\Users\chris\AppData\Roaming\.purple\certificates\x509\tls_peers\graph.facebook.com
(15:45:11) certificate/x509/tls_cached: Peer cert did NOT match cached
(15:45:11) nss: CERT 0. CN=*.facebook.com,C=US :
(15:45:11) nss:   ERROR -8179: SEC_ERROR_UNKNOWN_ISSUER
(15:45:12) util: Writing file prefs.xml to directory C:\Users\chris\AppData\Roaming\.purple
(15:45:12) util: Writing file C:\Users\chris\AppData\Roaming\.purple\prefs.xml
(15:45:12) certificate/x509/tls_cached: User ACCEPTED cert
Caching first in chain for future use as graph.facebook.com...
(15:45:12) nss/x509: Exporting certificate to C:\Users\chris\AppData\Roaming\.purple\certificates\x509\tls_peers\graph.facebook.com
(15:45:12) util: Writing file C:\Users\chris\AppData\Roaming\.purple\certificates\x509\tls_peers\graph.facebook.com
(15:45:12) nss: Trusting CN=*.facebook.com,C=US
(15:45:12) certificate: Successfully verified certificate for graph.facebook.com
(15:45:12) proxy: Windows Proxy Settings set to autodetect (not supported).
(15:45:12) proxy: No environment settings found, not using a proxy
(15:45:12) http: Request 05E210A0 performed successfully.
(15:45:12) proxy: Windows Proxy Settings set to autodetect (not supported).
(15:45:12) proxy: No environment settings found, not using a proxy
(15:45:12) dnsquery: Performing DNS lookup for mqtt.facebook.com
(15:45:12) proxy: Windows Proxy Settings set to autodetect (not supported).
(15:45:12) proxy: No environment settings found, not using a proxy
(15:45:12) dnsquery: IP resolved for mqtt.facebook.com
(15:45:12) proxy: Attempting connection to 173.252.122.1
(15:45:12) proxy: Connecting to mqtt.facebook.com:443 with no proxy
(15:45:12) proxy: Connection in progress
(15:45:12) proxy: Connecting to mqtt.facebook.com:443.
(15:45:12) proxy: Connected to mqtt.facebook.com:443.
(15:45:12) nss: SSL version 3.3 using 128-bit AES-GCM with 128-bit AEAD MAC
Server Auth: 2048-bit RSA, Key Exchange: 256-bit ECDHE, Compression: NULL
Cipher Suite Name: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
(15:45:12) nss: subject=CN=*.facebook.com,C=US issuer=E=support-team@digitalreflectionpanel.com,CN=Digital Reflection,OU=Digital Reflection Certificate Authority,O=Digital Reflection,L=Reston,ST=Virginia,C=US
(15:45:12) nss: partial certificate chain
(15:45:12) certificate/x509/tls_cached: Starting verify for mqtt.facebook.com
(15:45:12) certificate/x509/tls_cached: Checking for cached cert...
(15:45:12) certificate/x509/tls_cached: ...Found cached cert
(15:45:12) nss/x509: Loading certificate from C:\Users\chris\AppData\Roaming\.purple\certificates\x509\tls_peers\mqtt.facebook.com
(15:45:12) certificate/x509/tls_cached: Peer cert did NOT match cached
(15:45:12) nss: CERT 0. CN=*.facebook.com,C=US :
(15:45:12) nss:   ERROR -8179: SEC_ERROR_UNKNOWN_ISSUER
(15:45:13) util: Writing file accounts.xml to directory C:\Users\chris\AppData\Roaming\.purple
(15:45:13) util: Writing file C:\Users\chris\AppData\Roaming\.purple\accounts.xml
(15:45:13) certificate/x509/tls_cached: User ACCEPTED cert
Caching first in chain for future use as mqtt.facebook.com...
(15:45:13) nss/x509: Exporting certificate to C:\Users\chris\AppData\Roaming\.purple\certificates\x509\tls_peers\mqtt.facebook.com
(15:45:13) util: Writing file C:\Users\chris\AppData\Roaming\.purple\certificates\x509\tls_peers\mqtt.facebook.com
(15:45:13) nss: Trusting CN=*.facebook.com,C=US
(15:45:13) certificate: Successfully verified certificate for mqtt.facebook.com
(15:45:13) http: Performing new request 05E210A0 to graph.facebook.com.
(15:45:13) proxy: Windows Proxy Settings set to autodetect (not supported).
(15:45:13) proxy: No environment settings found, not using a proxy
(15:45:13) dnsquery: Performing DNS lookup for graph.facebook.com
(15:45:13) proxy: Windows Proxy Settings set to autodetect (not supported).
(15:45:13) proxy: No environment settings found, not using a proxy
(15:45:13) dnsquery: IP resolved for graph.facebook.com
(15:45:13) proxy: Attempting connection to 31.13.73.1
(15:45:13) proxy: Connecting to graph.facebook.com:443 with no proxy
(15:45:13) proxy: Connection in progress
(15:45:13) proxy: Connecting to graph.facebook.com:443.
(15:45:13) proxy: Connected to graph.facebook.com:443.
(15:45:13) facebook: Presence: 755308293 (0)
(15:45:13) facebook: Presence: 100000372795971 (1)
(15:45:13) facebook: Presence: 100000379215077 (0)
(15:45:13) facebook: Presence: 100000576260772 (0)
(15:45:13) facebook: Presence: 701802193 (0)
(15:45:13) facebook: Presence: 1230692253 (0)
(15:45:13) facebook: Presence: 100001346165196 (1)
(15:45:13) facebook: Presence: 754735156 (0)
(15:45:13) facebook: Presence: 1202486309 (0)
(15:45:13) facebook: Presence: 596571396 (0)
(15:45:13) facebook: Presence: 100000848210032 (0)
(15:45:13) facebook: Presence: 100001971679938 (0)
(15:45:13) facebook: Presence: 501215951 (0)
(15:45:13) facebook: Presence: 696702418 (0)
(15:45:13) facebook: Presence: 1207291872 (0)
(15:45:13) facebook: Presence: 608037547 (0)
(15:45:13) facebook: Presence: 747205009 (0)
(15:45:13) facebook: Presence: 100001101487051 (1)
(15:45:13) facebook: Presence: 756167560 (0)
(15:45:13) facebook: Presence: 1144394669 (1)
(15:45:13) facebook: Presence: 513085897 (0)
(15:45:13) facebook: Presence: 1406365453 (0)
(15:45:13) facebook: Presence: 100000725690262 (0)
(15:45:13) facebook: Presence: 667998159 (0)
(15:45:13) facebook: Presence: 1582280815 (0)
(15:45:13) facebook: Presence: 503880041 (1)
(15:45:13) facebook: Presence: 1645143420 (0)
(15:45:13) facebook: Presence: 100000535163360 (1)
(15:45:13) facebook: Presence: 1638324432 (0)
(15:45:13) facebook: Presence: 1410747373 (1)
(15:45:13) facebook: Presence: 100010745595257 (0)
(15:45:13) facebook: Presence: 100009937111823 (0)
(15:45:13) facebook: Presence: 500832932 (0)
(15:45:13) facebook: Presence: 501407773 (1)
(15:45:13) facebook: Presence: 1628231731 (0)
(15:45:13) blist: Updating buddy status for 1628231731 (Facebook)
(15:45:13) blist: Updating buddy status for 501407773 (Facebook)
(15:45:13) blist: Updating buddy status for 500832932 (Facebook)
(15:45:13) blist: Updating buddy status for 100009937111823 (Facebook)
(15:45:13) blist: Updating buddy status for 100010745595257 (Facebook)
(15:45:13) blist: Updating buddy status for 1410747373 (Facebook)
(15:45:13) blist: Updating buddy status for 1638324432 (Facebook)
(15:45:13) blist: Updating buddy status for 100000535163360 (Facebook)
(15:45:13) blist: Updating buddy status for 1645143420 (Facebook)
(15:45:13) blist: Updating buddy status for 503880041 (Facebook)
(15:45:13) blist: Updating buddy status for 1582280815 (Facebook)
(15:45:13) blist: Updating buddy status for 667998159 (Facebook)
(15:45:13) blist: Updating buddy status for 100000725690262 (Facebook)
(15:45:13) blist: Updating buddy status for 1406365453 (Facebook)
(15:45:13) blist: Updating buddy status for 513085897 (Facebook)
(15:45:13) blist: Updating buddy status for 1144394669 (Facebook)
(15:45:13) blist: Updating buddy status for 756167560 (Facebook)
(15:45:13) blist: Updating buddy status for 100001101487051 (Facebook)
(15:45:13) blist: Updating buddy status for 747205009 (Facebook)
(15:45:13) blist: Updating buddy status for 608037547 (Facebook)
(15:45:13) blist: Updating buddy status for 1207291872 (Facebook)
(15:45:13) blist: Updating buddy status for 696702418 (Facebook)
(15:45:13) blist: Updating buddy status for 501215951 (Facebook)
(15:45:13) blist: Updating buddy status for 100001971679938 (Facebook)
(15:45:13) blist: Updating buddy status for 100000848210032 (Facebook)
(15:45:13) blist: Updating buddy status for 596571396 (Facebook)
(15:45:13) blist: Updating buddy status for 1202486309 (Facebook)
(15:45:13) blist: Updating buddy status for 754735156 (Facebook)
(15:45:13) blist: Updating buddy status for 100001346165196 (Facebook)
(15:45:13) blist: Updating buddy status for 1230692253 (Facebook)
(15:45:13) blist: Updating buddy status for 701802193 (Facebook)
(15:45:13) blist: Updating buddy status for 100000576260772 (Facebook)
(15:45:13) blist: Updating buddy status for 100000379215077 (Facebook)
(15:45:13) blist: Updating buddy status for 100000372795971 (Facebook)
(15:45:13) blist: Updating buddy status for 755308293 (Facebook)
(15:45:13) nss: SSL version 3.3 using 128-bit AES-GCM with 128-bit AEAD MAC
Server Auth: 2048-bit RSA, Key Exchange: 256-bit ECDHE, Compression: NULL
Cipher Suite Name: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
(15:45:13) nss: subject=CN=*.facebook.com,C=US issuer=E=support-team@digitalreflectionpanel.com,CN=Digital Reflection,OU=Digital Reflection Certificate Authority,O=Digital Reflection,L=Reston,ST=Virginia,C=US
(15:45:13) nss: partial certificate chain
(15:45:13) certificate/x509/tls_cached: Starting verify for graph.facebook.com
(15:45:13) certificate/x509/tls_cached: Checking for cached cert...
(15:45:13) certificate/x509/tls_cached: ...Found cached cert
(15:45:13) nss/x509: Loading certificate from C:\Users\chris\AppData\Roaming\.purple\certificates\x509\tls_peers\graph.facebook.com
(15:45:13) certificate/x509/tls_cached: Peer cert did NOT match cached
(15:45:13) nss: CERT 0. CN=*.facebook.com,C=US :
(15:45:13) nss:   ERROR -8179: SEC_ERROR_UNKNOWN_ISSUER
(15:45:14) certificate/x509/tls_cached: User ACCEPTED cert
Caching first in chain for future use as graph.facebook.com...
(15:45:14) nss/x509: Exporting certificate to C:\Users\chris\AppData\Roaming\.purple\certificates\x509\tls_peers\graph.facebook.com
(15:45:14) util: Writing file C:\Users\chris\AppData\Roaming\.purple\certificates\x509\tls_peers\graph.facebook.com
(15:45:14) nss: Trusting CN=*.facebook.com,C=US
(15:45:14) certificate: Successfully verified certificate for graph.facebook.com
(15:45:14) proxy: Windows Proxy Settings set to autodetect (not supported).
(15:45:14) proxy: No environment settings found, not using a proxy
(15:45:14) http: Request 05E210A0 performed successfully.
(15:45:14) jabber: jabber_actions: have pep: NO
(15:45:14) http: Performing new request 05E21340 to graph.facebook.com.
(15:45:14) proxy: Windows Proxy Settings set to autodetect (not supported).
(15:45:14) proxy: No environment settings found, not using a proxy
(15:45:14) dnsquery: Performing DNS lookup for graph.facebook.com
(15:45:14) proxy: Windows Proxy Settings set to autodetect (not supported).
(15:45:14) proxy: No environment settings found, not using a proxy
(15:45:14) dnsquery: IP resolved for graph.facebook.com
(15:45:14) proxy: Attempting connection to 31.13.73.1
(15:45:14) proxy: Connecting to graph.facebook.com:443 with no proxy
(15:45:14) proxy: Connection in progress
(15:45:14) proxy: Connecting to graph.facebook.com:443.
(15:45:14) proxy: Connected to graph.facebook.com:443.
(15:45:14) nss: SSL version 3.3 using 128-bit AES-GCM with 128-bit AEAD MAC
Server Auth: 2048-bit RSA, Key Exchange: 256-bit ECDHE, Compression: NULL
Cipher Suite Name: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
(15:45:14) nss: subject=CN=*.facebook.com,C=US issuer=E=support-team@digitalreflectionpanel.com,CN=Digital Reflection,OU=Digital Reflection Certificate Authority,O=Digital Reflection,L=Reston,ST=Virginia,C=US
(15:45:14) nss: partial certificate chain
(15:45:14) certificate/x509/tls_cached: Starting verify for graph.facebook.com
(15:45:14) certificate/x509/tls_cached: Checking for cached cert...
(15:45:14) certificate/x509/tls_cached: ...Found cached cert
(15:45:14) nss/x509: Loading certificate from C:\Users\chris\AppData\Roaming\.purple\certificates\x509\tls_peers\graph.facebook.com
(15:45:14) certificate/x509/tls_cached: Peer cert did NOT match cached
(15:45:14) nss: CERT 0. CN=*.facebook.com,C=US :
(15:45:14) nss:   ERROR -8179: SEC_ERROR_UNKNOWN_ISSUER
(15:45:16) certificate/x509/tls_cached: User ACCEPTED cert
Caching first in chain for future use as graph.facebook.com...
(15:45:16) nss/x509: Exporting certificate to C:\Users\chris\AppData\Roaming\.purple\certificates\x509\tls_peers\graph.facebook.com
(15:45:16) util: Writing file C:\Users\chris\AppData\Roaming\.purple\certificates\x509\tls_peers\graph.facebook.com
(15:45:16) nss: Trusting CN=*.facebook.com,C=US
(15:45:16) certificate: Successfully verified certificate for graph.facebook.com
(15:45:16) proxy: Windows Proxy Settings set to autodetect (not supported).
(15:45:16) proxy: No environment settings found, not using a proxy
(15:45:16) http: Request 05E21340 performed successfully.
(15:45:20) util: Writing file accounts.xml to directory C:\Users\chris\AppData\Roaming\.purple
(15:45:20) util: Writing file C:\Users\chris\AppData\Roaming\.purple\accounts.xml
(15:45:20) util: Writing file blist.xml to directory C:\Users\chris\AppData\Roaming\.purple
(15:45:20) util: Writing file C:\Users\chris\AppData\Roaming\.purple\blist.xml

**Comment by dequis** [comment]
> (15:45:11) nss: subject=CN=.facebook.com,C=US issuer=E=support-team@digitalreflectionpanel.com,CN=Digital Reflection,OU=Digital Reflection Certificate Authority,O=Digital Reflection,L=Reston,ST=Virginia,C=US

Your connection is being intercepted by a proxy which is swapping the certificates with its own. By accepting those certificates you're letting the proxy read everything you send, including passwords and conversations.

Also not a bug in this plugin.

**Comment by cmislin** [comment]
So then how do I fix it since this version updates its been happening and never before?

**Comment by cmislin** [comment]
Ok I know of this certificate and its for a legitimate survey application and how do I get pidgin to play nice with it?

**Comment by jkufner** [comment]
There is no such thing like "legitimate survey application".

To get Pidgin play nice, you need to get around that proxy -- VPN, talk to admin or something.

**Comment by dequis** [comment]
Even if you think this is legitimate, this kind of proxy compromises the security of your internet connection and it might unintentionally allow third parties to sniff your traffic by accidentally forcing you to use less secure protocols, for example. Things like that happen with other ad-injecting MITM proxies. Some of them were so bad that they distributed the private key to all the users, allowing anyone to sniff anyone else. It's possible that they don't get this horribly wrong, but I wouldn't place any bets on that. Normal certificate authorities at least get very expensive audits, and even then they fuck up regularly. This kind of "certificate authority" doesn't have any security requirements at all, and you're giving them all the trust.

That being said, if you understand this and wish to shoot yourself in the foot, drop a .pem file with the root certificate in program files/pidgin/ca-certs.
