### ISSUE TITLE
[Request] Notification when added to new group chat

### ISSUE THREAD

**Issue by TeamSteeve** [dequis/purple-facebook#258]
I never know if a friend has added me to a group chat on facebook unless I specifically go and check the room list.
It would be nice if there was an option to be notified of any activity on any/all group chats.

On the wiki under [Frequently Asked Questions] > [How do I "mute" a groupchat?] it says:
_Under the account settings, go to the "Advanced" tab, and uncheck "Open new group chats with incoming messages."_
This seems like it would solve my problem if it was turned on. However, I can't see the advanced tab or a way to turn this on. Here's a pic of what I see on the account settings: ![image](https://cloud.githubusercontent.com/assets/20899173/17471605/dc0bee7e-5d88-11e6-826c-933a7c4dbbe6.png)

**Comment by EionRobb** [comment]
Have a look in Help->Plugin Information in pidgin to see what version of the plugin you're using, but it looks like you're either using the wrong plugin or it's out of date

**Comment by TeamSteeve** [comment]
Version: dc35ba3e7fac

**Comment by EionRobb** [comment]
Versions start with the date, like I've just downloaded from that link and got "Version: 20160409~2a24dff~66ee77378d82~110" - can you double-check you dont have multiple copies of the dll in your plugins folder?

**Comment by TeamSteeve** [comment]
Yep. Old version was the issue.
Something must've gone wrong along the line of me trying to update to the new version (caching, not replacing the old one properly, etc.)
Thanks for your help!

**Comment by EionRobb** [comment]
:)
