### ISSUE TITLE
Serious security concern

### ISSUE THREAD

**Issue by erlis** [dequis/purple-facebook#260]
Hi, 

I don't know if this is a bug that belong to this repo but I'm going to report it here and you guys tell me if I should open this in another place. 

After following the instructions on [this ](https://github.com/dequis/purple-facebook/wiki/Installing-on-Windows) page I got Pidgin to connect to Facebook but I noticed something. If you configure your account so you have to enter your password every time you open Pidgin, when it prompt for the password you can put anything and it will still connect. It will succeed with a wrong password! 

This is huge! I don't see any bug about this reported. 

I'll really appreciate if someone looks into this.

**Comment by dequis** [comment]
Duplicate of #66 and #193, see the explanation in those tickets.
