### ISSUE TITLE
"No matches for $.represented_profile.id" has returned

### ISSUE THREAD

**Issue by dstelzer** [dequis/purple-facebook#267]
This error showed up again this morning, though I can't tell what caused it—Messenger proper doesn't show any new messages or changes.

The debug log shows a number of SSL and HTTP-related messages, followed by

> (09:59:34) connection: Connection error on 0x56179997ca60 (reason: 0 description: No matches for $.represented_profile.id)

**Comment by dequis** [comment]
Do you mean the website or the android app?

**Comment by dstelzer** [comment]
Both work and show no change. I can also send messages from both (just tested that now).

Is there a way to get more debug information from this plugin? I installed through apt-get, rather than building from source.

**Comment by dequis** [comment]
https://github.com/dequis/purple-facebook/wiki/Debugging-Logs

**Comment by dstelzer** [comment]
Logs sent to the address listed on that page.

**Comment by dequis** [comment]
Looks like something is wrong with the profile of someone whose last name is Jackson.

Also I thought this was fixed already...

**Comment by dstelzer** [comment]
Curious. I went to her Facebook page and tried to view her profile, but absolutely nothing shows up...not "no information to show", not "you don't have permission", just nothing. An empty page.

![Screenshot](https://cloud.githubusercontent.com/assets/6438440/18555888/1698e7ea-7b2f-11e6-91ab-328365f83367.png)

However everything else appears just fine, and the Intro section next to her Timeline shows basic information. Nothing special appears in the browser console when viewing the empty profile.

**Comment by dequis** [comment]
https://github.com/dequis/purple-facebook/releases/tag/v0.9.0-c9b74a765767
