### ISSUE TITLE
Plugin is disabled when no connection is available

### ISSUE THREAD

**Issue by felagund** [dequis/purple-facebook#269]
Whenever I boot, Pidgin starts before my wifi connection is set up. Invariably, the Facebook plugin gets disabled and I have to manually re-enable it at the bottom of the pidgin window. This also happens to the Skype for Web plugin: https://github.com/EionRobb/skype4pidgin/issues/364 (it does not happend to the Google Hangout plugin). Also, this is possible related: https://developer.pidgin.im/ticket/3905

I think the plugin should try to reconnect harder (like right waya after a failure, then wait a few seconds, than hal a minute, a minute, five minutes and then get disabled).

**Comment by dequis** [comment]
Error message?

**Comment by felagund** [comment]
Unable to connect to graph.facebook.com: SSL Connection Failed

**Comment by felagund** [comment]
On second thought, it actually does what I want. It generally connects after about 40 seconds or so (sometimes earlier, sometimes later). IT is only the skype plugin that does not connect.

**Comment by dequis** [comment]
Oh, okay, yeah this sounded like something that should work to me.
