### ISSUE TITLE
Plugin is not loaded

### ISSUE THREAD

**Issue by paly2** [dequis/purple-facebook#271]
Hello, sorry for my bad English,

I compiled this plugin on GNU/Linux, it has been installed to `/usr/lib/purple-2/libfacebook.so`.

But it seems to be not loaded when Pidgin starts: the Facebook protocol does not appear in the protocols list.

I am using Pidgin 2.11.0 (libpurple 2.10.10), compiled with the following options to the configure script:
```
./configure --disable-screensaver --disable-gtkspell --disable-avahi --disable-dbus --disable-perl --disable-tcl --disable-vv
```

**Comment by dequis** [comment]
What distro are you using? Why are you compiling pidgin? The libpurple version doesn't match, you're doing something wrong there.

**Comment by paly2** [comment]
I am using RaspBian. I am compiled pidgin to have the latest version ;-)

OK, I am gonna recompile libpurple
