### ISSUE TITLE
Links not rendered in self-messages

### ISSUE THREAD

**Issue by marsjaninzmarsa** [dequis/purple-facebook#272]
Steps to reproduce:
1. Login to Messenger on Pidgin and phone.
2. Make sure you have _Show self messages_ option set.
3. Share post or URL with someone from your phone.
4. You have only comment for your attachment, if any. No URLs.

**Comment by dequis** [comment]
Can't reproduce. If this still happens for you, please get a debug log

https://github.com/dequis/purple-facebook/wiki/Debugging-Logs

**Comment by dequis** [comment]
Still happening?

**Comment by dequis** [comment]
I guess not
