### ISSUE TITLE
Failed to  build .deb package on testing/stretch

### ISSUE THREAD

**Issue by HumanG33k** [dequis/purple-facebook#273]
I'm not familiar with debian packaging.

i clone the repo, move in the directory and do :
 $dpkg-buildpackage 
dpkg-buildpackage: info: paquet source purple-facebook
dpkg-buildpackage: info: version source 0.0.0-1
dpkg-buildpackage: info: distribution source UNRELEASED
dpkg-buildpackage: info: source changé par jgeboski <jgeboski@gmail.com>
dpkg-buildpackage: info: architecture hôte amd64
 dpkg-source --before-build purple-facebook
 debian/rules clean
dh clean --with autoreconf
   dh_testdir
   dh_auto_clean
   dh_autoreconf_clean
   dh_clean
 dpkg-source -b purple-facebook
dpkg-source: avertissement: aucun format source indiqué dans debian/source/format, voir dpkg-source(1)
dpkg-source: info: utilisation du format source « 1.0 »
dpkg-source: avertissement: répertoire source « purple-facebook » n'est pas <paquet_source>-<version_amont> « purple-facebook-0.0.0 »
dpkg-source: info: construction de purple-facebook dans purple-facebook_0.0.0-1.tar.gz
dpkg-source: info: construction de purple-facebook dans purple-facebook_0.0.0-1.dsc
 debian/rules build
dh build --with autoreconf
   dh_testdir
   dh_update_autotools_config
   dh_autoreconf
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:31: installing 'build-aux/compile'
configure.ac:35: installing 'build-aux/config.guess'
configure.ac:35: installing 'build-aux/config.sub'
configure.ac:29: installing 'build-aux/install-sh'
configure.ac:29: installing 'build-aux/missing'
Makefile.am: installing './INSTALL'
configure.ac:121: error: required file 'pidgin/libpurple/protocols/facebook/Makefile.in' not found
Makefile.am:2: error: required directory ./pidgin/libpurple/protocols/facebook does not exist
autoreconf: automake failed with exit status: 1
dh_autoreconf: autoreconf -f -i returned exit code 1
debian/rules:8 : la recette pour la cible « build » a échouée
make: *** [build] Erreur 2
dpkg-buildpackage: erreur: debian/rules build a produit une erreur de sortie de type 2

**Comment by dequis** [comment]
Follow the instructions in https://github.com/dequis/purple-facebook/wiki/Building-on-*NIX

Replace 'make' with 'dpkg-buildpackage' if you wish

**Comment by HumanG33k** [comment]
thx it's work now.
Just a little warming : 

libtool: warning: remember to run 'libtool --finish /usr/lib/purple-2'

I close the issue feel free to reopen it.

Maybe you should update the wiki for repo not even exist.
