### ISSUE TITLE
How does one get the "nickname" of a user?

### ISSUE THREAD

**Issue by moomoomoo309** [dequis/purple-facebook#279]
Given libpurple's various alias methods and whatnot, I cannot for the life of me figure out which alias would be equivalent to facebook's "nickname". I'm using the DBus interface, so the naming convention is camelCase rather than snake_case, but the methods are the same.

What I've tried:
- purpleBuddyGetName (Returns a UUID, it looks like)
- purpleBuddyGetAlias (Returns their actual name)
- purpleBuddyGetServerAlias (Same as GetAlias)
- purpleBuddyGetContactAlias (Same as GetAlias)
- purpleBuddyGetLocalAlias (Same as GetName)

Is there a method to do this, or is it just not supported?

**Comment by EionRobb** [comment]
The closest you're going to get is the alias, which is populated with the full name.

There's no "nickname" field brought through from the api, only the "structured_name" see https://bitbucket.org/pidgin/main/src/671723ed2a4261eb6ac0474eec7aab16bba5f792/libpurple/protocols/facebook/api.c?at=default&fileviewer=file-view-default#api.c-2026:2086 and https://bitbucket.org/pidgin/main/src/671723ed2a4261eb6ac0474eec7aab16bba5f792/libpurple/protocols/facebook/facebook.c?at=default&fileviewer=file-view-default#facebook.c-276

**Comment by dequis** [comment]
This looks answered to me
