### ISSUE TITLE
Problem with Facebook transport

### ISSUE THREAD

**Issue by beherit** [dequis/purple-facebook#281]
I have problem with Facebook transport - always I have an error message (on my IM) "Application does not have permission for this action (10)". In Spectrum2 backend logs I see (only fragment):
```
2016-10-27 09:52:34,057 INFO  libpurple: certificate:Successfully verified certificate for b-api.facebook.com
2016-10-27 09:52:34,241 INFO  libpurple: http:Got main header with code 200
2016-10-27 09:52:34,241 INFO  libpurple: http:Got headers end
2016-10-27 09:52:34,241 INFO  libpurple: http:releasing a socket: 0x117d030
2016-10-27 09:52:34,241 INFO  libpurple: http:Request 0x1158fc0 performed successfully.
2016-10-27 09:52:34,241 INFO  libpurple: connection:Connection error on 0x1193560 (reason: 0 description: Application does not have permission for this action (10))
```
Also transport doesn't save settings - after adding new user via IM I have such problem and after restart connections I must put username and password again. I use apt repository:https://jgeboski.github.io/#package-repositories

**Comment by beherit** [comment]
?

**Comment by dequis** [comment]
Well, like i said in the other ticket I need you to pass the PURPLE_UNSAFE_DEBUG=1 PURPLE_VERBOSE_DEBUG=1 environment variables to the spectrum backend somehow. If you don't know how to do this, it might be easier to just install pidgin and try there.

**Comment by beherit** [comment]
I can't install Pidgin on VPS where I don't have any GUI - only SSH :)

**Comment by dequis** [comment]
Locally?

**Comment by beherit** [comment]
This doesn't make sense, problem concerns only VPS.

**Comment by dequis** [comment]
Are you saying you can confirm it works elsewhere?

Either way I can't help without a proper debug log.

**Comment by beherit** [comment]
Not exactly, on other my server I have problem with login - transport say that I put invalid login or password.

**Comment by beherit** [comment]
What is strange - after using transport my FB account is baned and I must change my password...

**Comment by dequis** [comment]
#282 is for you then

**Comment by beherit** [comment]
Oh, after login with app password FB transport start working agin!

**Comment by dequis** [comment]
Neat

**Comment by thundergreen** [comment]
dont use transport anymore .. i added app password and it stopped working again

**Comment by dequis** [comment]
@thundergreen Don't comment here, go to #282
