### ISSUE TITLE
Facebook Messenger protocol

### ISSUE THREAD

**Issue by wklm** [dequis/purple-facebook#283]
What is the mysterious "Facebook Messenger protocol"?

"The application name is shown as "facebook for android" (since this plugin connects in the same way as facebook messenger for android)."

Did you just reverse-engineered the android app to call the same http methods?
How do u deal with encryption? 
Would you mind sharing those methods and maybe the whole codebase as well? 

cheers,
Wojtek

**Comment by dequis** [comment]
I wrote some notes on this here https://wiki.dequis.org/notes/facebook/

>maybe the whole codebase as well?

https://bitbucket.org/pidgin/main/src/default/libpurple/protocols/facebook/

**Comment by wklm** [comment]
Thanks a lot @dequis  :)
