### ISSUE TITLE
login approval

### ISSUE THREAD

**Issue by arnauldb** [dequis/purple-facebook#285]
Hello,

this morning I received this message for facebook plugin when launching pidgin...
![selection_001](https://cloud.githubusercontent.com/assets/13196747/20425569/6e55e41e-ad7b-11e6-873b-ec690c84a069.png)

What can I do ?

thank you,

**Comment by dequis** [comment]
Use an app password

https://www.facebook.com/settings?tab=security&section=per_app_passwords

**Comment by jkufner** [comment]
This looks like a very important detail. Could you put this information
with the link somewhere user will see it? Like note in registration form
and at the end of the login-related error messages?


dx wrote, on 18.11.2016 14:24:

**Comment by dequis** [comment]
It's in https://github.com/dequis/purple-facebook/wiki#basic-usage since yesterday

**Comment by arnauldb** [comment]
thank you dequis for your quick reply and this plugin.
