### ISSUE TITLE
Error when trying to install using github instructions

### ISSUE THREAD

**Issue by nemoskapetanos** [dequis/purple-facebook#290]
Hi,

I get the following error when trying to compile purple facebook using the github instructions.

After I run autogen.sh, I get the following error:

configure.ac:34: error: possibly undefined macro: AC_DISABLE_STATIC
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:35: error: possibly undefined macro: AC_PROG_LIBTOOL
autoreconf: /usr/bin/autoconf failed with exit status: 1

What do I need to do?

Best regards,
Nemo

**Comment by dequis** [comment]
Install libtool

**Comment by nemoskapetanos** [comment]
Thanks!
