### ISSUE TITLE
Unknown HTTP error

### ISSUE THREAD

**Issue by lmfardin** [dequis/purple-facebook#291]
I keep getting "Unknown HTTP error". Is anyone facing the same issue?

**Comment by dequis** [comment]
https://github.com/dequis/purple-facebook/wiki/Debugging-Logs

**Comment by lmfardin** [comment]
I'll try to reproduce it and provide a debug log asap! 

    Em Sábado, 24 de Dezembro de 2016 21:50, dx <notifications@github.com> escreveu:
 

 https://github.com/dequis/purple-facebook/wiki/Debugging-Logs—

**Comment by dequis** [comment]
So, uh, hasn't happened again?

**Comment by lmfardin** [comment]
Ok, this might sound weird, but it seems related to locking my computer (does it affect my status on Pidgin?). When I unlock it, everything seems frozen and takes a long time to get back to normal. Therefore, I haven't been locking it nowadays and so it's been working fine =PBut I promise I'll lock it this week just to be sure. 

    Em Quarta-feira, 4 de Janeiro de 2017 0:39, dx <notifications@github.com> escreveu:
 

 So, uh, hasn't happened again?—

**Comment by lmfardin** [comment]
Well, it disconnects and takes long to re-connect, but I'm not sure it gets disabled. I'll double check. 

    Em Quarta-feira, 4 de Janeiro de 2017 17:21, dx <notifications@github.com> escreveu:
 

 When it returns from locking, does it auto-reconnect after a while? Or does it say the account is disabled? If it doesn't say the account is disabled there's no bug.—

**Comment by lmfardin** [comment]
OK, I followed that procedure for getting debug logs, I left the computer locked for a while and the issue hasn't happened again. I suspect of another plugin. Let me close this. 

    Em Quarta-feira, 4 de Janeiro de 2017 20:04, Luciano Fardin <lmfardin@yahoo.com.br> escreveu:
 

 Well, it disconnects and takes long to re-connect, but I'm not sure it gets disabled. I'll double check. 

    Em Quarta-feira, 4 de Janeiro de 2017 17:21, dx <notifications@github.com> escreveu:
 

 When it returns from locking, does it auto-reconnect after a while? Or does it say the account is disabled? If it doesn't say the account is disabled there's no bug.—
