### ISSUE TITLE
Error 404 - Repository not found?

### ISSUE THREAD

**Issue by HubDamian** [dequis/purple-facebook#292]
Hi there. 

I'm having an issue with installing the purple-facebook via using these commands: 

<code>
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/jgeboski/xUbuntu_$(lsb_release -rs)/ /' >> /etc/apt/sources.list.d/jgeboski.list"
cd /tmp && wget  http://download.opensuse.org/repositories/home:/jgeboski/xUbuntu_$(lsb_release -rs)/Release.key
sudo apt-key add - < Release.key  
sudo apt-get update
sudo apt-get install purple-facebook
</code> 

I used it like 2 months ago and it was fine, but now, it doesn't work. (I just upgraded to ssd).
Any help appreciated.

**Comment by dequis** [comment]
What is the output of `lsb_release -rs`?

**Comment by HubDamian** [comment]
@dequis it says 18

**Comment by dequis** [comment]
Where are those instructions from, anyway? The current instructions don't have any of that noise

http://jgeboski.github.io/

**Comment by HubDamian** [comment]
There are several instructions around the web, and back then i used to be a newbie this time i got around it and literally just downloaded the package off the repository and installed it manually and it works fine. 

I was just wondering how comes it doesn't work now. 

Anyways, thanks.

**Comment by dequis** [comment]
I guess at some point you stopped using ubuntu, because those instructions only work for ubuntu and "18" isn't a valid ubuntu version.

**Comment by dequis** [comment]
This was solved, right?

**Comment by HubDamian** [comment]
Yeah, that was solved.

sent from Outlook dla systemu Android

________________________________

**Comment by dequis** [comment]
Neat
