### ISSUE TITLE
When used with Spectrum 2 and bitlbee, ssome users are just UIN,.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [dequis/purple-facebook#295]
I've recently started using Spectrum 2, to use the Pidgin Plugin with Xabber on Android. However it seems as though the usernames often result in extremely_long_uin@facebook.domain rather than the rendered names. Sometimes you can see Profile pictures but it seems totally random when this happens. 
When used with bitlbee, only the UIN is ever displayed,

**Comment by dequis** [comment]
For bitlbee, use https://github.com/bitlbee/bitlbee-facebook, not this.

For spectrum, I don't know, that sounds like their bug.

**Comment by dequis** [comment]
Did you get anywhere with this?

**Comment by Zombie-Ryushu** [comment]
No. I didn't. The Spectrum 2 group said it was ejabberd's support for part of the XMPP standard, the ejabberd group said no, it was purple-facebook not sending correct XMPP feilds. In the MySQL database, the names all appear. [as they should]. In ejabberd, and Spectrum 2, only some of the names appear, about a third. 

Also there are errors that fill my terminal like this:
(process:19433): Json-CRITICAL **: json_node_get_array: assertion 'JSON_NODE_TYPE (node) == JSON_NODE_ARRAY' failed

(process:19433): Json-CRITICAL **: json_array_get_length: assertion 'array != NULL' failed

(process:19433): Json-CRITICAL **: json_node_get_array: assertion 'JSON_NODE_TYPE (node) == JSON_NODE_ARRAY' failed

(process:19433): Json-CRITICAL **: json_array_get_length: assertion 'array != NULL' failed

But everyone points fingers at everyone else when I ask.

**Comment by dequis** [comment]
Those errors are unrelated and possibly harmless.

Kinda absurd for ejabberd to point fingers at purple-facebook not sending the proper XMPP fields, when purple-facebook does absolutely nothing with XMPP.

So does it work with prosody instead of ejabberd?

**Comment by Zombie-Ryushu** [comment]
I personally have not. However I talked with someone else on FreeNode xmpp who said they had similar issues. In the MySQL database, all the names are filled out right. About a third of the "Real names" Appear in Psi, and Xabber, the rest are rendered as a UIN. There is no rhyme or reason to why this happens. Could there be an illegal character in the name being sent by purple-facebook? 

Skype names do not do this, Yahoo 2016 names and AIM names do not display like this.

**Comment by dequis** [comment]
Yeah okay I'd expect yahoo to have the same problem if this was a problem with spectrum. I'll have a look.

**Comment by dequis** [comment]
lol https://github.com/EionRobb/funyahoo-plusplus/issues/42

Also referencing https://github.com/hanzz/spectrum2/issues/181

**Comment by Zombie-Ryushu** [comment]
Addendum, XMPP info feilds are totally blank on the names section.

**Comment by dequis** [comment]
Is this solved?

**Comment by Zombie-Ryushu** [comment]
No.

**Comment by dequis** [comment]
I installed spectrum and ejabberd and tested this myself, no issues.

The other ticket mentions some stuff about remote roster. That appears to be something added to ejabberd 14.05. You're using "2.1.13". There's your problem.

Also, definitely not an issue with this plugin but that should have been obvious when the funyahoo issue was reported.
