### ISSUE TITLE
Upgrade to Pidgin 2.12.0 breaks the plugin

### ISSUE THREAD

**Issue by roberc51** [dequis/purple-facebook#300]
Just upgraded Pidgin to find my Facebook account now marked as "Unknown" in the Pidgin UI.

**Comment by dequis** [comment]
If you compiled pidgin yourself instead of using distro packages, it probably installed itself to /usr/local/ instead of /usr/, and you'll have to move the plugin from /usr/lib/purple-2/libfacebook.so to /usr/local/lib/purple-2/libfacebook.so

**Comment by ArchbishopFlabrus** [comment]
I can confirm the plugin also not working in Windows as of upgrading Pidgin.

I tried putting the plugin both under Program Files as well as the .purple directory in AppData, to no avail.

**Comment by dequis** [comment]
For windows the only paths you need are the ones in https://github.com/dequis/purple-facebook/wiki/Installing-on-Windows

I just started a fresh windows 7 VM, installed pidgin 2.12.0 there, installed this plugin following those instructions and it works for me.

Please double check that both dlls are in the right places.

If you're still having issues, do the following:

1. Open buddy list -> help menu -> debug window
2. Move the debug window aside, keep it open
3. Buddy list -> tools menu -> plugins
4. A bunch of lines saying "probing" should appear in the debug window, copy all of them and paste them here.

**Comment by ArchbishopFlabrus** [comment]
I've resolved my issue.

I had already installed `libjson-glib-1.0.dll` along with EionRobb's Steamworks plugin, so I had skipped that step when installing this plugin, and caused my issue.

Turns out the DLL in your instructions has a different checksum, and provides functionality for both plugins, so I'll just use that one.

**Comment by EionRobb** [comment]
Oops, I shall update the json-glib dll in the Steam plugin asap

**Comment by dequis** [comment]
So, uh, @roberc51?

**Comment by roberc51** [comment]
Putting libjson-glib-1.0.dll in the right place fixed it for me. Thanks for your help.

**Comment by dequis** [comment]
Neat.
