### ISSUE TITLE
When using different XMPP resources, Spectrum 2 does not transparently forward to Facebook.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [dequis/purple-facebook#303]
When using different XMPP resources, Spectrum 2 does not transparently forward to Facebook. I have a Desktop Pidgin instance with a XMPP resource of Pidgin, and Mobile XMPP Clients with a Resource of Xabber. The Xabber resources are not transparently forwarding to FaceBook when Spectrum 2 uses purple-facebook.

**Comment by dequis** [comment]
You're missing one important part of the bug report: what makes you think this is a purple-facebook bug and not a spectrum2 bug?

**Comment by Zombie-Ryushu** [comment]
AIM, Yahoo++, and SkypeWeb do not demonstrate this behavior. SkypeWeb has a different bug but that bug does not impede Skype's operation.

**Comment by dequis** [comment]
Also what does "transparently forwarding" mean?

**Comment by Zombie-Ryushu** [comment]
The recipient does not know from which XMPP resource that messages originate.

**Comment by dequis** [comment]
So... you're saying that facebook users can somehow see the name of the resource you used to send the message? I don't think I'm getting it. Can you provide some examples, maybe with screenshots?

**Comment by Zombie-Ryushu** [comment]
I'm not sure how I'd provide screenshots from Android like that.

**Comment by dequis** [comment]
http://www.androidcentral.com/android-screenshots

**Comment by dequis** [comment]
Poke?

**Comment by Zombie-Ryushu** [comment]
I resolved the problem by opening another Service Port.
