### ISSUE TITLE
messenger only account with phone number

### ISSUE THREAD

**Issue by brianjmurrell** [dequis/purple-facebook#304]
I've created a [Messenger](https://www.messenger.com/) account without a corresponding Facebook account by using my SMS phone number.

How do I configure pidgin for such an account given that I have no password for that account (that I know of) as it was confirmed by SMS, not by password.

**Comment by dequis** [comment]
This isn't supported because it's not feasible, see #237

>Anyway, it doesn't seem like you can have multiple devices. Also, messenger.com doesn't take logins for those. We might need to guess the unguessable device ID to be able to recover an account. Otherwise we have to create an account on every login. That would mean blocking previously created accounts under the same number, to end up with an empty contact list (and no way to add contacts)

**Comment by brianjmurrell** [comment]
Any idea if there is a way to "convert" an account opened as a messenger-only account into a full facebook account then so that it can be used by this plugin?

**Comment by dequis** [comment]
Nope. Register a normal account and add friends again
