### ISSUE TITLE
Still getting $.viewer.message_threads.sync_sequence_id

### ISSUE THREAD

**Issue by alexolog** [dequis/purple-facebook#309]
Log emailed to @dequis

**Comment by dequis** [comment]
Nothing interesting

>`(22:21:41) facebook: Parsing JSON: {"viewer":{"actor":{"__type__":{"name":"User"},"id":"[...]","name":"First Second","profile_picture":{"uri":"[...]"}},"message_threads":{"unread_count":0,"sync_sequence_id":null,"nodes":[]}}}`
>`(22:21:41) connection: Connection error on 03482ED8 (reason: 0 description: Null value for $.viewer.message_threads.sync_sequence_id)`

So uh, wanna try something experimental? Are you comfortable with commandlines? Or hopefully have access to a linux box? Ideally the same box though, or the same network.

1. Get curl for windows http://www.paehl.com/open_source/?download=curl_753_1_ssl.zip
2. Unzip it somewhere
3. Open a cmd.exe, `cd` there
4. Find the following two lines in your log (not right next to each other)

    ```
    Authorization: OAuth <access token here>
    ```
    ```
    (22:21:41) facebook:   Request Data: fb_api_req_friendly_name=ThreadListQuery&<the rest of the line>
    ```

    There are a few authorization that are all the same, but only one Request Data that is also ThreadListQuery. For the second line, remove the first part so that the line starts with "fb_api_req_friendly_name" .

5. Replace the stuff between `<...>` in this commandline with those two lines from above:

    ```
    curl -X POST https://graph.facebook.com/graphql -d '<request data here>' -H 'Authorization: OAuth <access token here>' -o result.txt
    ```

6. That should write to result.txt. Open it, find `sync_sequence_id` near the beginning, ensure it's still null there. If it's not then I'll be very confused.

7. Now take the same commandline as before, but add the following at the end, with a space before the `-A`

    ```
    -A 'Facebook plugin / Purple / 0.9 [FBAN/Orca-Android;FBAV/38.0.0.22.155;FBBV/14477681]'
    ```

8. Check for the sync_sequence_id again.

**Comment by dequis** [comment]
BTW if that curl package doesn't work for whatever reason, pick different options from https://curl.haxx.se/dlwiz/?type=bin or https://curl.haxx.se/download.html - just ensure it has SSL

**Comment by dequis** [comment]
Ah fuck it i'm going to have to apply that change for everyone anyway, will get a DLL ready in a bit.

At least those instructions will be useful to try other things in case it fails.

**Comment by dequis** [comment]
Please report results with https://github.com/dequis/purple-facebook/releases/tag/v0.9.3-c9b74a765767

**Comment by Malvineous** [comment]
Thank you!  Started getting this error on one PC yesterday afternoon (Windows) and another one a few minutes ago (Linux).  Upgraded the Linux one to the latest git release and I can log in again now!

**Comment by alexolog** [comment]
Appears fixed.  Thanks!

**Comment by dequis** [comment]
Interesting. So somehow the other error with groupchats affected almost everyone but you and some other guy had it in the sequence ID query. I didn't really expect this to help for that too. Well, whatever, glad it helped.

Closing this one to keep the other one visible.
