### ISSUE TITLE
"failed to parse thread information" on all group chats

### ISSUE THREAD

**Issue by IcyInsanities** [dequis/purple-facebook#310]
Starting about an hour ago, I'm seeing "failed to parse thread information" on every group chat causing the plugin to disconnect from the facebook chat. This happens whenever a window for a group chat opens (new message sent by self from other device, new message from other person, or opening from a chat added to buddylist).

The message itself does arrive, and then the plugin disconnects. It will not reconnect until the group chat window is closed. Whether the group chat is named or not seems irrelevant, as does whether the message is read or not.

The list of buddies in the group chat is empty however, so maybe that's where the problem is?

**Comment by IcyInsanities** [comment]
Forgot to mention - removing blist.xml did not help, and I was not removed from any of these chats.
The following two issues do not seem to the same:
https://github.com/dequis/purple-facebook/issues/214
https://github.com/dequis/purple-facebook/issues/261

**Comment by Sgarr17** [comment]
Having same issue, deleting blist.xml and allowing it to regenerate did nothing, nor did deactivating "Mark messages as read."
Updated to latest version of Purple half an hour ago through near-total reinstall. 
Happy to help with debug process in any way.

**Comment by dequis** [comment]
Fix https://github.com/dequis/purple-facebook/releases/tag/v0.9.3-c9b74a765767

**Comment by IcyInsanities** [comment]
Thanks for the super fast fix! Seems to work perfectly so far.

**Comment by Sgarr17** [comment]
Same here. Thanks heaps, Dx. ^^

**Comment by dequis** [comment]
Leave this open for visiblity

**Comment by db-bogdan** [comment]
@dequis is the compiled dll for windows available for download? With the risk of me being dumb, it doesn't seem to work with the one I just downloaded

**Comment by maraakate** [comment]
I've been having this problem with newer builds for a while.  I was using an older build (from about oct 2016) until recently because of the ERROR_QUEUE_OVERFLOW issue.

I upgraded to c9b74a765767 from the windows release link supplied and have verified in the plugins info that it is from this compile.

Whenever I connect it literally opens every conversation I've ever had on facebook that is still archived, including group chats, then disconnects with "Failed to parse thread information".  I delete blist.xml and the problem is still persisting.

**Comment by maraakate** [comment]
Changing the options to DISABLE "Open new group chats with incoming messages" made the parse error stop.  After I reconnected a couple of times to close all the "unread" messages the problem seems to have stopped.

**Comment by blackmailcz** [comment]
is there any fix for windows users please?

**Comment by dequis** [comment]
@blackmailcz I linked https://github.com/dequis/purple-facebook/releases/tag/v0.9.3-c9b74a765767 which says

>Windows users: get the latest build from the usual place: https://github.com/dequis/purple-facebook/wiki/Installing-on-Windows

**Comment by chadcatlett** [comment]
I'm currently running the latest version and normal group chats work fine, but for some reason the 'group' chats related to the sell-your-junk via Facebook seem to cause this same error. I have to go into the Messenger client and archive or delete the chat conversation and then the error will go away.

If you'd like I can generate debug logs and shoot them to you via email.

**Comment by dequis** [comment]
@chadcatlett open a new ticket
