### ISSUE TITLE
ERROR_QUEUE_OVERFLOW

### ISSUE THREAD

**Issue by scarletfires** [dequis/purple-facebook#311]
Hello.

I've been using Purple Facebook for a long while now, many months, without issue. Now, with Pidgin 2.12 I cannot run it. I have already tried a re-install, and a reconfiguration of the account settings. It still occurs.

Hopefully this will help the devs pinpoint the error. :) Thanks for any help!

See here:
![error](https://cloud.githubusercontent.com/assets/26792179/24502071/38743d44-151a-11e7-8322-0793a7787a71.png)

**Comment by dequis** [comment]
1. Check the version of the facebook plugin in buddy list -> help menu -> plugin information, should say something like 0.9.3 or 20170330[...]
2. Ensure there are no old copies of the dll in the plugin directory
3. If you're sure this is the right version, https://github.com/dequis/purple-facebook/wiki/Debugging-Logs

**Comment by dequis** [comment]
Hello?

**Comment by scarletfires** [comment]
Hello,


Sorry. I was able to fix this by completely uninstalling Pidgin and
Purple Facebook, and it is working correctly now on a full re-install.
:) Everything works now, not sure what happened but thank you!

**Comment by dequis** [comment]
Nice.

This sort of thing happened before due to version mixups so it makes sense.

**Comment by athyla** [comment]
For anyone looking for a fix for this issue, the HEX edit solution from this page worked for me. 

https://www.reddit.com/r/pidgin/comments/l14lxt/facebook_messenger_error_queue_underflow/

I'm on openSUSE Tumbleweed, libpurple-plugin-facebook version 0.9.6-1.19.

As mentioned on the linked discussion, I edited libfacebook.so with a hex editor (okteta) and searched for FBAV/192.0.0.31.101 and changed the 192 to 537. On openSUSE, libfacebook.so is located in: /usr/lib64/purple-2/. For safety, make a copy of the original file.
