### ISSUE TITLE
Invalid username or email address (400)

### ISSUE THREAD

**Issue by ProximaSolaris** [dequis/purple-facebook#312]
Hello!

Love your work on keeping this plugin up and running - I love having a desktop program to work off rather than having to use the applet on the website. I'm currently running on Pidgin 2.12.0 and using the latest versions of the dll files as per https://github.com/dequis/purple-facebook/wiki/Installing-on-Windows

Yesterday, I stopped being able to connect to the service with it constantly coming up with the error: 
"Invalid username or email address (400)"

I've tried reentering all the login info, reinstalling the plugin, reinstalling pidgin and nothing seems to be working. Has something changed at the backend at Facebook's end disallowing access? Is there an update or patch to help with the issue?

Any help would be much appreciated!
Thanks!
-Proxima

**Comment by dequis** [comment]
So, does the same login information you use for this plugin work for facebook.com?

As the error says, it accepts email addresses, usernames (for example if the url to your profile is https://www.facebook.com/zuck you'd use "zuck"), and also phone numbers, but i'm not really sure of the format.

**Comment by ProximaSolaris** [comment]
Yeah, my login info is working for the site

**Comment by advcomp2019** [comment]
Check the version of the Facebook plugin in Buddy List -> Help -> Plugin information. It should say something like 0.9.3 or 20170330 or c9b74a765767 in it. That should have that bug gone.

**Comment by dequis** [comment]
Getting the sync_sequence_id error means you're not using the last version, and it also means you found the correct username to log in, so I'm considering this one fixed.
