### ISSUE TITLE
Everyone is offline

### ISSUE THREAD

**Issue by baronvertigovongrahamthesecondofsealand** [dequis/purple-facebook#316]
After the latest release that fixes Facebooks breaking change (c9b74a765767), nobody is online. It looks like I get notifications that they are coming online, but then immediately go offline again.

**Comment by brianjmurrell** [comment]
Ditto.

I get receive messages from a contact that pidgin reports is offline.  I can send a message back once they send me one but until I get a message I don't have any Facebook contacts.  The offline contact shows up in a "Facebook Non-Friends" group even though I have previously dragged those buddies to a different group.

**Comment by danyvega1990** [comment]
I have exactly that problem, upgrade to the latest version to fix the c9b74a765767 problem and now nobody is online, sometimes I see somebody online when that person connects himself but when the chat refresh the contacts everybody offline again

**Comment by dequis** [comment]
https://github.com/dequis/purple-facebook/wiki/Debugging-Logs

**Comment by dequis** [comment]
Anyone?

**Comment by DMorgado** [comment]
Hello,
yesterday I had this very same problem. But not today, now it appears to be working fine. :)

Thanks

**Comment by dequis** [comment]
So, uh, @baronvertigovongrahamthesecondofsealand @brianjmurrell @danyvega1990? Is it still broken?

**Comment by klobes5** [comment]
I have this issue as well. Would love some elucidation as to the cause.

**Comment by solbu** [comment]
I had the same problem, but the problem disappeared a few days later.
(Running Mageia 5)

**Comment by dequis** [comment]
I guess it's fine now then.
