### ISSUE TITLE
Certificate issues after switching to latest release

### ISSUE THREAD

**Issue by haho16** [dequis/purple-facebook#317]
Hey, 
I wanted to add myself in the discussion over the latest issue of connecting to FB, but couldn't see my problem in there, so I decided to make a new issue alltogether :). 

So, basically, after having the same issues as most people these days, I updated to the latest release. I am not sure if I should have done it via libtools, as I just used: 
`~/home/.../purple-facebook../  $ make clean`
and deleted the entire folder from my home directory and the files in the /usr/lib/purple-2 :/.  After this, I just build the latest release. Here outputs of make and make install: 
> Making all in pidgin/libpurple/protocols/facebook                                
make[1]: Entering directory `/home/.../purple-facebook-0.9.3-c9b74a765767/pidgin/libpurple/protocols/facebook'                                      
make[1]: Nothing to be done for `all'.                                         
make[1]: Leaving directory `/home/.../purple-facebook-0.9.3-c9b74a765767/pidgin/libpurple/protocols/facebook'                                       
make[1]: Entering directory `/home/.../purple-facebook-0.9.3-c9b74a765767'                                                                       
make[1]: Nothing to be done for `all-am'.                                      
make[1]: Leaving directory `/home/.../purple-facebook-0.9.3-c9b74a765767'            

> Making install in pidgin/libpurple/protocols/facebook                           
make[1]: Entering directory `/home/.../purple-facebook-0.9.3-c9b74a765767/pidgin/libpurple/protocols/facebook'                                        
make[2]: Entering directory `/home/.../purple-facebook-0.9.3-c9b74a765767/pidgin/libpurple/protocols/facebook'                                   
make[2]: Nothing to be done for `install-exec-am'.                                
 /bin/mkdir -p '/usr/lib/purple-2'                                         
 /bin/sh ../../../../libtool   --mode=install /usr/bin/install -c   libfacebook.la
 '/usr/lib/purple-2'                                               
libtool: install: /usr/bin/install -c .libs/libfacebook.so /usr/lib/purple-2/libfacebook.so                                                           
libtool: install: /usr/bin/install -c .libs/libfacebook.lai /usr/lib/purple-2/libfacebook.la                                                                        
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/sbin" ldconfig -n /usr/lib/purple-2  

This resulted in: 
> $ ls /usr/lib/purple-2
libfacebook.la  libfacebook.so           

I started pidgin and cannot connect. Firstly, it was giving me the "Unable to connect tographi.facebook.com: Cancelled" error. I decided to bravely do a rollback and re-install pidgin, libpurple-dev + the latest release in case something was stuck out there that confused pidgin. After the fresh re-installs, I now get this "Unable to connect to b-api.facebook.com: Cancelled". Here is a debug window output:

>(12:46:09) util: Writing file prefs.xml to directory /home/.../.purple
(12:46:09) util: Writing file /home/.../.purple/prefs.xml
(12:46:31) http: Timeout reached for request 0x7f320edfeae0
(12:46:31) http: Request 0x7f320edfeae0 performed without success.
(12:46:31) connection: Connection error on 0x7f320edfc040 (reason: 0 description: Unable to connect to b-api.facebook.com: Cancelled)
(12:46:31) account: Disconnecting account - (0x7f320e382600)
(12:46:31) connection: Disconnecting connection 0x7f320edfc040
(12:46:31) connection: Destroying connection 0x7f320edfc040
(12:46:36) util: Writing file accounts.xml to directory /home/.../.purple
(12:46:36) util: Writing file /home/.../.purple/accounts.xml
(12:46:58) autorecon: do_signon called
(12:46:58) autorecon: calling purple_account_connect
(12:46:58) account: Connecting to account -.
(12:46:58) connection: Connecting. gc = 0x7f320ee6b7c0
(12:46:58) http: Performing new request 0x7f320ee59f00 to b-api.facebook.com.
(12:46:58) autorecon: done calling purple_account_connect
(12:46:58) g_log: purple_ssl_connect_with_ssl_cn: assertion 'purple_ssl_is_supported()' failed
(12:46:58) http: failed creating new socket(12:47:28) http: Timeout reached for request 0x7f320ee59f00
(12:47:28) http: Request 0x7f320ee59f00 performed without success.

I am on Linux Mint 17.3 Rosa 64-bit, Kernel Linux 3.19.0-32-generic x86_64. Thanks a lot for the plugin and the work :).

**Comment by dequis** [comment]
>and deleted the entire folder from my home directory and the files in the /usr/lib/purple-2

Holy crap, no need to murder everybody to get rid of a spider.

>(12:46:58) g_log: purple_ssl_connect_with_ssl_cn: assertion 'purple_ssl_is_supported()' failed

You removed all the ssl plugins. You need to reinstall pidgin/libpurple to get it back.

**Comment by haho16** [comment]
> Holy crap, no need to murder everybody to get rid of a spider.

Haha, ok I got it. I re-installed also the libpurple library and now it works fine. I guess next time libtools to switch to a newer release?
Thanks anyhow, you can close the issue then :).
