### ISSUE TITLE
plugin quit working as of today

### ISSUE THREAD

**Issue by aumua123** [dequis/purple-facebook#320]
This is on windows with the 'libfacebook.dll'.

I log and and see all my facebook contacts, but as soon as I try to message someone I get 'disconnected. failed to send message'. 

Nothing else has changed on my system over the past few days AFAIK.

**Comment by dequis** [comment]
Buddy list -> help menu -> plugin information

Find the facebook plugin in there, copy and paste the version here.

**Comment by aumua123** [comment]
Version: 20161121~a157645~c9b74a765767~117

**Comment by advcomp2019** [comment]
You need to upgrade and see if it happens with the newest version. Then report back.

**Comment by aumua123** [comment]
I knew that. Just testing ya. :)

The newest version works.
