### ISSUE TITLE
Update Windows build to latest version

### ISSUE THREAD

**Issue by ponjadito23** [dequis/purple-facebook#321]
The build listed in https://github.com/dequis/purple-facebook/wiki/Installing-on-Windows is stuck on the version 20160409~2a24dff~66ee77378d82~110 and doesn't work anymore after the facebook changes.

**Comment by dequis** [comment]
Unlikely, otherwise it would be broken for everyone else. Check that you don't have old DLLs laying around

**Comment by ponjadito23** [comment]
Just checked and that was the problem, I was trying to update the file in program files but I also had the plugin in roaming/.purple, sorry
