### ISSUE TITLE
Messages not received

### ISSUE THREAD

**Issue by cipri-tom** [dequis/purple-facebook#322]
Hi,

Some times the messages are not received by Pidgin (plugin version `20170330~3cbb433~c9b74a765767~126`). It first happened a few days ago and today again. There are no apparent problems; no error in Pidgin window, network works fine. I can see messages on the website, but nothing reaches Pidgin.

I know this is very cryptic and I would appreciate any advice on how to debug it.

**Comment by dequis** [comment]
What sort of messages? Text only? Image attachments?

Is it individual messages in the middle of the conversation or entire parts of the conversation?

How often does it happen?

**Comment by cipri-tom** [comment]
All messages. I am actively chatting yet nothing arrives in Pidgin. Strangely, sending works: so if I say something in Pidgin, I see it in the chat, but the reply is not shown back in Pidgin. And it remains like that until ... **I think** until I reconnect to the network

It happens very rarely ! Like, only happened a few times. I understand at this point there's not much we can do to debug it, since it works now (maybe because of restart).

What can I do the next time it happens ? Is there a log that I could check ? I don't mind enabling extra logging, if possible, or debug symbols. Can I attach a `gdb` session to it and look for what happens ? I don't mind getting my hands dirty 😃 

It's a shame it's so infrequent, though

**Comment by dequis** [comment]
Odd.

https://github.com/dequis/purple-facebook/wiki/Debugging-Logs

**Comment by dequis** [comment]
Still happening?

**Comment by cipri-tom** [comment]
Nothing yet. It must have been some problem of network connection or something .. I'm sorry it's not reproducible. Let's close it for now.
