### ISSUE TITLE
not falling back to ipv4

### ISSUE THREAD

**Issue by brianjmurrell** [dequis/purple-facebook#323]
It would seem, from where I am at least (through two providers even) that graph.facebook.com's ipv6 address (2a03:2880:f011:1:face:b00c:0:1) is down and that is causing the plugin to fail to connect:

```
(07:01:28) account: Connecting to account [redacted].
(07:01:28) connection: Connecting. gc = 0x555558167530
(07:01:28) http: Performing new request 0x5555597c9a50 to graph.facebook.com.
(07:01:28) dnsquery: Performing DNS lookup for graph.facebook.com
(07:01:28) dns: Wait for DNS child 24490 failed: No child processes
(07:01:28) dns: Created new DNS child 24663, there are now 1 children.
(07:01:28) dns: Successfully sent DNS request to child 24663
(07:01:28) dns: Got response for 'graph.facebook.com'
(07:01:28) dnsquery: IP resolved for graph.facebook.com
(07:01:28) proxy: Attempting connection to 2a03:2880:f011:1:face:b00c:0:1
(07:01:28) proxy: Connecting to graph.facebook.com:443 with no proxy
(07:01:28) proxy: Connection in progress
(07:01:32) account: Connecting to account [redacted].
(07:01:33) util: Writing file accounts.xml to directory /home/brian/.purple
(07:01:33) util: Writing file /home/brian/.purple/accounts.xml
(07:01:38) prefs: /pidgin/debug/filter changed, scheduling save.
(07:01:40) prefs: /pidgin/debug/filter changed, scheduling save.
```
But graph.facebook.com has an ipv4 address also:

```
$ host graph.facebook.com
graph.facebook.com is an alias for api.facebook.com.
api.facebook.com is an alias for star.c10r.facebook.com.
star.c10r.facebook.com has address 157.240.3.19
star.c10r.facebook.com has IPv6 address 2a03:2880:f001:6:face:b00c:0:2
star.c10r.facebook.com mail is handled by 10 msgin.vvv.facebook.com.
```

Yet, while looking at the Pidgin log or even using tcpdump I don't see anything that indicates that the plugin is falling back to the ipv4 that is returned in the query for graph.facebook.com when the ipv6 address fails (or put more generically that it's trying alternate addresses when the first address that it tries to connect to fails).

**Comment by dequis** [comment]
```
PING 2a03:2880:f011:1:face:b00c:0:1(2a03:2880:f011:1:face:b00c:0:1) 56 data bytes
64 bytes from 2a03:2880:f011:1:face:b00c:0:1: icmp_seq=1 ttl=56 time=103 ms
64 bytes from 2a03:2880:f011:1:face:b00c:0:1: icmp_seq=2 ttl=56 time=102 ms
```

It's your network. Probably a routing issue halfway through.

Also, it's not up to this plugin to handle DNS resolution business or ipv6/ipv4 fallback, that's libpurple stuff.

**Comment by brianjmurrell** [comment]
> It's your network. Probably a routing issue halfway through.

As I said "from where I am at least".  But whether the ipv6 address is reachable from here is orthogonal.  The point is that when being given multiple addresses and a connection to the first one fails, it is not falling back to any of the subsequent ones.

> Also, it's not up to this plugin to handle DNS resolution business or ipv6/ipv4 fallback

Well, to be clear, it's not technically "ipv6/ipv4 fallback" but rather just trying all of the addresses that a name returns, in the order RFC 3484 prescribes which is to use IPv6 first.

> that's libpurple stuff.

Fair enough.  I have opened a [ticket](https://developer.pidgin.im/ticket/17204) with them.  Thanks for letting me know.
