### ISSUE TITLE
Is Facebook "App Passwords" still supported by Facebook?

### ISSUE THREAD

**Issue by bkidwell** [dequis/purple-facebook#327]
The README for this plugin strongly suggests using the Facebook App Password feature, and I agree.

Some months ago the App Password for my personal laptop broke, and I didn't do anything about it immediately. Last week I went into Facebook from my desktop browser to delete and create a new App Password, and I found that clicking "App Passwords" in Security Settings does nothing at all.

Does anyone else have this problem, and is this feature known to be broken or unsupported?

I contacted the Facebook help desk and they told me to go stick my head in a pig. "Your feedback will be used to improve Facebook. Thanks for taking the time to make a report."

**Comment by dequis** [comment]
Works for me on firefox.

![screen shot 2017-05-18 at 16 52 51-fullpage](https://cloud.githubusercontent.com/assets/94108/26220902/f2ac3418-3bea-11e7-96d3-8d9b28c9c6a1.png)

**Comment by wrtaff** [comment]
I just installed the Purple Facebook plugin today (WHICH IS TOTALLY AWESOME) and was also able to use the app password option - looked the same as dequis above, running chrome on a linux box.  I think it's working fine!  Good luck to you!

**Comment by bkidwell** [comment]
We're not going to solve my particular problem here; it's now clearly off-topic. Thanks for the replies to help me narrow it down.

**Comment by dequis** [comment]
@bkidwell Still, I'm curious, is it still not there? Can you post a screenshot?

**Comment by bkidwell** [comment]
I can't reproduce the problem now. (I tried, just now, with and without my two extensions disabled.) I did get the problem consistently for over a month whenever I thought to try it; this is the first time I've had it work since 2017 quarter 1.
