### ISSUE TITLE
mercurial is waaaaay slow

### ISSUE THREAD

**Issue by brianjmurrell** [dequis/purple-facebook#334]
The whole Mercurial cloning bit in update.sh takes waaaaay too long.  Looking at the time left it's got to be over an hour.

It's much (much!) faster to just fetch the tarball of what you want using a URL such as https://bitbucket.org/pidgin/main/get/c9b74a765767.tar.gz.

I'll submit a PR once I have `update.sh` updated to do this instead.

**Comment by brianjmurrell** [comment]
Not to mention, I keep getting an error here, after waiting the hour or so:

```
applying clone bundle from https://media-api.atlassian.io/file/7c1d2160-a2cc-43cc-9d3e-a765cc6851a6/binary?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI3MjY1ZTlhOS0yYmRhLTRmN2QtYTcwMy01ZmVhNjgzNDViMjYiLCJhY2Nlc3MiOnsidXJuOmZpbGVzdG9yZTpmaWxlOjdjMWQyMTYwLWEyY2MtNDNjYy05ZDNlLWE3NjVjYzY4NTFhNiI6WyJyZWFkIl19LCJuYmYiOjE0OTcwMjMxNjUsImV4cCI6MTQ5NzAyMzU4NX0.pO4c1g60kdKFkn8NHK-kA2xq-WTK6OQkakaRjVCxWzU&client=7265e9a9-2bda-4f7d-a703-5fea68345b26
adding changesets
adding manifests                                                                                                                                                       
transaction abort!                                                                                                                                                     
rollback completed                                                                                                                                                     
abort: stream ended unexpectedly (got 0 bytes, expected 4)
abort: repository .pidgin not found!
abort: repository .pidgin not found!
```

**Comment by dequis** [comment]
You do not need to use mercurial at all. See:

https://github.com/dequis/purple-facebook/wiki/Building-on-*NIX#compiling

The release tarballs include everything you need:

https://github.com/dequis/purple-facebook/releases/download/v0.9.4-c9b74a765767/purple-facebook-0.9.4-c9b74a765767.tar.gz

**Comment by brianjmurrell** [comment]
Hrm.  When I grabbed the 0.9.4 tarball almost 2 hours ago it was only 37,856 bytes big.  Now it's 459,535.

**Comment by dequis** [comment]
The small one is the "source code (tar.gz)" link that is autogenerated from the source tree, do not touch that one. Unfortunately github provides no way to get rid of those.

**Comment by brianjmurrell** [comment]
Oh.  I see.  Thanks for clarifying.
