### ISSUE TITLE
Will there be a repo for debian stretch (to be released next week)

### ISSUE THREAD

**Issue by ManfredSchenk** [dequis/purple-facebook#335]
Since debian Stretch will probably be released in about one week I wonder if there will be some stretch-specific packages.
Or should the packages provided for jessie still work with stretch?

**Comment by dequis** [comment]
It's not up to me, it's up to OBS, but yes, there will be a repo for stretch.

Jessie packages might work too.

**Comment by dequis** [comment]
It's enabled now
