### ISSUE TITLE
400 Error occurs on startup as plugin loads a chat

### ISSUE THREAD

**Issue by metalman88** [dequis/purple-facebook#337]
I start the client and immediately after it loads a series of messages sent to me, I get a 400 error.
I used the latest version and it's still doing it.
It says my account is disabled -- Invalid HTTP Response Code (400)
Facebook
	Author: (null)
	Version: 20170330~3cbb433~c9b74a765767~126
	Website: https://github.com/dequis/purple-facebook
	ID String: prpl-facebook
	Loadable: Yes
	Loaded: Yes

**Comment by dequis** [comment]
That's old. Get the latest version

**Comment by metalman88** [comment]
Hm, correct-a-mundo, seems like my download trolled me and I had the old version. Thanks for confirming that, works now.

Facebook
	Author: (null)
	Version: 20170608~c40d9fa~c9b74a765767~128
	Website: https://github.com/dequis/purple-facebook
	ID String: prpl-facebook
	Loadable: Yes
	Loaded: Yes
