### ISSUE TITLE
Pidgin logs you out when image pasted into facebook messenger

### ISSUE THREAD

**Issue by bclarke-pixelcube** [dequis/purple-facebook#338]
As of Wednesday if you paste an image into Facebook messenger pidgin now disables the account when it tries to display it. Comes up with the error Invalid HTTP response code (400). You can just re-enable the account and it will log back in fine.

**Comment by dequis** [comment]
If you're running the latest version: https://github.com/dequis/purple-facebook/wiki/Debugging-Logs

**Comment by bclarke-pixelcube** [comment]
[pidgin.zip](https://github.com/dequis/purple-facebook/files/1079954/pidgin.zip)

Facebook
	Author: (null)
	Version: 20170330~3cbb433~c9b74a765767~126
	Website: https://github.com/dequis/purple-facebook
	ID String: prpl-facebook
	Loadable: Yes
	Loaded: Yes

**Comment by bclarke-pixelcube** [comment]
Updated to:

Facebook
	Author: (null)
	Version: 20170608~c40d9fa~c9b74a765767~128
	Website: https://github.com/dequis/purple-facebook
	ID String: prpl-facebook
	Loadable: Yes
	Loaded: Yes

Now working again. Apologies for the inconvenience.
