### ISSUE TITLE
Connection closes upon picture receive of any sort

### ISSUE THREAD

**Issue by buchty** [dequis/purple-facebook#339]
Since a couple of days, the connection closes once a picture is received. Doesn't matter what kind of picture it is (sticker, large smiley, picture transfer).

Pending messages get transmitted up to the picture, then the connection closes and will drop again upon reconnect as long as the picture message is still pending.

Temporary fix is to mark those messages as read in the browser.

(Already tried with the latest commit c40d9fa, problem persists.)

**Comment by EionRobb** [comment]
Check your version info in Help->Plugin Information, you probably have an older version of the plugin installed somewhere you don't realise such as ~/.purple/plugins

**Comment by buchty** [comment]
This is the only one appearing:

Facebook
	Author: (null)
	Version: 0.9.3-c9b74a765767
	Website: https://github.com/dequis/purple-facebook
	ID String: prpl-facebook
	Loadable: Yes
	Loaded: Yes

**Comment by EionRobb** [comment]
That's a very old version of the plugin.  Check that you don't have multiple .so's installed

**Comment by wolfy67** [comment]
The current ( newest ) version is 0.9.4

**Comment by EionRobb** [comment]
@wolfy67 no, you should be seeing a date for the start of the version, eg "Version: 20170608~c40d9fa~c9b74a765767~128"

**Comment by buchty** [comment]
Thanks, EionRobb ... 0.9.4-c9b74a765767 now after cleaning/restart.

**Comment by dequis** [comment]
>you should be seeing a date for the start of the version

For the record: Both version string formats can be valid, it depends on the build system. I'll sort things out when I get to 1.0.
