### ISSUE TITLE
*wrong way symbol* "xyz-account disabled" Invalid HTTP response code (400) can't connect to facebook as of today

### ISSUE THREAD

**Issue by flzzjw72z** [dequis/purple-facebook#340]
OS is Linux Mint 17.3, fully updated, even a Pidgin PPA to be sure I'm running the latest version my distro can use (2.10.11), apparently those who haven't abandoned Ubuntu past 12.10 can get 2.10.13 but nothing has changed in config, at least, anything I think could directly impact Pidgin. I've updated adobe-flashplugin (2 in 4 days heh), Firefox, WoeUSB (what WinUSB became) and some suggested dependencies that weren't automatically installed with it that I decided to install to cover bases in the future tense. libgnutls related packages such as libgnutls-openssl. Now that's something I imagine could cause some issue, but it was installed on the 13th and then Pidgin connected to Facebook without a problem. It had to happen today as I am trying to organize something for Father's Day with my brother to get my brother some gift...my brother detests talking on the phone, he only sms's and use IM programs on his phone...so yeah, this sucks, I logged in to the facebook site thinking it would make things fine, but it didn't, where a few times or maybe just once, it did make everything work fine. I had to take a picture recognizing test because of my using a vpn service but that's it.

Anybody else with this problem today? Especially if you're using Linux Mint 17.3 LTS. Thanks a lot for your attention.

![pidginfail](https://user-images.githubusercontent.com/23146298/27255338-6ea2d39c-536a-11e7-8ec9-3d5479da6118.png)

**Comment by dequis** [comment]
Upgrade to 0.9.4

**Comment by flzzjw72z** [comment]
What package exactly?

libpurple-dev; bin and 0 are version 1:2.10.11-1ubuntu0+pidgin7.14.04

**Comment by dequis** [comment]
purple-facebook

**Comment by flzzjw72z** [comment]
This package isn't even in synaptic.

Anyway, why would it stop working all of a sudden like that? But sure, I'll compile it if there is no PPA.

**Comment by dequis** [comment]
>This package isn't even in synaptic.

You need to install it in the same way that you installed it originally.

The installation instructions in [the wiki][1] link debian/ubuntu repositories which may work for linux mint if you pick the equivalent ubuntu version. Otherwise build it.

>Anyway, why would it stop working all of a sudden like that?

Times change and nothing lasts forever

[1]: https://github.com/dequis/purple-facebook/wiki

**Comment by flzzjw72z** [comment]
Yup, I'm just surprised that update manager didn't tell me, I remember it told me when a purple-facebook update would show up in the mint update manager. But yeah I compiled it and succeeded installing it with my finally perfected checkinstall command. All's good! Thanks a lot. Searching on search engines for an hour or so gave me no info that a new purple-facebook was out too, just thought you should know that.

**Comment by dequis** [comment]
Neat.

In the future just check the [releases page][1]

You can also check other [open issues][2] in this issue tracker, particularly that one which is labeled "resolved" and has the same error you have in the title.

[1]: https://github.com/dequis/purple-facebook/releases
[2]: https://github.com/dequis/purple-facebook/issues
