### ISSUE TITLE
Missing Messages

### ISSUE THREAD

**Issue by jaymzh** [dequis/purple-facebook#341]
Starting today I seem to just not be getting messages in most of my chat windows... they appear on the web, but not in pidgin.

**Comment by dequis** [comment]
https://github.com/dequis/purple-facebook/wiki/Debugging-Logs

**Comment by jaymzh** [comment]
yeah I'll gather logs in a bit... I'll need to scrub them, so I need time. Was just throwing this out there so I don't forget and in case others are seeing it.

**Comment by eddiem9** [comment]
I was also seeing this....restarted to turn on logging and the issue went away.

**Comment by jaymzh** [comment]
Yeah, things are working today.
