### ISSUE TITLE
Works for one account, won't work for second account - Error validating access token

### ISSUE THREAD

**Issue by Oook** [dequis/purple-facebook#344]
This seems to be a similar issue that others have reported. I have two FB accounts. One of them works just fine. The other does this:

> Error validating access token: The session has been invalidated because the user changed their password or Facebook has changed the session for security reasons. (452)

This happens *instantly*. No pause at all, no delay at all. Whammo, the instant I try to enable the account, this message appears. No other message appears.

- Errors thrown by pidgin:
- Message shown by the facebook website (particularly pay attention to mentions of "unfamiliar location" or "suspicious activity"): None. Absolutely non. Account works just fine as always even from different browsers.
- Is it all the same internet connection?: Yes
- Are you using any proxies / VPNs?: No
- Were you using app passwords? Did the situation improve after using app passwords?: Tried app passwords, same thing happens.
- Did it happen once or did it happen on every login attempt?: Happens every time. I have never been able to get the second account to work.
- Was it enough to change the password?: I changed password, still won't work.
- Have you used this plugin before? If so, when was the last time it worked?: It has always worked with one account, it has never worked with the other.
- Have you used any other third party facebook clients like miranda?: No

*(admin edit: fixed text formatting)*

**Comment by Oook** [comment]
Update: Does this from different locations, different computers, with different ISPs.

**Comment by dequis** [comment]
>Update: Does this from different locations, different computers, with different ISPs.

Different pidgin installations or using something like pidgin portable?

>This actually worked a long time ago back when facebook was still ... xmpp? Didn't FB used to be xmmp? It's just since they dropped the old protocol that I've not been able to get this account to work in pidgin.

That would be since 2015

**Comment by Oook** [comment]
So I went to another computer to do some more testing, and for reasons unknown to me, it refuses to recognize libfacebook.so. Completely ignores it. No idea why. Works on one machine, not on another. I'll be back with test results when I have the time to get this working...

**Comment by Oook** [comment]
So I revisited this issue, and now it works. I haven't changed anything on my end, I wonder if FB did something on their end?

**Comment by dequis** [comment]
Huh. Well. I guess I'll just close this, then
