### ISSUE TITLE
Picture messages do not show

### ISSUE THREAD

**Issue by IcyInsanities** [dequis/purple-facebook#347]
Starting a couple days ago, picture messages do not show up in pidgin. At first, it was only when a picture was sent to a chat that had been dormant for a bit of time (few hours), and now it's all pictures sent to chats. This affects both individual and group chats.

**Comment by dequis** [comment]
https://github.com/dequis/purple-facebook/wiki/Debugging-Logs

**Comment by dequis** [comment]
> Hi dx,
> 
> Thanks for the quick response. Attached is the log file.
> 
> I took a quick glance, seems the interesting line is 1818:
> 
> `(23:21:37) facebook: Failed to retrieve image http://scontent.xx.fbcdn.net/[snip]: Error writing to scontent.xx.fbcdn.net: Bad file descriptor`
> 
> That link loads for me in browser though.
> 
> FYI, in case it’s relevant: I have the windows credentials plugin which might be why I need to enter my password on every reconnect to fb. Never tested it at the cause yet.

Interesting one!

```
(23:21:37) http: Request 05551AE0 performed successfully.
(23:21:37) facebook: HTTP Response (05551AE0):
(23:21:37) facebook:   Response Error: 200
(23:21:37) facebook:   Response Data: {"content_type":"image\/jpeg","filename":"image-[snip].jpg","redirect_uri":"[snip]"}
(23:21:37) facebook: Parsing JSON: {"content_type":"image\/jpeg","filename":"image-[snip].jpg","redirect_uri":"[snip]"}

(23:21:37) http: Performing new request 05551648 for http://scontent.xx.fbcdn.net/[snip].
(23:21:37) http: Connecting to http://scontent.xx.fbcdn.net/[snip]...
(23:21:37) http: destroying socket: 06E64D40
(23:21:37) dnsquery: Performing DNS lookup for scontent.xx.fbcdn.net
(23:21:37) http: new socket created: 06E652B0
(23:21:37) http: locking a (new) socket: 06E652B0
(23:21:37) dnsquery: IP resolved for scontent.xx.fbcdn.net
(23:21:37) proxy: Attempting connection to 2a03:2880:f022:b:face:b00c:0:3
(23:21:37) proxy: Connecting to scontent.xx.fbcdn.net:80 with no proxy
(23:21:37) proxy: Connection in progress
(23:21:37) proxy: Connecting to scontent.xx.fbcdn.net:80.
(23:21:37) proxy: Connected to scontent.xx.fbcdn.net:80.
(23:21:37) http: Generated request headers:
GET /[snip].jpg?[snip] HTTP/1.1
Host: scontent.xx.fbcdn.net
Connection: Keep-Alive
Accept: */*
Accept-Encoding: gzip, deflate

(23:21:37) http: error: Error writing to scontent.xx.fbcdn.net: Bad file descriptor
(23:21:37) http: Cancelling connection 05551648...
(23:21:37) http: releasing a socket: 06E652B0
(23:21:37) http: destroying socket: 06E652B0
(23:21:37) http: Request 05551648 performed without success.
(23:21:37) facebook: Failed to retrieve image http://scontent.xx.fbcdn.net/[snip]: Error writing to scontent.xx.fbcdn.net: Bad file descriptor
```

So, getAttachment succeeds, other ipv6 connections succeed. Pidgin 2.12.0, windows, 0.9.4.

Other plugins:

```
(23:18:50) plugins: probing C:\Users\Shir\AppData\Roaming\.purple\plugins\keysperminute.dll
(23:18:50) plugins: probing C:\Users\Shir\AppData\Roaming\.purple\plugins\pidgin-logstatus-0.7.dll
logstatus: entry
(23:18:50) plugins: probing C:\Users\Shir\AppData\Roaming\.purple\plugins\pidgin-wincred.dll
(23:18:50) plugins: probing C:\My Programs\Pidgin\plugins\autoaccept.dll
(23:18:50) plugins: probing C:\My Programs\Pidgin\plugins\buddynote.dll
(23:18:50) plugins: probing C:\My Programs\Pidgin\plugins\convcolors.dll
(23:18:50) plugins: probing C:\My Programs\Pidgin\plugins\extplacement.dll
(23:18:50) plugins: probing C:\My Programs\Pidgin\plugins\gtkbuddynote.dll
(23:18:50) plugins: probing C:\My Programs\Pidgin\plugins\history.dll
(23:18:50) plugins: probing C:\My Programs\Pidgin\plugins\iconaway.dll
(23:18:50) plugins: probing C:\My Programs\Pidgin\plugins\idle.dll
(23:18:50) plugins: probing C:\My Programs\Pidgin\plugins\joinpart.dll
(23:18:50) plugins: probing C:\My Programs\Pidgin\plugins\libaim.dll
(23:18:50) plugins: probing C:\My Programs\Pidgin\plugins\libbonjour.dll
(23:18:50) plugins: probing C:\My Programs\Pidgin\plugins\libfacebook.dll
(23:18:50) plugins: probing C:\My Programs\Pidgin\plugins\libgg.dll
(23:18:50) plugins: probing C:\My Programs\Pidgin\plugins\libhangouts.dll
(23:18:50) plugins: probing C:\My Programs\Pidgin\plugins\libicq.dll
(23:18:51) plugins: probing C:\My Programs\Pidgin\plugins\libirc.dll
(23:18:51) plugins: probing C:\My Programs\Pidgin\plugins\libnovell.dll
(23:18:51) plugins: probing C:\My Programs\Pidgin\plugins\libsametime.dll
(23:18:51) plugins: C:\My Programs\Pidgin\plugins\libsametime.dll has a prefs_info, but is a prpl. This is no longer supported.
(23:18:51) plugins: probing C:\My Programs\Pidgin\plugins\libsilc.dll
(23:18:51) plugins: probing C:\My Programs\Pidgin\plugins\libsimple.dll
(23:18:51) plugins: probing C:\My Programs\Pidgin\plugins\libxmpp.dll
(23:18:51) plugins: probing C:\My Programs\Pidgin\plugins\log_reader.dll
(23:18:51) plugins: probing C:\My Programs\Pidgin\plugins\markerline.dll
(23:18:51) plugins: probing C:\My Programs\Pidgin\plugins\newline.dll
(23:18:51) plugins: probing C:\My Programs\Pidgin\plugins\notify.dll
(23:18:51) plugins: probing C:\My Programs\Pidgin\plugins\nss-prefs.dll
(23:18:51) plugins: probing C:\My Programs\Pidgin\plugins\offlinemsg.dll
(23:18:51) plugins: probing C:\My Programs\Pidgin\plugins\perl.dll
(23:18:51) plugins: C:\My Programs\Pidgin\plugins\perl.dll is not loadable: `C:\My Programs\Pidgin\plugins\perl.dll': The specified module could not be found.
(23:18:51) plugins: probing C:\My Programs\Pidgin\plugins\pidginrc.dll
(23:18:51) plugins: probing C:\My Programs\Pidgin\plugins\psychic.dll
(23:18:51) plugins: probing C:\My Programs\Pidgin\plugins\relnot.dll
(23:18:51) plugins: probing C:\My Programs\Pidgin\plugins\sendbutton.dll
(23:18:51) plugins: probing C:\My Programs\Pidgin\plugins\spellchk.dll
(23:18:51) plugins: probing C:\My Programs\Pidgin\plugins\ssl-nss.dll
(23:18:51) plugins: probing C:\My Programs\Pidgin\plugins\ssl.dll
(23:18:51) plugins: probing C:\My Programs\Pidgin\plugins\statenotify.dll
(23:18:51) plugins: probing C:\My Programs\Pidgin\plugins\themeedit.dll
(23:18:51) plugins: probing C:\My Programs\Pidgin\plugins\ticker.dll
(23:18:51) plugins: probing C:\My Programs\Pidgin\plugins\timestamp.dll
(23:18:51) plugins: probing C:\My Programs\Pidgin\plugins\timestamp_format.dll
(23:18:51) plugins: probing C:\My Programs\Pidgin\plugins\win2ktrans.dll
(23:18:51) plugins: probing C:\My Programs\Pidgin\plugins\winprefs.dll
(23:18:51) plugins: probing C:\My Programs\Pidgin\plugins\xmppconsole.dll
(23:18:51) plugins: probing C:\My Programs\Pidgin\plugins\xmppdisco.dll
```

Not much stands out. I don't think the windows credentials thing is relevant.

There's one 404 attempting to fetch someone's profile pic, and that url does look weird, but i think it's unlikely that would result in this behavior two minutes later with several successful requests in the middle.

@EionRobb, ideas?

**Comment by IcyInsanities** [comment]
I disabled windows cred and retested, and it still repros (as expected).
As for the 404 on the profile pic, I just checked that person's profile page directly and their profile pic is broken there as well. Seems like a facebook bug on that.

Let me know if there's anything else I can test.

**Comment by dequis** [comment]
Hmm, how about removing the hangouts plugin temporarily? Wonder if its http stuff is interfering somehow. Doubt it, but who knows.

**Comment by IcyInsanities** [comment]
Tried a few more things:
- disable hangouts plugin
- full reinstall (did not wipe appdata settings) and no hangouts install
- different computer
All show the same behavior.
Does this repro for anyone else? It happens on both sending/receiving pictures (sending via phone, receiving from others).

**Comment by Malvineous** [comment]
Same problem here, no pics starting a few days ago, affects me on Windows 7 but still works on Linux (so far) - same account, logged in at the same time - pics show on Linux, not on Windows.  Will be tricky to try to get comparative debug logs but I can try if it would help.

**Comment by IcyInsanities** [comment]
Since it seems to be relevant, I've tested on win 8.1 and win 10

**Comment by monstertrimble** [comment]
Same issue here - I have Windows 10. Haven't tried it on my linux box yet.

**Comment by dequis** [comment]
Hm. Antivirus/firewall software?

**Comment by RushJet1** [comment]
I've had the same issue for 2 days now.  The facebook plugin disconnected for about 30 minutes, then would not display pictures after it reconnected.

**Comment by dequis** [comment]
@RushJet1 

>Antivirus/firewall software?

**Comment by IcyInsanities** [comment]
One of my win 8.1 computers has Windows Defenders, another has Norton. No windows update occurred during the time this started, so I'm not sure what would have changed on the windows side.

I've noticed on my phone that notifications for picture messages sometimes immediately disappear (iphone+messenger app), and that started maybe a day or so before this. I don't know how exactly it would be related, but maybe it is.

Anything that might help in figuring this out? (And thanks again for the time you've spent on this.)

**Comment by dequis** [comment]
Hmm okay I have an idea. Those attachments come over http instead of https for some reason. So let's try forcing it to https.

Pushed a thing to this branch https://github.com/dequis/purple-facebook/tree/mystery-meat-1

Test build for windows: http://dequis.org/libfacebook-20170722-c4e8920-c9b74a765767.dll

Rename to libfacebook.dll, replace the old one, and restart.

**Comment by IcyInsanities** [comment]
That fixes it! Thanks so much!

**Comment by dequis** [comment]
Neat. So yeah, server side change. The last attachment I have in my logs is from the last sunday and it had https, current ones don't have it anymore. Wonder why they did this, unencrypted http is a risk and a source of failures, but the world is so big that maybe this was the fix for someone's problem.

It doesn't look like something else is messing with the traffic, so maybe purple3's code for unencrypted http connections is busted on windows. On the bright side that means all successful connections were https!

**Comment by monstertrimble** [comment]
Windows Defender for both (work machine)

**Comment by db-bogdan** [comment]
@dequis I am still getting this error.

I have sent you the log by email.

Anything I must change or that can be done? :(

**Comment by dequis** [comment]
@db-bogdan that's not the version in https://github.com/dequis/purple-facebook/issues/347#issuecomment-317156426

I'm still hoping it will be fixed server side and I won't need to merge that, but giving it a week or so.

**Comment by db-bogdan** [comment]
That's very strange. Sorry to have bothered you, @dequis. I added it again and it does indeed work.

I do have another question, however. I am never getting any notification whenever someone directly shares a youtube video for example from their mobile device. Is there any way to at least get notified when that happens?

Thank you for your work.

**Comment by dequis** [comment]
Hm. Odd. Open a new ticket and send a debug log for that if you can catch it.

**Comment by dequis** [comment]
This appears to be fixed on the server side now.

The test build linked above is no longer needed. Those who are using that build can go back to the last release or stay with it until the next release, it's the same.
