### ISSUE TITLE
./configure: line 11964: syntax error near unexpected token `GLIB,'

### ISSUE THREAD

**Issue by smeagolthellama** [dequis/purple-facebook#351]
When I run ./configure && make && make install it says the following:
```
./configure:` line 11964: syntax error near unexpected token `GLIB,'
./configure: line 11964: `PKG_CHECK_MODULES(GLIB, glib-2.0 >= 2.28.0 gio-2.0 gobject-2.0)'

```
I have made sure that the dependencies are there, and have no idea how to fix this.

**Comment by dequis** [comment]
What distro?

Looks like you're not using the release tarball instructions. If you use that you'll need less dependencies. See https://github.com/dequis/purple-facebook/wiki/Building-on-*NIX#from-a-release-tarball

**Comment by smeagolthellama** [comment]
distro: a mess that I got from migrating from ubuntu to debian by stripping everything away except for the essentials (bash, sudo, systemd, apt) and changing /etc/apt/sources.list.

thanks for the link. seems to be working now.

**Comment by dequis** [comment]
Brutal

Well. Glad it works.
