### ISSUE TITLE
Invalid HTTP response code (400). Fixes from June don't seem to work.

### ISSUE THREAD

**Issue by FeO2** [dequis/purple-facebook#356]
Can't connect to facebook messenger. I get the above error code. Running pidgin ver. 2.12.0 on Windows 10. I've downloaded the latest plugins libson-glib-1.0.dll and libfacebook.dll. I don't believe these dlls have changed since the issue began about two weeks ago. I've been waiting hoping a fix would be posted.

In fairness to you I'm not that technical. Please feel free to be didactic. Being gentle would be nice but not required.

**Comment by dequis** [comment]
Easiest way to tell is to send me one of these https://github.com/dequis/purple-facebook/wiki/Debugging-Logs

**Comment by FeO2** [comment]
Thanks for the response. Sorry missed the email. File attached.

Maybe of note: The issue with the facebook plugin is it won't enable. I
have gchat and facebook on pidgin. I disabled the gchat. The facebook would
not enable.

Rusty

**Comment by dequis** [comment]
Don't send it to github, it drops attachments. Send it to the address in https://github.com/dequis/purple-facebook/wiki/Debugging-Logs

**Comment by FeO2** [comment]
My bad. Sent to the correct address.

**Comment by dequis** [comment]
Not seeing much there.

```
(16:23:18) plugins: probing C:\Program Files (x86)\Pidgin\plugins\libfacebook.dll
...
(16:23:19) plugins: probing C:\Program Files (x86)\Pidgin\plugins\libjson-glib-1.0.dll
(16:23:19) plugins: C:\Program Files (x86)\Pidgin\plugins\libjson-glib-1.0.dll is not usable because the 'purple_init_plugin' symbol could not be found.  Does the plugin call the PURPLE_INIT_PLUGIN() macro?
```

That `libjson-glib-1.0.dll` is in the wrong directory but the other dll doesn't fail to load so you probably have one copy of it in the correct place too. Recheck that anyway. https://github.com/dequis/purple-facebook/wiki/Installing-on-Windows

I don't see any attempts to connect using the plugin so I can't provide more information about the error. So send another log with a connection attempt if it still happens.

**Comment by dequis** [comment]
We ended up troubleshooting this one over email - oddly enough most of the logs didn't have any connection attempts either and I'm not sure how could that happen when the UI appeared to attempt a reconnect.

The solution was to do a complete clean uninstall of pidgin and reinstall:

>Based on your suggestion I decided to go a little further and completely start over. I used the Windows (10) software removal tool and uninstalled Pidgin. I restarted the PC. I noted that removal did not remove the Pidgin directory structure. I deleted the  libjson-glib-1.0.dll and the libfacebook.dll. I re-downloaded those. I started Pidgin and it worked.

¯\(°_o)/¯

Either way, solved, so closing this.
