### ISSUE TITLE
Purple facebook on Windows

### ISSUE THREAD

**Issue by johan8863** [dequis/purple-facebook#358]
After I downloaded the pulgins to th corresponding directories, my jabber account doesn´t connect anymore

**Comment by dequis** [comment]
I don't think that's related to this plugin... What error does it throw?

**Comment by EionRobb** [comment]
After I took the bus to work my motorcycle wouldn't start

**Comment by johan8863** [comment]
Ver sorry, it was a dns problem, thanks.
