### ISSUE TITLE
"Failed to read fixed header" on 0.9.5

### ISSUE THREAD

**Issue by jaymzh** [dequis/purple-facebook#361]
Debug logs to follow.

**Comment by jaymzh** [comment]
Sent

**Comment by dequis** [comment]
Huh. Haven't had to read MQTT in a long while. It's also possible the problematic packet might be outside what's logged. Fun stuff. I'll take a deeper look later

**Comment by QomariSanjaya** [comment]
Is this the same issue with "Unknown HTTP error" ? or this is another issue?
I got Unknown HTTP error today, before it was fine

**Comment by dequis** [comment]
@QomariSanjaya it's not the same. post another ticket, send debug log https://github.com/dequis/purple-facebook/wiki

**Comment by dequis** [comment]
@jaymzh hey sorry I couldn't look at this yet, is this broken on every login or just sometimes?

**Comment by jaymzh** [comment]
@dequis  just sometimes. I haven't had it in a week or so, actually.

**Comment by dequis** [comment]
This looks like it hasn't been an issue for a while so i'll blame the server

**Comment by rosshadden** [comment]
I'm getting this error again, after upgrading to the latest `master`.  I can try to bisect and figure out when it broke when I get time, though if it's on Facebook's end I wouldn't get anywhere :).  Before this, I haven't had this issue for many months.

**Comment by jaymzh** [comment]
Hey @rosshadden  Are you still experiencing this? I haven't been able to login for over 2 days now, except for a brief period last night. I'm wondering if there's anything in common between your use-case and mine...

**Comment by ipantovic** [comment]
after SSL handshake issue on 2.12 and upgrade to 2.13. and latest master I got the same "Failed to read fixed header" error. Strange enough when I removed the account and re-added ... I got my fb name populated as an alias.

**Comment by dequis** [comment]
Moving this over to #410 - i'm sure the original issue wasn't TLS 1.3 related so that goes back to its "blame the server" state.

**Comment by rosshadden** [comment]
@jaymzh Yes I am, and funny enough it's the same thing for me. I haven't been able to login for over two days now, except for a brief period last night. So yeah, seems very closely related!

I know this issue is closed now, just wanted to respond directly.
