### ISSUE TITLE
Unknown HTTP error

### ISSUE THREAD

**Issue by QomariSanjaya** [dequis/purple-facebook#362]
I got this error since yesterday. Suddenly it stop working. Tried to update to the latest version, it was work stable for a while, but after about 12 hours i got the same error again. I dont know what is causing this, my system, server connection (I have checked it and its works good), or Facebook already blocked this lib, My system using debian stretch and openfire 4.1.4

**Comment by dequis** [comment]
"and openfire 4.1.4" So, is this spectrum and not pidgin? If so, try with pidgin just once.

And https://github.com/dequis/purple-facebook/wiki/Debugging-Logs

**Comment by Ruplahlava** [comment]
Had the same error, but for me was enough to update to latest

**Comment by alanapants** [comment]
Having this error still even when updated to the latest version of the plugin. Using Windows 10 and Pidgin 2.12.0

**Comment by dequis** [comment]
Not seeing any debug logs from anyone here. I can't help without that.

https://github.com/dequis/purple-facebook/wiki/Debugging-Logs

**Comment by dequis** [comment]
@alanapants Got debug log. You're using an old version of this plugin, 0.9.3, because there's another copy of the dll in the plugins directory:

```
(12:13:41) plugins: probing C:\Program Files (x86)\Pidgin\plugins\libfacebook (1).dll
(12:13:41) plugins: probing C:\Program Files (x86)\Pidgin\plugins\libfacebook.dll
```

Removing the `(1)` copy is probably enough to fix this, assuming libfacebook.dll is a newly downloaded 0.9.5

**Comment by alanapants** [comment]
Hghh, I can't believe the answer was just... me being a big dumdum. It works now that it isn't trying to use both an old (the copy) and a new (the regular) version. Thanks for the help!

**Comment by gtTracy** [comment]
Running into the same error (Unknown HTTP error) when connecting to Facebook.  Problem started last night, after running successfully for more than a week (system was reinstalled completely about 2 weeks ago).

Ubuntu 17.04 (with all updates, but skipping the version upgrade to 17.10)
Pidgin 2.12.0
Purple-Facebook (libfacebook.so) Wed 04 Oct 2017 12∶12∶45 AM EDT (I didn't see a version number)

Tried uninstalling purple-facebook and reinstalling. Same issue.

Small log snippet:

(09:24:16) http: Timeout reached for request 0x55eb72425e30
(09:24:16) http: Cancelling connection 0x55eb72425e30...
(09:24:16) http: destroying socket: 0x55eb71b730e0
(09:24:16) http: Request 0x55eb72425e30 performed without success.
(09:24:16) facebook: HTTP Response (0x55eb72425e30):
(09:24:16) facebook:   Response Error: Unknown HTTP error (0)
(09:24:16) connection: Connection error on 0x55eb723d75a0 (reason: 0 description: Unknown HTTP error)

I have a full copy of the log, if you would like to see it. 

Open to any ideas or suggestions....

**Comment by gtTracy** [comment]
And, after two days of not working, suddenly it is working again. No idea why. I guess something was out of whack somewhere, but...

**Comment by dequis** [comment]
Closing because OP hasn't replied and everyone else got it sorted.

**Comment by truenicoco** [comment]
FWIW, I have the same error since 4am this morning using spectrum2.

It occured before and self-resolved but I couldn't figure out how or why. I guess it's something on the facebook side.

```
tail /var/log/spectrum2/XXXXXXXXXXXXXX/backends/backend-1.log -n 20
31913: 2018-06-15 08:29:07,061 INFO  libpurple: dnsquery:Performing DNS lookup for graph.facebook.com
31913: 2018-06-15 08:29:07,061 INFO  libpurple: dns:Successfully sent DNS request to child 31935
31913: 2018-06-15 08:29:07,071 INFO  libpurple: dns:Got response for 'graph.facebook.com'
31913: 2018-06-15 08:29:07,071 INFO  libpurple: dnsquery:IP resolved for graph.facebook.com
31913: 2018-06-15 08:29:07,071 INFO  libpurple: proxy:Attempting connection to 185.60.217.20
31913: 2018-06-15 08:29:07,071 INFO  libpurple: proxy:Connecting to graph.facebook.com:443 with no proxy
31913: 2018-06-15 08:29:07,071 INFO  libpurple: proxy:Connection in progress
31913: 2018-06-15 08:29:10,338 INFO  libpurple: util:Writing file accounts.xml to directory /var/lib/spectrum2/XXXXXXXXXXXXXX
31913: 2018-06-15 08:29:10,338 INFO  libpurple: util:Writing file /var/lib/spectrum2/XXXXXXXXXXXXXX/accounts.xml
31913: 2018-06-15 08:29:37,338 INFO  libpurple: http:Timeout reached for request 0x5603175c1680
31913: 2018-06-15 08:29:37,338 INFO  libpurple: http:Request 0x5603175c1680 performed without success.
31913: 2018-06-15 08:29:37,338 INFO  libpurple: connection:Connection error on 0x560316fd43a0 (reason: 0 description: Unknown HTTP error)
31913: 2018-06-15 08:29:37,339 INFO  libpurple: account:Disconnecting account XXXXXXXXXXXXXX (0x560317804840)
31913: 2018-06-15 08:29:37,339 INFO  libpurple: connection:Disconnecting connection 0x560316fd43a0
31913: 2018-06-15 08:29:37,339 INFO  libpurple: connection:Destroying connection 0x560316fd43a0


$ apt-cache policy purple-facebook
purple-facebook:
  Installed: 20180323~ef6ae47~9ff9acf9fa14~145
  Candidate: 20180323~ef6ae47~9ff9acf9fa14~145
  Version table:
 *** 20180323~ef6ae47~9ff9acf9fa14~145 500
        500 http://download.opensuse.org/repositories/home:/jgeboski/Debian_9.0 ./ Packages
        100 /var/lib/dpkg/status

$ apt-cache policy spectrum2
spectrum2:
  Installed: 1:2.0.7-1
  Candidate: 1:2.0.7-1
  Version table:
 *** 1:2.0.7-1 500
        500 http://packages.spectrum.im/spectrum2 stretch/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by truenicoco** [comment]
It seemed that this was DNS problem on my server (thanks @vitalister). I changed `/etc/resolv,conf` to use `1.1.1.1`, restarted the spectrum transport with `spectrum2_manager facebook.XXXXXXX restart`, and finally restarted Gajim, now I'm back online on facebook. I hope this might help others.
