### ISSUE TITLE
Facebook: Insert image and link items are disabled

### ISSUE THREAD

**Issue by raavimohindar** [dequis/purple-facebook#363]
I do not know whether it is specific to purple-facebook or pidgin from Debian Stretch.

I can't send either an url nor an image in chat. Any help!!!

**Comment by dequis** [comment]
If you want to post an url, just ctrl-c and ctrl-v?

**Comment by marsjaninzmarsa** [comment]
Linked text is just not supported by Messenger protocol, and sending images is topic of #133.
