### ISSUE TITLE
Failed to read thrift: api.c:1679 fb_api_cb_publish_pt: assertion 'FALSE' failed

### ISSUE THREAD

**Issue by RushJet1** [dequis/purple-facebook#364]
Within the last few minutes my Facebook account refuses to connect with the message

"Failed to read thrift: api.c:1679 fb_api_cb_publish_pt: assertion 'FALSE' failed"

Tried restarting Pidgin, but to no avail. Internet here is still working fine, I can access messenger on my phone or browser.  No firewall stuff has changed, etc.

**Comment by RushJet1** [comment]
Nevermind, this is in the latest version. It's odd that I was using an old version with no problems until now if it's been an issue for half a month...

**Comment by affinityv** [comment]
Hi,

On 13/09/17 05:55, RushJet1 wrote:
> Nevermind, this is in the latest version. It's odd that I was using an
> old version with no problems until now if it's been an issue for half a
> month...

I've not seen any problems....

Using Pidgin on Linux Mint 18.2

Pidgin 2.10.12 (libpurple 2.10.12)

I have recently built the plugin without any troubles as well; the
original SuSe build source.list file stopped working (resource gone).

Kind Regards
AndrewM

**Comment by dooglus** [comment]
I was able to use Facebook chat in pidgin yesterday, and it broke overnight for me.

I was on version `v0.9.4-c9b74a765767`. Rebuilding for v0.9.5 fixed it for me.

I did this to rebuild and reinstall:

    $ cd ~/Programs/purple-facebook/
    $ git fetch origin
    $ git checkout v0.9.5-9ff9acf9fa14      # or whatever version
    $ ./autogen.sh
    $ make
    $ mkdir -p ~/.purple/plugins            # it probably already exists
    $ cp pidgin/libpurple/protocols/facebook/.libs/libfacebook.so ~/.purple/plugins

**Comment by madmangunradio** [comment]
I received the same error.  Following dooglus advice, plugin is now working.

**Comment by semakuln** [comment]
Hello, 
New to this, can someone break down in simple man's language on how to follow dooglus advice.  Step by step process would be nice, or even a link to instructions would be great.  Thanks

**Comment by dooglus** [comment]
@semakuln Did you build and install purple-facebook yourself? There are instructions for how to do that [in the wiki](https://github.com/dequis/purple-facebook/wiki), but I didn't see instructions for how to upgrade an existing installation. I didn't want to redownload and rebuild everything from scratch so I played around and posted a list of the commands that worked for me.

It is a step-by-step list of the commands I ran. I'm using Linux. I expect it would be different on other systems.

**Comment by madmangunradio** [comment]
Quick and dirty instructions.
sudo apt install git
mkdir ~/Programs
cd ~/Programs
git clone https://github.com/dequis/purple-facebook.git
cd purple-facebook
./update.sh
**Now follow dooglus instructions.**

**Comment by dequis** [comment]
I'll reopen this and mark it as resolved so people stop opening new tickets.

**Comment by joshuasb** [comment]
Is there an updated pre-compiled windows dll to fix this issue yet?

**Comment by cyberknight1062** [comment]
hi, I got a message "Failed to read thrift: api.c:1679 fb_api_cb_publish_pt: assertion 'FALSE' failed"

Internet is still working fine, I can access messenger on my phone or browser. No firewall stuff has changed, etc.

BUILD INFORMATION:
Pidgin 2.12.0 (libpurple 2.12.0)
unknown

Build Information
  Arguments to ./configure:   '--build=i686-linux-gnu' '--prefix=/usr' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=${prefix}/lib/pidgin' '--disable-maintainer-mode' '--disable-dependency-tracking' '--disable-silent-rules' '--disable-gevolution' '--enable-cap' '--with-system-ssl-certs=/etc/ssl/certs' '--enable-perl' '--with-zephyr=/usr' '--enable-dbus' '--enable-gnutls=no' '--enable-nss=yes' '--enable-cyrus-sasl' '--enable-vv' '--enable-tcl' '--enable-tk' '--enable-unity' '--with-tclconfig=/usr/lib/i386-linux-gnu' '--with-dynamic-prpls=bonjour,gg,irc,jabber,novell,oscar,sametime,simple,zephyr' '--enable-nm' 'build_alias=i686-linux-gnu' 'CFLAGS=-g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2'
  Print debugging messages: No
  Plugins: Enabled
  SSL: SSL support is present.

  Library Support
    Cyrus SASL: Enabled
    D-Bus: Enabled
    Evolution Addressbook: Disabled
    Gadu-Gadu library (libgadu): External
    GtkSpell: Enabled
    GnuTLS: Disabled
    GStreamer: Enabled
    Mono: Disabled
    NetworkManager: Enabled
    Network Security Services (NSS): Enabled
    Perl: Enabled
    Tcl: Enabled
    Tk: Enabled
    UTF-8 DNS (IDN): Enabled
    Voice and Video: Enabled
    X Session Management: Enabled
    XScreenSaver: Enabled
    Zephyr library (libzephyr): External
    Zephyr uses Kerberos: No

**Comment by kikendo** [comment]
How was this solved? I still have this issue on Windows.

**Comment by joshuasb** [comment]
Your plug-in file is out of date. Exit Pidgin. Go to the instructions on how to install this for Windows. Download the dll for the plug-in and install it, overwriting the file you already have in your Pidgin plug-ins folder. Launch Pidgin. Problem solved.

**Comment by kikendo** [comment]
Cool, thanks, I figured it out, but it wasn't clearly described here, teh OP closed the thread without much explanation (and this is the first hit of the error to come up on Google).

Updating the DLL did do the trick! The version that works is **20170916~af391dc~9ff9acf9fa14~135**

**Comment by saleslogistix** [comment]
I may be misreading this thread, but my understanding is that downloading the latest dll for Windows "solves" this issue.  
On my system (Pidgin 2.12.0 on Win7 64 bit), the new dll is never able to log in to Facebook (but it also doesn't throw an error item up).

**Comment by joshuasb** [comment]
I noticed that it took some time before the login completed. And you have to replace the file while Pidgin is NOT running.

**Comment by dequis** [comment]
Closing this (which was only open for visibility)
