### ISSUE TITLE
Failed to load libfacebook.so with pidgin3

### ISSUE THREAD

**Issue by cicciofuser** [dequis/purple-facebook#365]
Hi, 

I'm trying to use plugin purple-facebook with pidgin3 . I got this error and plugin isn't loading :

(Pidgin:13930): GPlugin-WARNING **: failed to query '/home/cg12005/.purple/plugins/libfacebook.so' with loader 'GPluginNativeLoader': Failed to open plugin '/home/cg12005/.purple/plugins/libfacebook.so': libpurple.so.0: cannot open shared object file: No such file or directory

The content of my /usr/lib/libpurple* is :

lrwxrwxrwx 1 root root      19 ott 16  2016 libpurple.so -> libpurple.so.20.0.0
lrwxrwxrwx 1 root root      26 ott 16  2016 libpurple-client.so -> libpurple-client.so.20.0.0
lrwxrwxrwx 1 root root      19 ott 16  2016 libpurple.so.20 -> libpurple.so.20.0.0
lrwxrwxrwx 1 root root      26 ott 16  2016 libpurple-client.so.20 -> libpurple-client.so.20.0.0
-rw-r--r-- 1 root root 1505384 ott 16  2016 libpurple.so.20.0.0
-rw-r--r-- 1 root root  198472 ott 16  2016 libpurple-client.so.20.0.0

**Comment by dequis** [comment]
The plugin in this repository is for purple2. It backports the code of the plugin from purple3. If you have purple3, you already have this plugin.

**Comment by cicciofuser** [comment]
Oh ok sorry, thanks a lot.
