### ISSUE TITLE
Documentation issue for FB Windows Install

### ISSUE THREAD

**Issue by jeremymeyers** [dequis/purple-facebook#368]
This is totally a small thing but wasn't sure where else to put it.

on [https://github.com/dequis/purple-facebook/wiki/Installing-on-Windows](https://github.com/dequis/purple-facebook/wiki/Installing-on-Windows) , you should include that on 64-bit windows installs, the directory will be c:\program files (x86)\pidgin\* rather than c:\program files\pidgin

**Comment by dequis** [comment]
It says exactly that

>Program Files will be Program Files (x86) on 64-bit Windows
