### ISSUE TITLE
Utilize Travis-CI for posting releases to GitHub's Releases page

### ISSUE THREAD

**Issue by aph3rson** [dequis/purple-facebook#370]
https://victorhurdugaci.com/github-releases-travis

This would be handy for users who look at Releases (or use things like [sibbell](https://about.sibbell.com/)).

**Comment by dequis** [comment]
This is incompatible with the way this project makes releases.

**Comment by aph3rson** [comment]
Is there any particular reason why it's incompatible?

**Comment by affinityv** [comment]
On 19/09/17 01:59, Ian Williams wrote:
> Is there any particular reason why it's incompatible?

I know I wouldn't be trusting a third party to have full access to my
github accouont!

It is incompatible with basic security as far as I am concerned.

Kind Regards
AndrewM

**Comment by aph3rson** [comment]
> It is incompatible with basic security as far as I am concerned.

Travis-CI is one of the biggest continuous integration platforms used on Github, and is totally free for public projects. It integrates just like a normal application, and you can tailor its access to particular repositories - it doesn't have "full access," it's simply a tool to build code as it's released.

To be frank, I don't see any technical limitations for why Travis (or another CI bot) wouldn't work.

**Comment by marsjaninzmarsa** [comment]
@affinityv:
> I know I wouldn't be trusting a third party to have full access to my
github accouont!

Learn about OAuth scopes. We're not in 2003 anymore, fortunately. :smiley:

**Comment by affinityv** [comment]
Hi,

On 23/09/17 08:32, Kuba Niewiarowski wrote:
> @affinityv <https://github.com/affinityv>:
> 
>     I know I wouldn't be trusting a third party to have full access to my
>     github accouont!
> 
> Learn about OAuth scopes. We're not in 2003 anymore, fortunately. 😃

Yes, well, I don't trust OAuth either.  Never link accounts with other
services, OAuth does that; don't use LinkedIn either -- they track every
skill, every job, every employer, every training organisation for any
skill... and they are now owned by M$.  LinnkedIn and by definition
Microsoft are the wet dreams of over surveillance, 1984 (George Orwell)
was a kindergarten picnic by comparison.

If you had an account that was singly for a project, then it might be
slightly less bad -- but you are still giving away the keys to the kingdom.

Kind Regards
AndrewM

**Comment by marsjaninzmarsa** [comment]
> LinnkedIn and by definition
Microsoft are the wet dreams of over surveillance, 1984 (George Orwell)
was a kindergarten picnic by comparison.
>
> If you had an account that was singly for a project, then it might be
slightly less bad -- but you are still giving away the keys to the kingdom.

Are we still under issue with implementation of Facebook Messenger protocol? 😂
Either way, EOT.
