### ISSUE TITLE
Peer cert did NOT match cached - I can't connect to my facebook account.

### ISSUE THREAD

**Issue by pulidovpe** [dequis/purple-facebook#373]
I use Debian 9. And, I just install the last update: 
- purple-facebook_20170916-af391dc-9ff9acf9fa14-135_amd64
- purple-facebook-dbgsym_20170916-af391dc-9ff9acf9fa14-135_amd64)

But now, I can't connect to my facebook account using pidgin. I got repeatedly certificate messages.
I got these messages on the debug window:
***
(15:56:31) certificate/x509/tls_cached: Starting verify for fb-s-a-a.akamaihd.net
(15:56:31) certificate/x509/tls_cached: Checking for cached cert...
(15:56:31) certificate/x509/tls_cached: ...Found cached cert
(15:56:31) nss/x509: Loading certificate from /home/developer/.purple/certificates/x509/tls_peers/fb-s-a-a.akamaihd.net
(15:56:31) certificate/x509/tls_cached: Peer cert did NOT match cached
(15:56:31) nss: CERT 0. CN=a248.e.akamai.net,O="Akamai Technologies, Inc.",L=Cambridge,ST=Massachusetts,C=US :
(15:56:31) nss:   ERROR -8179: SEC_ERROR_UNKNOWN_ISSUER

*** and these others

(15:54:56) dnsquery: Error al resolver fb-s-b-a.akamaihd.net: 
Nombre o servicio desconocido
(15:54:56) proxy: Connection attempt failed: Error al resolver fb-s-b-a.akamaihd.net: 
Nombre o servicio desconocido
(15:54:56) socket: invalid state: 3 (should be: 2)

*** and so much more...

Any idea???

**Comment by miguelzf** [comment]
Can confirm, I also get similar errors after upgrading to debian 9

**Comment by pulidovpe** [comment]
It's already solved! With the new release! Thanks!

- purple-facebook_20171004
- purple-facebook-dbgsym_20171004

**Comment by brianjmurrell** [comment]
I still get this error with 0.9.6 which was released 13 Jan 2019 so it seems it should include this fix, as it's almost 2 years newer than the supposed fixed release of 20171004.

Can we please have this issue reopened?
