### ISSUE TITLE
"Failed to get sync_sequence_id" on existing Facebook account

### ISSUE THREAD

**Issue by KimHono** [dequis/purple-facebook#377]
Hi,
I've got this error on a fresh installation of the plugin.
Environment : plugin 20170916~af391dc~9ff9acf9fa14~135
Pidgin 2.11.0
LMDE 2 (Linux Mint Debian Edition)

**Comment by dequis** [comment]
https://github.com/dequis/purple-facebook/wiki/Debugging-Logs

**Comment by KimHono** [comment]
Well, there is no error with a new Facebook account.
I think there is somewhere a FB setting to damn...
