### ISSUE TITLE
Buddy Pounce?

### ISSUE THREAD

**Issue by Aasemoon** [dequis/purple-facebook#378]
Hi there,

First, sorry if this is not really an issue... I haven't used Pidgin in a while and I'm a bit clueless.

When I set a buddy pounce to get notified when facebook contacts prepare to send me a message [start typing], it seems like I only get alerted when the conversation window with the specific contact is already open. To me this seems to defeat the purpose? 

So is there a way to fix this / get notified without the conversation window being open?

Thanks!

**Comment by EionRobb** [comment]
You could use the Psychic Plugin to make the conversation open and the buddy pounce to work

**Comment by Aasemoon** [comment]
@EionRobb Thanks a lot for the tip, now could you please tell me where to get my hands on this plugin? =) It doesn't seem to be listed....

**Comment by Aasemoon** [comment]
Oh wait nevermind, it's there.... didn't see it. =) Thank you.
