### ISSUE TITLE
[FEATURE] add allias and Informations.

### ISSUE THREAD

**Issue by jeros-xyz** [dequis/purple-facebook#379]
In the previous plugin, we could retrieve the contact information and automatically change the contact's name with its facebook alias. Currently we only see the ID in the contact list

Ubuntu 16.04
Pidgin 2.12.0
version 0.9.5-9ff9acf9fa14

**Comment by marsjaninzmarsa** [comment]
Optable synchronization of Pidgin buddy name and Messenger nickname would be nice. And doable.

**Comment by dequis** [comment]
>with its facebook alias

What alias?

>Currently we only see the ID in the contact list

What ID?

**Comment by jeros-xyz** [comment]
Hi, thanks for the replies.

What I call the facebook alias is what appears in the <title> tag of a browser tab when visiting a contact's profile

When I'm in the desktop view of facebook.com, I see the contact list. When I mouse over a contact, I can see the URL(at the bottom left) with a link similar to "https://www.facebook.com/posts/t/xxxxxxxxxx". The x is the facebook id

UPDATE : I don't know when or how but now, my contacts nickname is the facebook alias. 
Sorry for the inconvenience and thanks again for your work ;)
