### ISSUE TITLE
Connection error: Null value for $.viewer.message_threads.unread_count

### ISSUE THREAD

**Issue by ajarov** [dequis/purple-facebook#394]
Can't connect to Facebook anymore, I get the error of the title.
Started happening today.

Windows 7 64-bit
Pidgin 2.12.0 (libpurple 2.12.0)
prpl-facebook 20171004~4aa77de~9ff9acf9fa14~137

**Comment by dequis** [comment]
https://github.com/dequis/purple-facebook/wiki/Debugging-Logs

**Comment by ajarov** [comment]
Debug log sent via e-mail, thanks.

**Comment by ajarov** [comment]
It seems to be solved, I can connect now.

**Comment by dequis** [comment]
Duplicate of #393
