### ISSUE TITLE
Error with connecting

### ISSUE THREAD

**Issue by Johnnyreyman** [dequis/purple-facebook#398]
![screenshot from 2017-12-22 22-52-39](https://user-images.githubusercontent.com/31798114/34317037-10214bb0-e76b-11e7-932f-25f38f0a7b67.png)
Can anyone tell me what is going on?

**Comment by dequis** [comment]
https://github.com/dequis/purple-facebook/wiki/Debugging-Logs

**Comment by werstatyw** [comment]
Hello, have a connection issiue, will provide log now.

**Comment by dequis** [comment]
I don't think I got anything from this ticket, but either way this is most likely an outdated plugin.
