### ISSUE TITLE
token issue?

### ISSUE THREAD

**Issue by jaymzh** [dequis/purple-facebook#399]
I have a problem I've been trying to gather debug logs for a long time, but is very hard to do so for... and i have a theory.

Does purple-facebook hold a token/cookie across disconnect/reconnect that it does *not* hold across app restarts?

I keep Pidgin open always, but at the end of the day "offline" (disconnects from all accounts) and go back online in the morning. I do this to keep my pidgin windows/tabs as they are. After some period of time, usually weeks, Facebook fails to connect. It'll go online for a second and then disconnect with "failed to parse thread information." Repeated reconnects always fail. However, restarting the app always fixes it.

Therefore it's VERY hard to get debug logs - that requires restarting the app which fixes it.

It occurred to me today this behavior would be caused by some stored token/cookie retrieved and reused across disconnect/reconnect that is regenerated/refreshed on fresh startup.

I know that's not the most useful bug report... I hope it's enough to go on though.

**Comment by dequis** [comment]
Well, uh, sounds like gating debug behind an environment variable only wasn't the smartest of decisions. You could set those env vars system-wide and get the equivalent in a more on-demand way from the help menu -> debug window.

**Comment by jaymzh** [comment]
Oh, neat. OK, I'll try that.
