### ISSUE TITLE
Adium plugin

### ISSUE THREAD

**Issue by pasnox** [dequis/purple-facebook#406]
Hi,

Any chance to see an Adium plugin for this protocol ?

Thanks,

**Comment by dequis** [comment]
Not from me, I don't have a mac and the process of wrapping purple plugins for adium is more complicated than it should be.

See also #95, #202, #275

**Comment by EionRobb** [comment]
Maybe @tripplet would be interested (he's done Adium plugins for other plugins too https://github.com/tripplet?utf8=✓&tab=repositories&q=adium&type=&language= )

**Comment by tripplet** [comment]
I don't want to make any promises, I'll look into it.
