### ISSUE TITLE
Ubuntu 17.10 Facebook is not a protocol option

### ISSUE THREAD

**Issue by mathiesonsterling** [dequis/purple-facebook#407]
Installed via instrucions, according to apt-get it's there . . .. .

>
    sudo apt-get install bitlbee-facebook
    Reading package lists... Done   
    Building dependency tree       
    Reading state information... Done
    bitlbee-facebook is already the newest version (20171017~553593d~315).   
    The following package was automatically installed and is no longer required:
     libxss1:i386
    Use 'sudo apt autoremove' to remove it.
    0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
>

Restart Pidgin, go to add account, and no Facebook (or Facebook XMPP) option.  Pidgin is version 2.12.0

![screenshot from 2018-03-12 14-20-26](https://user-images.githubusercontent.com/3457836/37285835-9592a504-2600-11e8-9bab-c9a98ea8e3ec.png)

**Comment by dequis** [comment]
That's bitlbee-facebook, not purple-facebook

**Comment by dequis** [comment]
Did you get it working?

**Comment by dequis** [comment]
Reopen if you still have issues.
