### ISSUE TITLE
"Failed to read fixed header" due to TLS 1.3 (march 2018 + january 2019)

### ISSUE THREAD

**Issue by dequis** [dequis/purple-facebook#410]
This was brought up by @rosshadden / @jaymzh / @ipantovic in https://github.com/dequis/purple-facebook/issues/361#issuecomment-373971853 and @mandree in https://github.com/dequis/purple-facebook/issues/403#issuecomment-375260640 - I'm opening a new ticket for visibility/clarity.

### tl;dr

Update to libpurple 2.13.0, or, if that's not possible, use the NSS preferences plugin (tools menu -> plugins) to set the max version to TLS 1.2.

Do not play with the other checkboxes in the NSS preferences plugin.

### Causes

The above is my current recommendation - play it safe and avoid this bug, TLS 1.3 is too young for now - but this bug is about the case where TLS 1.3 itself is enabled, it works, but you get disconnected with "Failed to read fixed header" after sending MQTT CONNECT (the first hexdump in the debug logs, which says `MQTToT`).

I imagine three possible causes for this:

* Using libpurple 2.12.0 or older and using NSS preferences to tick all the checkboxes of ciphers required for TLS 1.3 instead of just disabling it
* Using libpurple 2.13.0 or newer and using NSS preferences to enable TLS 1.3
* Future versions of NSS may change the defaults to enable TLS 1.3. That's why this bug is worth fixing.

If anyone with had this error and doesn't fit in these please leave a comment here.

Also, all of these cases require linux, because the version of NSS shipped with pidgin doesn't have TLS 1.3 support.

### Previous issues

Pidgin/libpurple 2.12.0 and earlier had a bug in which (for historical reasons) they force-enable the latest TLS version and disable ciphers they don't know about, making it impossible to connect to servers that enable TLS 1.3. That issue fixed in libpurple 2.13.0. The result of that:

* #404 (2018-01-30) is the facebook CDN deploying TLS 1.3 - results in images not being visible
* #408 (2018-03-16) is deploying TLS 1.3 in the mqtt server - results in SSL handshake error

This issue was initially reported arond the same date.

### The actual bug

This is when you avoid the SSL Handshake Error and trip right after. As @mandree points out in https://github.com/dequis/purple-facebook/issues/403#issuecomment-375262198 it's just an EAGAIN.

The old code made the assumption that the first call to the read callback would also include at least two bytes to read, and this seems to be true with TLS 1.2. I guess something changed about TLS 1.3 that gets you calls with nothing to read.

ef6ae47b8bf971d3f2803b1552b7debc59429dc1 fixes that

So, if you *really* want, you can enable TLS 1.3 if you use libpurple 2.13.0 and upgrade to this commit. At least until we find the next issue.

**Comment by jaymzh** [comment]
You are my hero.

**Comment by dequis** [comment]
Credit to @mandree really, I didn't even think this code could be failing to handle EAGAIN

**Comment by EionRobb** [comment]
I wonder if that EAGAIN thing is why I could get the FB plugin to work with the win32-ssl plugin.  I might try that again too.

**Comment by rosshadden** [comment]
@dequis Setting max TLS to 1.2 did bypass the issue for me, however it's worth noting I actually have libpurple 2.13.0-1 installed, which is the latest. Oh well.

**Comment by jaymzh** [comment]
I can confirm that with this patch and libpurple 2.13, the problem is fixed.

I can also confirm that setting max to TLS 1.2 works around it.

Thanks so much @mandree and @dequis !

**Comment by rosshadden** [comment]
Oh my bad, I didn't update this plugin. I'll try it tomorrow.

**Comment by mandree** [comment]
@dequis - Fedora 27 Workstation (amd64), ef6ae47 and NSS limited to TLS 1.2 (without I get sporadic errors and need to reconnect), fixes things for me (with libpurple 2.12.0/pidgin 2.12.0-3.fc27). Thank you!

**Comment by rosshadden** [comment]
After updating the plugin, it works with TLS 1.3, and as I had already confirmed the workaround of using TLS 1.2 had worked before doing so. Thanks!

**Comment by Zombie-Ryushu** [comment]
I still get this error even after updating the plugin with  Spectrum2.

**Comment by shlomif** [comment]
@Zombie-Ryushu : everyone: note that I got this bug again and was able to fix it by deleting ssl-gnutls.so.

**Comment by petermolnar** [comment]
> For me downgrade to GnuTLS 3.5.x fixes the issue.

May I ask how did you manage that? If I try to downgrade libgnutls30 on debian (unstable) it wants to wreak havoc and remove nearly all packages on my system.

**Comment by dequis** [comment]
Yeah so now gnutls enabled TLS 1.3 but the issue is essentially the same. I applied the same fix over at bitlbee-facebook, which primarily uses gnutls, so if you just build the master branch it should work for you.

**Comment by dequis** [comment]
0.9.6 is out with the patch that fixes our side of issues, mostly relevant again for gnutls people, but for nss people libpurple 2.13.0 or tinkering with nss preferences is still required. I wrote a bit more here https://github.com/dequis/purple-facebook/releases/tag/v0.9.6

**Comment by josx** [comment]
A few days ago my pidgin started to give this error (on faceboook). I have latest purple-facebook source code compiled and libpurple 2.13.x
Any clue to solve it?

**Comment by dequis** [comment]
Then it's something else. Please open another issue.

Note that the error is roughly equivalent to "connection reset by peer", and anything can cause the connection to be abruptly closed, TLS is just one of many possible reasons for it.
