### ISSUE TITLE
Show your Group Chats into a separate caregory by default

### ISSUE THREAD

**Issue by mayrinck** [dequis/purple-facebook#412]
Could you add support for this? (as said on the title)

I have some groups here and would be nice to see them directly on pidgin buddy list, not just when someone send a message on the group... 

I know that is still possible to add them manually and you can query to find group chats you are part of, but the query don't show all chats you have, making it a bit useless...

**Comment by dequis** [comment]
I'd rather not mess with the buddy list. You can do it yourself:

Buddy list window -> buddies menu -> join a chat -> room list -> add chat

![screenshot](https://user-images.githubusercontent.com/94108/38002005-4b482840-3206-11e8-90c3-bf6377b13451.png)
