### ISSUE TITLE
Invalid username or email address (400)

### ISSUE THREAD

**Issue by Vict0rC** [dequis/purple-facebook#417]
Hello,
Since yesterday I can not connect to facebook with your plugin. Tryied everything. Even on another computer, different profile and pidgin installation.
In browser, facebook account it is working, in pidgin not ;-(
Any idea?

Using:
Facebook
	Author: (null)
	Version: 20180323~ef6ae47~9ff9acf9fa14~145
	Website: https://github.com/dequis/purple-facebook
	ID String: prpl-facebook
	Loadable: Yes
	Loaded: Yes

Thanx lot.
VicC

**Comment by dequis** [comment]
Oh huh sorry missed this. Is this still an issue? This error is always exactly what it says on the tin. A username that works for facebook.com should do.
