### ISSUE TITLE
Problem compiling

### ISSUE THREAD

**Issue by revan9112** [dequis/purple-facebook#421]
**Hi community, i just install Ubuntu 18.04 i386 on my old computer, an Acer Aspire One ZG5 from 2008. When I prepare to compile version "purple-facebook-0.9.5-9ff9acf9fa14" with command "./configure" I get the following error: "No package 'json-glib-1.0' found"** 

**I leave here the complete log of the order "./configure"**

./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking build system type... i686-pc-linux-gnu
checking host system type... i686-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/i686-linux-gnu-ld
checking if the linker (/usr/bin/i686-linux-gnu-ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert i686-pc-linux-gnu file names to i686-pc-linux-gnu format... func_convert_file_noop
checking how to convert i686-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/i686-linux-gnu-ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/i686-linux-gnu-ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking whether make supports nested variables... (cached) yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for glib-2.0 >= 2.28.0 gio-2.0 gobject-2.0... yes
checking for json-glib-1.0 >= 0.14.0... no
configure: error: Package requirements (json-glib-1.0 >= 0.14.0) were not met:

No package 'json-glib-1.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables JSON_CFLAGS
and JSON_LIBS to avoid the need to call pkg-config.

**And here I leave my list of packages that contain the string "json"**

ii  json-glib-tools                       1.4.2-3                             i386         GLib JSON manipulation library (tools)
ii  libfastjson4:i386                     0.99.8-2                            i386         fast json library for C
ii  libjson-c3:i386                       0.12.1-1.3                          i386         JSON manipulation library - shared library
ii  libjson-glib-1.0-0:i386               1.4.2-3                             i386         GLib JSON manipulation library
ii  libjson-glib-1.0-common               1.4.2-3                             all          GLib JSON manipulation library (common files)
ii  libunity-scopes-json-def-desktop      7.1.4+18.04.20180209.1-0ubuntu2     all          binding to get places into the launcher - desktop def file
ii  php7.2-json                           7.2.5-0ubuntu0.18.04.1              i386         JSON module for PHP
ii  python-simplejson                     3.13.2-1                            i386         simple, fast, extensible JSON encoder/decoder for Python 2.x

**Any possible fix for this issue??**

**Comment by dequis** [comment]
Install `libjson-glib-dev`

From https://github.com/dequis/purple-facebook/wiki/Building-on-*NIX you need:

* build-essential
* libglib2.0-dev
* libjson-glib-dev
* libpurple-dev
