### ISSUE TITLE
compilation issues

### ISSUE THREAD

**Issue by mattdawolf** [dequis/purple-facebook#423]
I am having issues compiling this. Not sure what could be wrong.

root@mattdawolfsden:/opt/purple-facebook# make
Making all in pidgin/libpurple/protocols/facebook
make[1]: Entering directory '/opt/purple-facebook/pidgin/libpurple/protocols/facebook'
  CC       libfacebook_la-marshal.lo
marshal.c:248:1: error: redefinition of ‘fb_marshal_VOID__INT64’
 fb_marshal_VOID__INT64 (GClosure     *closure,
 ^~~~~~~~~~~~~~~~~~~~~~
marshal.c:53:1: note: previous definition of ‘fb_marshal_VOID__INT64’ was here
 fb_marshal_VOID__INT64 (GClosure     *closure,
 ^~~~~~~~~~~~~~~~~~~~~~
marshal.c:283:1: error: redefinition of ‘fb_marshal_VOID__POINTER_BOOLEAN’
 fb_marshal_VOID__POINTER_BOOLEAN (GClosure     *closure,
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
marshal.c:88:1: note: previous definition of ‘fb_marshal_VOID__POINTER_BOOLEAN’ was here
 fb_marshal_VOID__POINTER_BOOLEAN (GClosure     *closure,
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
marshal.c:320:1: error: redefinition of ‘fb_marshal_VOID__STRING_BOXED’
 fb_marshal_VOID__STRING_BOXED (GClosure     *closure,
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
marshal.c:125:1: note: previous definition of ‘fb_marshal_VOID__STRING_BOXED’ was here
 fb_marshal_VOID__STRING_BOXED (GClosure     *closure,
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
marshal.c:357:1: error: redefinition of ‘fb_marshal_VOID__POINTER_POINTER’
 fb_marshal_VOID__POINTER_POINTER (GClosure     *closure,
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
marshal.c:162:1: note: previous definition of ‘fb_marshal_VOID__POINTER_POINTER’ was here
 fb_marshal_VOID__POINTER_POINTER (GClosure     *closure,
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Makefile:543: recipe for target 'libfacebook_la-marshal.lo' failed
make[1]: *** [libfacebook_la-marshal.lo] Error 1
make[1]: Leaving directory '/opt/purple-facebook/pidgin/libpurple/protocols/facebook'
Makefile:411: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
root@mattdawolfsden:/opt/purple-facebook#

**Comment by dequis** [comment]
Huh.

What distro?

Release tarball or git clone?

Run this:

```
find /opt/purple-facebook -name marshal.c
```

**Comment by mattdawolf** [comment]
ubuntu 18.04, gitclone

ran that. Got:

root@mattdawolfsden:/home/mattdawolf# find /opt/purple-facebook -name marshal.c
/opt/purple-facebook/pidgin/libpurple/protocols/facebook/marshal.c
root@mattdawolfsden:/home/mattdawolf#

**Comment by mattdawolf** [comment]
tarball compiled properly.

**Comment by dequis** [comment]
Neat

**Comment by mattdawolf** [comment]
would be neater if that didn't take my derp ass two months to figure out.
and fb supported retrieving past messages. logs dir will have a gap now.

thanks for the help.
