### ISSUE TITLE
error 406

### ISSUE THREAD

**Issue by Riamse** [dequis/purple-facebook#427]
If you have 2fa enabled on your account via text, you can't log in with this plugin. You'll receive a message `Login approvals are on. Expect an SMS shortly with a code to use for log in (406)` and a text message, but there's no way for you to use the text message to log in. No input prompt or anything shows up.

**Comment by dequis** [comment]
Use an [app password][1] (as recommended in the [basic usage][2] guide)

[1]: https://www.facebook.com/settings?tab=security&section=per_app_passwords&view
[2]: https://github.com/dequis/purple-facebook/wiki
