### ISSUE TITLE
Crash on connect

### ISSUE THREAD

**Issue by angus73** [dequis/purple-facebook#429]
Hi, for a few days now, pidgin crashes when I enter the password of my fb account. Note that the same happens either if the password is correct or not.

Pidgin 2.13.0-1.fc27 (libpurple 2.13.0)
(I currently don't know how to get the version of purple-facebook: where do I find it?)

Could anybody help me please?

Thank you very much!
Andrea

**Comment by MsJamie** [comment]
Andrea,

It looks Facebook updated something again breaking the plugin. I just tried updating from v0.9.1-c9b74a765767 to  v0.9.5-9ff9acf9fa14 and it's still not working for me. Showing "Unknown HTTP error"

As far as your question assuming you are not using the git repo itself and downloading it periodically

You can check against the libfacebook.so file in the Pidgin library directory like this

# strings libfacebook.so |grep 'Facebook$' -A1
Facebook
0.9.5-9ff9acf9fa14

That's the newest version currently as it matches the VERSION file in the repo. If you still have the old package you can check that file or the Makefile as it contains version references as well

PACKAGE_STRING = purple-facebook 0.9.5-9ff9acf9fa14
PACKAGE_VERSION = 0.9.5-9ff9acf9fa14
VERSION = 0.9.5-9ff9acf9fa14

Hope that helps

Jamie

**Comment by dequis** [comment]
Please run the "Obtaining a GDB Backtrace" command in https://github.com/dequis/purple-facebook/wiki/Debugging-Logs

Make it crash, copy the last screenful here

**Comment by dequis** [comment]
@MsJamie oh and since yours doesn't seem to be a crash follow the standard debugging logs instructions in that page and email that (don't post here)

**Comment by MsJamie** [comment]
@dequis my issue is resolved. Found it was two separate things
1. IPv6 networking issue (office network)... not under my control
2. The version that was loading wasn't the one that was expected and was actually still 0.9 , not 0.9.5 that it should have. Noticed it in the debug output and found a second file that I don't remember putting there.

Thank you!

**Comment by angus73** [comment]
@dequis running gdb I get a "Missing separate debuginfos" warning, to clear it I should install 900MB (see attached file), is it really needed?
[dbginfo.txt](https://github.com/dequis/purple-facebook/files/2230589/dbginfo.txt)

**Comment by mykhi** [comment]
+1, whatever the reason is it shouldn't crash the whole pidgin.

**Comment by dequis** [comment]
@angus73 uh, not normally, seems to be a distro specific thing. Does it just exit after saying that? That's annoying

@mykhi can you get a backtrace like i posted above?

**Comment by mykhi** [comment]
Currently it started working again, probably due to marking messages as read on the `messenger`. 
I will post the backtrace whenever it starts occurring again. It happens quite often.

**Comment by angus73** [comment]
@dequis oh no, but I was wondering whether it was strictly needed to obtain a good backtrace. I can get a bt without installing those packages, but I didn't want to waste the time of doing it (and clean private data, etc) if not useful. So, I am doing it ASAP.

**Comment by mykhi** [comment]
I think it happens when you have two pidgins connected at the same time.

**Comment by angus73** [comment]
An update on this: as per issue #430, I installed purple-facebook from dns and the problem is solved.
When I experienced the problem, I was using the binary I compiled from source.
The version is the same (purple-facebook-0.9.5-9ff9acf9fa14), and this sounds strange to me.
Let me know if you are interested in some further investigation on my side.

**Comment by besser82** [comment]
@angus73 The version provided by the Fedora repositories carry some backported fixes from the master branch of this repo, which have not been in any release tarball, yet.  That's why you do not get those crashes anymore.

**Comment by angus73** [comment]
@besser82 thank your for your explanation :-)
