### ISSUE TITLE
create fedora 28 repo

### ISSUE THREAD

**Issue by ychromosome** [dequis/purple-facebook#430]
can you please create a fedora 28 repo

also the fedora 27 repo is not working anymore.

**Comment by ychromosome** [comment]
I get this message upon dnf update:
`Zwischenspeicher` für Paketquelle »home_jgeboski« konnte nicht synchronisiert werden, wird `deaktiviert.`

it translates to "repo could not get synced"

**Comment by ychromosome** [comment]
@dequis 
today I get the same error on the fedora 28 repo as well: 
`Zwischenspeicher für Paketquelle »home_jgeboski« konnte nicht synchronisiert werden, wird deaktiviert.`

**Comment by besser82** [comment]
@ychromosome I'm the maintainer of that package in Fedora and EPEL (Extension packages for RHEL and CentOS).  The packages available in the distribution repositories are up2date and carry backported fixes from the master branch of this repo.

@dequis Can you please close this issue as it is verifiably invalid.

**Comment by dequis** [comment]
Uhhh not sure what's verifiable or invalid here but sure.
