### ISSUE TITLE
SSL Error on Linux

### ISSUE THREAD

**Issue by PersistentHandle** [dequis/purple-facebook#432]
Disconnected with error: "Unable to connect to b-api.facebook.com: SSL Handshake Failed"

On Linux Mint MATE Tara 19 (based on Ubuntu 18.04), using Facebook's App Passwords for login.

**Comment by dequis** [comment]
https://github.com/dequis/purple-facebook/issues/408#issuecomment-374275285

**Comment by uNouss** [comment]
I have the same issue. 
I follow #408 and I config NSS Preference plugin like this:

![img](http://i.imgur.com/UkNNsVp.png)

but it's not work

![](http://i.imgur.com/UIGoFKC.png)

**Comment by dequis** [comment]
That's not the same issue because it's not "SSL Handshake Failed", that's some other connection error. Please open a new issue and we'll talk it over there.

**Comment by janek37** [comment]
I'm getting a similar error after upgrade to Ubuntu 18.04:
[account name] disconnected
Unable to connect to graph.facebook.com: SSL Handshake Failed

**Comment by dequis** [comment]
@janek37 Again, see: https://github.com/dequis/purple-facebook/issues/408#issuecomment-374275285

**Comment by dequis** [comment]
Duplicate of #408
