### ISSUE TITLE
[HELP] SSL Certificate Verification

### ISSUE THREAD

**Issue by pussfacestalk** [dequis/purple-facebook#441]
Hello,
I have been getting quite alot of certificate verification dialog boxes for graph.fb and api.fb 
![image](https://user-images.githubusercontent.com/42937542/46524031-2d4d4d80-c8a5-11e8-8380-662fbb4ff820.png)
The issue however is, it keeps replacing the current cert with one issued by vmware valid between 2016-2017. So far i tried deleting outdated certificate from certificate manager and restarting pidgin. It didn't help. Neither by deleting everything from `/.purple/certificates/x509/tls_peers` folder.

Please help. It is really annoying as this message boxes keep popping endlessly and it isn't even keeping the connection to facebook until it somehow grabs uptodate certificate on its own (valid till march 19)

os: win 7 pro sp1 x64
pidgin: 2.13.0 (libpurple 2.13.0)
purplefb: 20180323~ef6ae47~9ff9acf9fa14~145

**Comment by dequis** [comment]
Uhh what? vmware? Can you post a screenshot of the stuff in 'view certificate'?

**Comment by pussfacestalk** [comment]
> Uhh what? vmware? Can you post a screenshot of the stuff in 'view certificate'?

![image](https://user-images.githubusercontent.com/42937542/46546661-5bec1800-c8e7-11e8-9a7e-ce38a0a83103.png)

![image](https://user-images.githubusercontent.com/42937542/46546779-b71e0a80-c8e7-11e8-8815-6312bb9da96f.png)
