### ISSUE TITLE
Pidgin disconnects when sending a message to a friend from Facebook

### ISSUE THREAD

**Issue by rusofil** [dequis/purple-facebook#447]
Lately I had my system reinstalled. 2 weeks or so ago. Before that Pidgin worked perfectly with Facebook purple and  I had no issues sending and receiving messages from Facebook messenger. But after reinstallation of my Windows, and after adding Purple to Pidgin I'm unable to send messages. Pidgin keeps disconnecting me every time I press enter. It seems Pidgin connects well to Purple, it accepts my password and login and there's a list of friends from Facebook, but there's still that issue. Can you guys help me resolve that problem?

**Comment by EionRobb** [comment]
Can you get a debug log when you send a message?
https://github.com/dequis/purple-facebook/wiki/Debugging-Logs

**Comment by dequis** [comment]
I didn't get anything, so closing due to lack of response (feel free to send stuff though)
