### ISSUE TITLE
Stopped working - Failed to get sync_sequence_id

### ISSUE THREAD

**Issue by boskar** [dequis/purple-facebook#449]
Facebook for purple stopped working today with above message. 

Debug received is: 

Dzi\u0119kujemy za korzystanie z Messengera. Z przykro\u015bci\u0105 informujemy, \u017ce od dzisiaj (29 marca) u\u017cywana przez Ciebie wersja aplikacji nie b\u0119dzie obs\u0142ugiwana, przez co nie b\u0119dzie ju\u017c mo\u017cna wysy\u0142a\u0107 i odbiera\u0107 wiadomo\u015bci. Aby nadal korzysta\u0107 z Messengera, zainstaluj najnowsz\u0105 wersj\u0119 aplikacji Messenger: https:\/\/play.google.com\/store\/apps\/details?id=com.facebook.orca Je\u017celi Tw\u00f3j telefon nie obs\u0142uguje najnowszych wersji aplikacji Messenger, masz dwie mo\u017cliwo\u015bci: 1) Mo\u017cesz zainstalowa\u0107 aplikacj\u0119 Facebook Lite, aby uzyska\u0107 dost\u0119p do wiadomo\u015bci. Jest to uproszczona wersja aplikacji Facebook, kt\u00f3ra jest szybka, zu\u017cywa mniej danych i dzia\u0142a tak\u017ce w wolniejszych sieciach. Zainstaluj j\u0105 z tego \u017ar\u00f3d\u0142a: https:\/\/fb.me\/aVEhe5AIomBFH9 2) Zalecamy przej\u015bcie do strony https:\/\/m.facebook.com\/messages w przegl\u0105darce mobilnej. Dzi\u0119kujemy Zesp\u00f3\u0142 aplikacji Messenger","message_sender":{"id":"602814669838217"},"unread":true,"offline_threading_id":"6198677104802234982","message":{"text":"Dzi\u0119kujemy za korzystanie z Messengera. Z przykro\u015bci\u0105 informujemy, \u017ce od dzisiaj (29 marca) u\u017cywana przez Ciebie wersja aplikacji nie b\u0119dzie obs\u0142ugiwana, przez co nie b\u0119dzie ju\u017c mo\u017cna wysy\u0142a\u0107 i odbiera\u0107 wiadomo\u015bci. Aby nadal korzysta\u0107 z Messengera, zainstaluj najnowsz\u0105 wersj\u0119 aplikacji Messenger: https:\/\/play.google.com\/store\/apps\/details?id=com.facebook.orca Je\u017celi Tw\u00f3j telefon nie obs\u0142uguje najnowszych wersji aplikacji Messenger, masz dwie mo\u017cliwo\u015bci: 1) Mo\u017cesz zainstalowa\u0107 aplikacj\u0119 Facebook Lite, aby uzyska\u0107 dost\u0119p do wiadomo\u015bci. Jest to uproszczona wersja aplikacji Facebook, kt\u00f3ra jest szybka, zu\u017cywa mniej danych i dzia\u0142a tak\u017ce w wolniejszych sieciach. Zainstaluj j\u0105 z tego \u017ar\u00f3d\u0142a: https:\/\/fb.me\/aVEhe5AIomBFH9 2) Zalecamy przej\u015bcie do strony https:\/\/m.facebook.com\/messages w przegl\u0105darce mobilnej. Dzi\u0119kujemy Zesp\u00f3\u0142 aplikacji Messenger

(Polish for: Thank You for using Messenger, Your version is not supported since March 29, please update, blah blah blah). Duplicate of #349 ? New issue? Happened today, version: 20180323~ef6ae47~9ff9acf9fa14~145

**Comment by plavirudar** [comment]
I can verify (along with the others) that this is also an issue for me. (Windows, pidgin 2.13, latest plugin)

All of my accounts across all computers have stopped working, and generating a new app password doesn't work.  From the looks of the debug message, it seems that they've started blocking the announce version of the plugins.

**Comment by Whovian9369** [comment]
Also seems to be an issue for me as well. Been using the plugin (thank you for it, by the way) to help keep in contact with family and friends easily.
My Debug output makes me think that my issue seems to be an issue with the certificate, so I'm not sure if it's a different problem or not? My timeframe of having this error for ~2 days also seems to be correct, so that's part of the reason that I think it's the same issue as above.

Attached a slightly redacted copy of my log from a Windows install of Pidgin. Issue also affects Arch Linux laptop with same/similar Pidgin setup (accounts and plugins).

Version Info:
```
Pidgin 2.12.0 (libpurple 2.12.0) -- Attached debug output is from this version
Pidgin 2.13.0 (libpurple 2.13.0) -- Also seems to affect this version (Updated while writing)
Plugin Version: 20180323~ef6ae47~9ff9acf9fa14~145
```

[Purple_Facebook_Debug_Output_010419_0130.txt](https://github.com/dequis/purple-facebook/files/2726159/Purple_Facebook_Debug_Output_010419_0130.txt)

**Comment by Martyprod** [comment]
Same here ! 

(12:28:29) nss: Trusting CN=*.facebook.com,O="Facebook, Inc.",L=Menlo Park,ST=California,C=US
(12:28:29) certificate: Successfully verified certificate for graph.facebook.com
(12:28:29) http: Request performed successfully.
(12:28:29) connection: Connection error on 053C61D8 (reason: 0 description: Failed to get sync_sequence_id)
(12:28:29) account: Disconnecting account 
(12:28:29) connection: Disconnecting connection

**Comment by edtsz** [comment]
Same here:

```shell
$ uname -a
Linux pc1.edtsz.com 4.19.13-300.fc29.x86_64 #1 SMP Sat Dec 29 22:54:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ pidgin --help
Pidgin 2.13.0-6.fc29
```

About _purple-facebook_ package:
```
Nome         : purple-facebook
Versão       : 0.9.5
Lançamento   : 11.9ff9acf9fa14.fc29
Arq.         : x86_64
Tam.         : 256 k
Origem       : purple-facebook-0.9.5-11.9ff9acf9fa14.fc29.src.rpm
```

About pidgin:
```
Pidgin 2.13.0-6.fc29 (libpurple 2.13.0)
f07927902113041d6fa291293d9205ea4f05e9e6

Informações sobre build
  Arguments to ./configure:   '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--enable-gnutls=no' '--enable-nss=yes' '--enable-cyrus-sasl' '--enable-tcl' '--enable-tk' '--disable-schemas-install' '--with-extraversion=6.fc29' '--enable-perl' '--disable-gevolution' '--enable-dbus' '--with-python=/usr/bin/python3' '--disable-nm' '--with-gstreamer=1.0' '--with-system-ssl-certs=/etc/pki/tls/certs' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' 'LDFLAGS=-Wl,-z,relro   -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld' 'PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig'
  Print debugging messages: No
  Plugins: Enabled
  SSL: SSL support is present.

  Library Support
    Cyrus SASL: Enabled
    D-Bus: Enabled
    Evolution Addressbook: Disabled
    Gadu-Gadu library (libgadu): External
    GtkSpell: Enabled
    GnuTLS: Disabled
    GStreamer: Enabled
    Mono: Disabled
    NetworkManager: Disabled
    Network Security Services (NSS): Enabled
    Perl: Disabled
    Tcl: Disabled
    Tk: Disabled
    UTF-8 DNS (IDN): Enabled
    Voice and Video: Enabled
    X Session Management: Enabled
    XScreenSaver: Enabled
    Zephyr library (libzephyr): Internal
    Zephyr uses Kerberos: No
```

**Comment by dequis** [comment]
Yeah I get it. Give me some time.

**Comment by ticris** [comment]
I have 2 messenger accounts set up, but only for one of them I get the error.

**Comment by besser82** [comment]
Comenting here to be in the loop in case of a fix.

**Comment by jirikeller** [comment]
Subscribing here as well from original #349 as dequis claimed that this is better thread. Looking forward for the fix, fingers crossed !

**Comment by dequis** [comment]
Use the 'subscribe' button on the right sidebar

**Comment by Martyprod** [comment]
>  I hate Farcebook and although most of my friends are on Skype since the old MSN Messenger log/passes work with it, but I need to be able to speak to most of my family who only use fb chat because they actually go on-site and play their dumb made-to-be-addictive puzzle games.

Same issue as you !

**Comment by EionRobb** [comment]
We don't need any more "me too" messages.  Just use the "Subscribe" button on the right if you want to be notified of any updates

**Comment by dequis** [comment]
Pushed a commit that seems to fix the thing. Please test. Thanks to @thorgrin for pointing this out.

~~Windows builds available from the same place as usual in ten mins or so.~~ nnnnnnnnnevermind some part of the pipeline broke, i'll fix it later today, be patient. [Unless someone else wants to give it a shot][1]

[1]: https://travis-ci.org/dequis/purple-facebook/jobs/476273783#L816

Linux tarballs later today but y'all can just put up with the crappy mercurial-requiring ./autogen.sh anyway.

**Comment by EionRobb** [comment]
[libfacebook.zip](https://github.com/dequis/purple-facebook/files/2732267/libfacebook.zip)
I've compiled it, but haven't tested it

**Comment by bellouffmdach** [comment]
> 
> 
> [libfacebook.zip](https://github.com/dequis/purple-facebook/files/2732267/libfacebook.zip)
> I've compiled a dll for Windows, but haven't tested it

Works for me with Pidgin 2.13.0 on Windows 7! :-)

**Comment by defeatillusion** [comment]
> [libfacebook.zip](https://github.com/dequis/purple-facebook/files/2732267/libfacebook.zip)
> I've compiled a dll for Windows, but haven't tested it

Awesome, I tested it.No more synch error. Facebook chat is working now.Thank you very much.
(Pidgin Pidgin 2.12.0 on Windows 10)

**Comment by SarcasmCupcakes** [comment]
2.12.0, Win 10, didn't work for me.

(I recently updated my FB password and pidgin kept saying unauthorized, so I deleted that and re-did the account)

**Comment by quoing** [comment]
Compiled from master for linux / spectrum2, login is now OK. Thx

**Comment by Martyprod** [comment]
> [libfacebook.zip](https://github.com/dequis/purple-facebook/files/2732267/libfacebook.zip)
> I've compiled a dll for Windows, but haven't tested it

Pidgin 2.13.0 + Windows 10 pro = Work Again ! Thank you !

**Comment by SpiritualForest** [comment]
Arch Linux, Pidgin 2.13.0, installed via purple-facebook-git AUR package. Issue resolved for me. Thank you.

**Comment by ae-bogdan** [comment]
Pidgin 2.12.0, Windows 8. Works great.

**Comment by paulb104** [comment]
So, just to be crystal clear, get the libfacebook.dll out of the .zip file, shut down Pidgin, put the .dll in the main Pidgin folder then open Pidgin again. This should be resolve this issue? Am I missing a step? I hope so, because that didn't work for me...

**Comment by paulb104** [comment]
Oh, I see now. SarcasmCupcakes previous message was backwards, where you said "put the new thing in the plugin folder rather than top-level."

So I renamed the original .dll to .dllold and moved the new one into the plugins folder and it's working again!

Thanks so much! Sorry this crap had to happen!

**Comment by gilthanis** [comment]
Downloaded and installed newest version 2.13.0  on Windows 10 Home 64bit,  copied dll file to plugins and started pidgin and same issue.  No option for facebook listed in account management and won't work with xmpp either. Thanks

**Comment by ae-bogdan** [comment]
Something strange that happened to me, and you might have to look out for - when I renamed the previous libfacebook.dll file to libfacebook-20190701.dll, Pidgin would still load the previous version of it.

So you should completely remove the old one from the folder, imo.

**Comment by vitin22** [comment]
i have this problem with ubuntu 18.04....Failed to get sync_sequence_id

**Comment by gilthanis** [comment]
> Something strange that happened to me, and you might have to look out for - when I renamed the previous libfacebook.dll file to libfacebook-20190701.dll, Pidgin would still load the previous version of it.
> 
> So you should completely remove the old one from the folder, imo.

Completely uninstalled pidgin, rebooted,  installed new version of Pidgin and then added the .dll  no older version existed in my install.   still won't connect.

**Comment by tuxmaster5000** [comment]
Fixed on Fedora with the last git version.

**Comment by linkp** [comment]
Ubuntu 16.04.5 LTS here. I was using the deb package. I gave it an "apt remove" and then ran a build from the git repo with a global install. I am thrilled to report that all is working as expected. Thanks for the quick fix.

**Comment by gilthanis** [comment]
> > Something strange that happened to me, and you might have to look out for - when I renamed the previous libfacebook.dll file to libfacebook-20190701.dll, Pidgin would still load the previous version of it.
> > So you should completely remove the old one from the folder, imo.
> 
> Completely uninstalled pidgin, rebooted, installed new version of Pidgin and then added the .dll no older version existed in my install. still won't connect.

I fixed this issue I had by going to https://github.com/dequis/purple-facebook/wiki/Installing-on-Windows and re-adding the libjson-glib-1.0.dll to my main Pidgin folder as well as the updated facebook.dll to my plugins folder.  It is now working for me as well.

**Comment by rathann** [comment]
> Fixed on Fedora with the last git version.

Indeed, it is fixed. Thanks!

**Comment by MAN-AT-ARMS** [comment]
Patch has not resolved the issue for me.

**Comment by vitin22** [comment]
I still with the same problem...in ubuntu 18.04 "Failed to get sync_sequence_id"...i update the last fedora purple-facebook....and nothing

**Comment by besser82** [comment]
> /usr/bin/ld: cannot find -lgadu

You need to have `libgadu-devel` installed.

**Comment by shorewall** [comment]
Tks very much.
Now it compiles and works like a charm

**Comment by sanyooh** [comment]
Will the Linux Tarball be created today?

**Comment by gabrielgg** [comment]
> some part of the pipeline broke, i'll fix it later today, be patient. [Unless someone else wants to give it a shot](https://travis-ci.org/dequis/purple-facebook/jobs/476273783#L816)

Just a thought, as I'm not very familiar with Travis and don't know how well you can affect the containers that they provide - it looks like their mercurial installation is not done properly (see all the warnings and whatnot).
You _may_ be able to hack it by including:
`[ui]`
`tls=False`
in ~/.hgrc, albeit I can't test it as my installation works ok.

**Comment by MAN-AT-ARMS** [comment]
> > some part of the pipeline broke, i'll fix it later today, be patient. [Unless someone else wants to give it a shot](https://travis-ci.org/dequis/purple-facebook/jobs/476273783#L816)
> 
> Just a thought, as I'm not very familiar with Travis and don't know how well you can affect the containers that they provide - it looks like their mercurial installation is not done properly (see all the warnings and whatnot).
> You _may_ be able to hack it by including:
> `[ui]`
> `tls=False`
> in ~/.hgrc, albeit I can't test it as my installation works ok.

I had to do this as well.

**Comment by mbrancalion** [comment]
> You may be able to hack it by including:
> [ui]
> tls=False

I had to do the same, in one installation. On another it was not necessary.

**Comment by besser82** [comment]
> Windows builds available from the same place as usual in ten mins or so. nnnnnnnnnevermind some part of the pipeline broke, i'll fix it later today, be patient. [Unless someone else wants to give it a shot](https://travis-ci.org/dequis/purple-facebook/jobs/476273783#L816)

@dequis I've added a fix for the build-pipeline in #440

**Comment by joshuawlawson** [comment]
Will the Linux Tarball be created today?

**Comment by joshuawlawson** [comment]
I understand. When I try using git, I receive the error about not sure which file to patch. This is likely due to my ignorance and I do take full responsibility.

**Comment by lowermouse** [comment]
> I understand. When I try using git, I receive the error about not sure which file to patch. This is likely due to my ignorance and I do take full responsibility.

The same happened to me, :(

**Comment by delul** [comment]
Same error here, it requires a file to patch.

**Comment by dequis** [comment]
Can someone post the full output between `./autogen.sh` and the error where it says it needs a file?

To everyone else: you might be interested in the "unsubscribe" button on the right sidebar

**Comment by jirikeller** [comment]
./autogen.sh 
abort: error: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:581)
abort: repository .pidgin not found!
abort: repository .pidgin not found!
cp: cannot stat '.pidgin/AUTHORS': No such file or directory
cp: cannot stat '.pidgin/COPYING': No such file or directory
cp: cannot stat '.pidgin/COPYRIGHT': No such file or directory
cp: cannot stat '.pidgin/libpurple/glibcompat.h': No such file or directory
cp: cannot stat '.pidgin/libpurple/http.c': No such file or directory
cp: cannot stat '.pidgin/libpurple/http.h': No such file or directory
cp: cannot stat '.pidgin/libpurple/protocols/facebook/api.c': No such file or directory
cp: cannot stat '.pidgin/libpurple/protocols/facebook/api.h': No such file or directory
cp: cannot stat '.pidgin/libpurple/protocols/facebook/data.c': No such file or directory
cp: cannot stat '.pidgin/libpurple/protocols/facebook/data.h': No such file or directory
cp: cannot stat '.pidgin/libpurple/protocols/facebook/facebook.c': No such file or directory
cp: cannot stat '.pidgin/libpurple/protocols/facebook/facebook.h': No such file or directory
cp: cannot stat '.pidgin/libpurple/protocols/facebook/http.c': No such file or directory
cp: cannot stat '.pidgin/libpurple/protocols/facebook/http.h': No such file or directory
cp: cannot stat '.pidgin/libpurple/protocols/facebook/id.h': No such file or directory
cp: cannot stat '.pidgin/libpurple/protocols/facebook/json.c': No such file or directory
cp: cannot stat '.pidgin/libpurple/protocols/facebook/json.h': No such file or directory
cp: cannot stat '.pidgin/libpurple/protocols/facebook/Makefile.am': No such file or directory
cp: cannot stat '.pidgin/libpurple/protocols/facebook/Makefile.mingw': No such file or directory
cp: cannot stat '.pidgin/libpurple/protocols/facebook/mqtt.c': No such file or directory
cp: cannot stat '.pidgin/libpurple/protocols/facebook/mqtt.h': No such file or directory
cp: cannot stat '.pidgin/libpurple/protocols/facebook/thrift.c': No such file or directory
cp: cannot stat '.pidgin/libpurple/protocols/facebook/thrift.h': No such file or directory
cp: cannot stat '.pidgin/libpurple/protocols/facebook/util.c': No such file or directory
cp: cannot stat '.pidgin/libpurple/protocols/facebook/util.h': No such file or directory
can't find file to patch at input line 4
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff -r ad2ee74b913a libpurple/protocols/facebook/Makefile.am
|--- a/libpurple/protocols/facebook/Makefile.am	Thu Jan 07 14:06:04 2016 -0500
|+++ b/libpurple/protocols/facebook/Makefile.am	Thu Jan 07 15:45:09 2016 -0500
--------------------------
File to patch: ^C

**Comment by greatquux** [comment]
I don't really know why the checkout is failing, like some people said it might be due to some mercurial settings that have to be changed (see https://github.com/dequis/purple-facebook/issues/449#issuecomment-452272340) but for anyone who just wants a binary (x86-64 compiled on Ubuntu 18.10) here's one:
https://www.dropbox.com/s/dxt2phw6hj1nt3u/libfacebook.so?dl=0

**Comment by greatquux** [comment]
Of course, these days, no should trust links to random binaries... ;)

**Comment by delul** [comment]
At this point the patch file error disappeared, but after it gets all the files  I have other error:

978 files updated, 0 files merged, 364 files removed, 0 files unresolved
./update.sh: 38: ./update.sh: patch: not found
./update.sh: 38: ./update.sh: patch: not found
./update.sh: 38: ./update.sh: patch: not found
./update.sh: 38: ./update.sh: patch: not found
./update.sh: 38: ./update.sh: patch: not found
./update.sh: 38: ./update.sh: patch: not found
./update.sh: 38: ./update.sh: patch: not found
./update.sh: 38: ./update.sh: patch: not found
./update.sh: 38: ./update.sh: patch: not found
./update.sh: 38: ./update.sh: patch: not found
./update.sh: 38: ./update.sh: patch: not found
./update.sh: 38: ./update.sh: patch: not found
./update.sh: 38: ./update.sh: patch: not found
./update.sh: 38: ./update.sh: patch: not found

**Comment by MAN-AT-ARMS** [comment]
Note above for *nix installs...this is a workaround for the SSL: WRONG_VERSION_NUMBER error.

Create a file .hgrc in your home directory (if it does not exist - do not forget to include the leading dot).

Add these lines and save:
[ui]
tls=False

Then run the autogen.sh

**Comment by delul** [comment]
Ok, I managed to compile and install the plugin, but when i add the account I get new error in Pidgin window:
Unable to connect to b-api.facebook.com: SSL Handshake Failed

I also added .hgrc file.. but no luck

**Comment by joshuawlawson** [comment]
After adding the .hgrc file, I now see the following handshake error:

sudo ./autogen.sh 
applying clone bundle from https://api.media.atlassian.com/file/7c1d2160-a2cc-43cc-9d3e-a765cc6851a6/binary?client=7265e9a9-2bda-4f7d-a703-5fea68345b26&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOnsidXJuOmZpbGVzdG9yZTpmaWxlOjdjMWQyMTYwLWEyY2MtNDNjYy05ZDNlLWE3NjVjYzY4NTFhNiI6WyJyZWFkIl19LCJleHAiOjE1NDcwNjc5NjYsImlzcyI6IjcyNjVlOWE5LTJiZGEtNGY3ZC1hNzAzLTVmZWE2ODM0NWIyNiIsIm5iZiI6MTU0NzA2NzU0Nn0.b3rgt3Y8MFkCjfVvQU0mpY0vHYKvZQCKyMR7hjBwjhE
error fetching bundle: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:727)
abort: error applying bundle
(if this error persists, consider contacting the server operator or disable clone bundles via "--config ui.clonebundles=false")

**Comment by jirikeller** [comment]
anyone who just wants a binary (x86-64 compiled on Ubuntu 18.10) here's one:
> https://www.dropbox.com/s/dxt2phw6hj1nt3u/libfacebook.so?dl=0

I tried out the binary, however does not help much (debian jessie, spectrum2, backend1.log):

```
19640: 2019-01-09 22:11:05,098 INFO  backend: Buddy updated user@svr 000000 John Doe group (1)=Facebook Friends
19640: 2019-01-09 22:11:05,109 INFO  libpurple: http:Request 0x232bb00 performed successfully.
19640: 2019-01-09 22:11:05,109 INFO  libpurple: util:Writing file /var/lib/spectrum2/fb.svr/icons/3e0b6....jpg
19640: 2019-01-09 22:11:05,111 INFO  libpurple: http:Performing new request 0x2245e00 to scontent.xx.fbcdn.net.
19640: 2019-01-09 22:11:05,111 INFO  libpurple: dnsquery:Performing DNS lookup for scontent.xx.fbcdn.net
19640: 2019-01-09 22:11:05,111 INFO  libpurple: dns:Successfully sent DNS request to child 19673
19640: 2019-01-09 22:11:05,112 INFO  libpurple: dns:Got response for 'scontent.xx.fbcdn.net'
19640: 2019-01-09 22:11:05,112 INFO  libpurple: dnsquery:IP resolved for scontent.xx.fbcdn.net
19640: 2019-01-09 22:11:05,112 INFO  libpurple: proxy:Attempting connection to 31.13.84.4
19640: 2019-01-09 22:11:05,112 INFO  libpurple: proxy:Connecting to scontent.xx.fbcdn.net:443 with no proxy
19640: 2019-01-09 22:11:05,112 INFO  libpurple: proxy:Connection in progress
19640: 2019-01-09 22:11:05,113 INFO  libpurple: http:Request 0x22f1d00 performed successfully.
19640: 2019-01-09 22:11:05,113 INFO  libpurple: util:Writing file /var/lib/spectrum2/fb.svr/icons/b47f5b623795470f0be2996e881b516d27c5df1b.jpg
19640: 2019-01-09 22:11:05,114 INFO  libpurple: http:Performing new request 0x232bb00 to scontent.xx.fbcdn.net.
19640: 2019-01-09 22:11:05,115 INFO  libpurple: http:Request 0x22dd640 performed successfully.
19640: 2019-01-09 22:11:05,115 INFO  libpurple: util:Writing file /var/lib/spectrum2/fb.svr/icons/cb....jpg
19640: 2019-01-09 22:11:05,115 INFO  libpurple: http:Performing new request 0x2334100 to scontent.xx.fbcdn.net.
19640: 2019-01-09 22:11:05,116 INFO  libpurple: dnsquery:Performing DNS lookup for scontent.xx.fbcdn.net
19640: 2019-01-09 22:11:05,116 INFO  libpurple: dnsquery:Performing DNS lookup for scontent.xx.fbcdn.net
19640: 2019-01-09 22:11:05,116 INFO  libpurple: dns:Successfully sent DNS request to child 19673
19640: 2019-01-09 22:11:05,116 INFO  libpurple: dns:Successfully sent DNS request to child 19675
19640: 2019-01-09 22:11:05,116 INFO  libpurple: dns:Got response for 'scontent.xx.fbcdn.net'
19640: 2019-01-09 22:11:05,116 INFO  libpurple: dnsquery:IP resolved for scontent.xx.fbcdn.net
19640: 2019-01-09 22:11:05,116 INFO  libpurple: proxy:Attempting connection to 31.13.84.4
19640: 2019-01-09 22:11:05,116 INFO  libpurple: proxy:Connecting to scontent.xx.fbcdn.net:443 with no proxy
19640: 2019-01-09 22:11:05,116 INFO  libpurple: proxy:Connection in progress
19640: 2019-01-09 22:11:05,116 INFO  libpurple: dns:Got response for 'scontent.xx.fbcdn.net'
19640: 2019-01-09 22:11:05,116 INFO  libpurple: dnsquery:IP resolved for scontent.xx.fbcdn.net
19640: 2019-01-09 22:11:05,116 INFO  libpurple: proxy:Attempting connection to 31.13.84.4
19640: 2019-01-09 22:11:05,116 INFO  libpurple: proxy:Connecting to scontent.xx.fbcdn.net:443 with no proxy
19640: 2019-01-09 22:11:05,116 INFO  libpurple: proxy:Connection in progress
19640: 2019-01-09 22:11:05,120 INFO  libpurple: proxy:Connecting to scontent.xx.fbcdn.net:443.
19640: 2019-01-09 22:11:05,120 INFO  libpurple: proxy:Connected to scontent.xx.fbcdn.net:443.
19640: 2019-01-09 22:11:05,124 INFO  libpurple: proxy:Connecting to scontent.xx.fbcdn.net:443.
19640: 2019-01-09 22:11:05,124 INFO  libpurple: proxy:Connected to scontent.xx.fbcdn.net:443.
19640: 2019-01-09 22:11:05,125 INFO  libpurple: proxy:Connecting to scontent.xx.fbcdn.net:443.
19640: 2019-01-09 22:11:05,125 INFO  libpurple: proxy:Connected to scontent.xx.fbcdn.net:443.
19640: 2019-01-09 22:11:05,126 INFO  libpurple: http:Request 0x2398200 performed successfully.
19640: 2019-01-09 22:11:05,126 INFO  libpurple: connection:Connection error on 0x22d24c0 (reason: 0 description: Failed to get sync_sequence_id)
19640: 2019-01-09 22:11:05,127 INFO  libpurple: account:Disconnecting account jiri.keller (0x2206f00)
19640: 2019-01-09 22:11:05,127 INFO  libpurple: connection:Disconnecting connection 0x22d24c0
19640: 2019-01-09 22:11:05,127 INFO  libpurple: http:Request 0x2334100 performed without success.
19640: 2019-01-09 22:11:05,128 INFO  libpurple: http:Request 0x2245e00 performed without success.
19640: 2019-01-09 22:11:05,128 INFO  libpurple: http:Request 0x232bb00 performed without success.
19640: 2019-01-09 22:11:05,128 INFO  libpurple: connection:Destroying connection 0x22d24c0
19640: 2019-01-09 22:11:05,129 ERROR backend: g_log purple_account_disconnect: assertion '!purple_account_is_disconnected(account)' failed
19640: 2019-01-09 22:11:05,130 INFO  libpurple: account:Destroying account 0x2206f00
19640: 2019-01-09 22:11:10,069 INFO  libpurple: util:Writing file accounts.xml to directory /var/lib/spectrum2/fb.svr
19640: 2019-01-09 22:11:10,069 INFO  libpurple: util:Writing file /var/lib/spectrum2/fb.svr/accounts.xml
19640: 2019-01-09 22:11:20,020 INFO  backend: Exiting...
```

**Comment by greatquux** [comment]
are you sure you overwrote the original one and restarted pidgin?

**Comment by jirikeller** [comment]
I do not use pidgin but spectrum2. Re-checked and the only occurrence of .so file is replaced. Maybe some strange caching of .so somewhere ? Any idea ?

**Comment by bf0003** [comment]
I still have the same error, does anyone have libfacebook.so for this ?
```
$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
$ pidgin --version
Pidgin 2.10.12 (libpurple 2.10.12)
```

**Comment by lowermouse** [comment]
So to whom should I send nudes to motivate them to fix this?

**Comment by elguaposghost** [comment]
Even though my paranoid side advised against it, I downloaded the .so file mentioned above and that works for now.

**Comment by MarkMura** [comment]
Strange, it was working for me fine for the last week, but stopped yesterday. Debug window shows request timeout and unknown http error, no mention of any sequence_id, so not sure if it's the same issue.

Do you know when will a new build be available at the PPA for Ubuntu: https://jgeboski.github.io/#package-repositories ? Or is that obsolete? Any other PPA available?

**Comment by MarkMura** [comment]
Great, it works now. Thanks very much

**Comment by boskar** [comment]
@MarkMura works for me for now, using @jgeboski repo on Debian

**Comment by dequis** [comment]
Oh and I guess the pinned issues thing lets me close this

**Comment by gradius-v** [comment]
This issue has returned today.
