### ISSUE TITLE
Add option to disable prefixed timestamps

### ISSUE THREAD

**Issue by Avamander** [dequis/purple-facebook#455]
Is there a way to disable the timestamps purple-facebook prefixes to group chat messages when using it with bitlbee?

It's really unnecessary especially given most clients display the time messages have been received anyways.

**Comment by dequis** [comment]
That's a bitlbee thing. See `help set display_timestamps` in &bitlbee. If you see it in all messages, your system clock might be wrong.

Also, you might want to use [bitlbee-facebook][1] instead.

[1]: https://github.com/bitlbee/bitlbee-facebook/

**Comment by Avamander** [comment]
My system clock is synchronized with NTP and this doesn't happen with other services except this plugin. 


`bitlbee-facebook` had some other bug that was a showstopper.

**Comment by Avamander** [comment]
It's weird though that cap server-time can't be used to send clients this timestamp information and instead timestamp is prefixed.

**Comment by dequis** [comment]
Please open an issue on the bitlbee-facebook repo.

**Comment by Avamander** [comment]
Why? I'm not using it.

**Comment by Avamander** [comment]
Just installed this and latest bitlbee from git and I still have this issue, I see an additional timestamp prefixed to each message.

**Comment by dequis** [comment]
> That's a bitlbee thing. See `help set display_timestamps` in &bitlbee. If you see it in all messages, your system clock might be wrong.

**Comment by dequis** [comment]
To be clear, I meant that `display_timestamps` is the option you're requesting in the title of this issue.

**Comment by Avamander** [comment]
Oh, thank you! Hopefully this issue helps others with the same issue as well.

I guess this is caused by the fact that earlier messages might be delivered later, upon connection, and bitlbee lacks the ability to use `system-time` to inform the client properly when the message was actually received. I pinged the Bitlbee issue about `system-time`. Other plugins don't deliver older messages which is why I didn't notice it with other plugins.
