### ISSUE TITLE
fbjoin crash

### ISSUE THREAD

**Issue by isakrubin** [dequis/purple-facebook#464]
Trying to join an existing chat makes bitlbee crash and restart.

06:40:11  @me | fbjoin 7 #xxx
06:40:11 @root | facebook - Error: Failed to create chat: 20812800119XXXXX
06:40:11    -- | irc: disconnected from server

Is this a known issue?

**Comment by dequis** [comment]
That's bitlbee-facebook, not purple-facebook.

If you're using bitlbee 3.6 you might have a message in your irc status window with a crash log, otherwise follow https://wiki.bitlbee.org/DebuggingCrashes

And please reopen this in the other bug tracker.
