### ISSUE TITLE
Tricks to post to timeline

### ISSUE THREAD

**Issue by slackhead** [dequis/purple-facebook#469]
I found a way of posting to my timeline by messaging my self-contact, and then opening facebook in a tinfoil/browser and copying the text to my timeline, but I wondered if anyone had found an easier way to do it without needing to open a browser?

**Comment by PhantomWatson** [comment]
This doesn't appear to be related to the scope of the Purple Facebook plugin, which only interfaces with Facebook Messenger.

**Comment by slackhead** [comment]
On Fri 20 Sep 2019 11:21,
Graham Watson <notifications@github.com> put forth the proposition:
> This doesn't appear to be related to the scope of the Purple Facebook plugin, which only interfaces with Facebook Messenger.

Well, I am using the plugin to do it.

**Comment by PhantomWatson** [comment]
To clarify, your request for support for posting to a Facebook timeline appears to fall outside of the scope of this plugin.

**Comment by dequis** [comment]
> Well, I am using the plugin to do it.

Heh, more like using the plugin as a note taking app and then doing the actual posting by hand.

But yeah, as a general rule, if the android facebook messenger can't do it, we can't do it. Our tokens are restricted by the same permissions as them.

So yeah, out of scope.
