### ISSUE TITLE
https://dequis.org/ is timing out

### ISSUE THREAD

**Issue by yahooeny** [dequis/purple-facebook#471]
Can't download libfacebook.dll due to https://dequis.org/libfacebook.dll timing out

**Comment by dequis** [comment]
Sorry for that :(

No idea what's up with the hosting, they aren't replying to me anymore.

**Comment by yahooeny** [comment]
is there a mirror to the dll?

**Comment by yahooeny** [comment]
welp i guess it's back up. closing for now. i wish the dll would be packaged on the github releases page instead of being hosted on an outside host that has the tendency to shut down without notice but i guess i got what i needed for now.
