### ISSUE TITLE
Failed getting PPFT value, please try logging in via browser first

### ISSUE THREAD

**Issue by grzegorz-janoszka** [dequis/purple-facebook#472]
Hi,
That is an awesome plugin and I appreciate all the work on it. It has one major flaw - whenever the networks goes down, the plugin disables the account with the message "Failed getting PPFT value, please try logging in via browser first". I have to click re-enable and everything is fine. It would be great if this plugin could detect that network is missing and just wait, like all other programs do.

**Comment by EionRobb** [comment]
That error is from the skypeweb plugin not the Facebook one and means you need to upgrade that plugin
