### ISSUE TITLE
Host timeout to https://dequis.org/

### ISSUE THREAD

**Issue by jangliss** [dequis/purple-facebook#473]
I saw somebody reported an issue the other day, but closed it out as things seem to be responding again, however it looks like https://dequis.org is once again unreachable.  I did some checking, and it looks like traceroute is returning destination host unreachable from something upstream from the host.

Is there any chance the libfacebook.dll could be added to the release packages on github? Or do you need another mirror to host on?

Thanks!

**Comment by xdmtk** [comment]
Still experiencing this. Any updates?

**Comment by dequis** [comment]
I started setting up a new server over the weekend from a 3 month old backup aaaaaaaand this morning it came back. Still not a single reply from support.

This provider isn't the same it was a few years ago, nowadays it's not even worth keeping for free (they gave me a free year one time that they forgot to tell me about planned maintenance)

**Comment by xdmtk** [comment]
Nice. Up and running now.
