### ISSUE TITLE
Debian and Ubuntu repository key expired again

### ISSUE THREAD

**Issue by dreamlayers** [dequis/purple-facebook#476]
In Ubuntu 19.10 when I do `sudo apt update` I'm told "The following signatures were invalid: EXPKEYSIG 12C6ADA61C85BB5E home:jgeboski OBS Project <home:jgeboski@build.opensuse.org>", and that repository is not updated.

I ran `wget -O- https://jgeboski.github.io/obs.key | sudo apt-key add -` to download and add the key again, as instructed at https://jgeboski.github.io/#package-repositories. and the error didn't go away.

**Comment by dequis** [comment]
Why is time like this

**Comment by i-need-to-tell-you-something** [comment]
```
$ sudo apt-key list | grep -A1 expired
Warning: apt-key output should not be parsed (stdout is not a terminal)
pub   rsa2048 2015-07-23 [SC] [expired: 2019-12-05]
      1E7B F737 CB87 09F0 F740  625B 12C6 ADA6 1C85 BB5E
uid           [ expired] home:jgeboski OBS Project <home:jgeboski@build.opensuse.org>
```
Should we switch to building (in a script) for greater reliability?

**Comment by dequis** [comment]
Use this instead https://build.opensuse.org/projects/home:jgeboski/public_key

I'll update the file in the old url, and point the instructions to this other url. Copying the key was a bad idea.

**Comment by i-need-to-tell-you-something** [comment]
Hmm tangentially related, but [the previous link](https://download.opensuse.org/repositories/home:jgeboski/xUbuntu_18.04/Release.key) worked (except it expired) for me in the Ansible Playbook's `apt-key` [module](https://docs.ansible.com/ansible/latest/modules/apt_key_module.html#apt-key-add-or-remove-an-apt-key), whilst [the new link](https://build.opensuse.org/projects/home:jgeboski/public_key) doesn't.

**Comment by dequis** [comment]
Oh. Thanks.

The previous link was actually https://jgeboski.github.io/obs.key, that's what i meant by "copying the key"

I was hoping that this new link I found would also be a valid gpg public key, but I guess not.

I'll go with https://download.opensuse.org/repositories/home:jgeboski/xUbuntu_18.04/Release.key i guess, which has the downside of having the ubuntu version encoded in the url, but it'll have to do.

**Comment by i-need-to-tell-you-something** [comment]
> I was hoping that this new link I found would also be a valid gpg public key, but I guess not.

I don't know much of what I'm doing here so I wouldn't know really. What I said is the only verified part. All the other repo keys I use worked fine with the `apt-key` module. When I tried (grasping at straws) to see if I could download it with `wget -o- https://build.opensuse.org/projects/home:jgeboski/public_key`, I did get a valid-looking key:

<details>

```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.4.5 (GNU/Linux)

mQENBFWxUncBCADooelaZenOf75pypfDa9EarqnnSKMaqp2HewHHyBedwh1g0LUn
xYriU9Krjks/uzHrPyKQxTafyOCE1pqqv9ZaL0jYs1+sGpV3LG/a8S9wF1we33ff
bEpUtzFsz3DGVeLxzo9kEiLZ1mvyH/xv1eQn0LoGDl4x7vQIOYbmR5A+fPUiT3PY
E8B4KAaYC4GpgohLDnf39HAtYcnkX78q2VLmBmFQzsjyfZVqyErRiViWwkFbI/ok
TYv45nkOsJPN2aTVeHAmcbRMddAFJ63vPxuPWN5P3HVv5ine18rD3P1zHICDR8qs
jbvIH+GTlwSXRD3ZGs2/Fe3r8A7bTtowU/JzABEBAAG0PGhvbWU6amdlYm9za2kg
T0JTIFByb2plY3QgPGhvbWU6amdlYm9za2lAYnVpbGQub3BlbnN1c2Uub3JnPokB
PgQTAQIAKAUCXeDFigIbAwUJDE4jEwYLCQgHAwIGFQgCCQoLBBYCAwECHgECF4AA
CgkQEsatphyFu17uvQgAqNFFzjiRjv5gfT9tBYYnWcjJliyH2OXjwMY2IWaY3G9s
D2MOYyylJ1Pu2nOwC3AKxiquq45kq9aeK0MHlX3Pi0Ki0gPep1BnueCa1vghEGwY
8azOEcHMsfRNhBla/foXzOSs0z+gxtIIb5WHcDdrSWX3pdqGxfMEiDv5ILQWJfQh
2NXk7PXlvRKJK4Kcxjf2y/7VdEjZ2DVvTX1Hd/TkgHRMp04BdLLya+qdthlDxdf9
fu5j3g+SYXQ37jR5agEg1HLhq7jEdDLBzx5YzAWQuDIG3YCjTLk+RP1qNfCxq0Zq
K089rXIVblTcVCXOBTgjj5fwqADnlTX9/7sZHZ3bpYhGBBMRAgAGBQJVsVJ3AAoJ
EDswEbdrnWUjN0sAoLirdnJKmtcRAsQQMyfItlyo9QLGAJ9qJcXjkhGjbbdA8u7S
ILXmXbNiJw==
=tA45
-----END PGP PUBLIC KEY BLOCK-----

```
</details>

**Comment by dreamlayers** [comment]
https://build.opensuse.org/projects/home:jgeboski/public_key was a valid key and worked for me. After adding that the repository list updated without problems.

build.opensuse.org was slow. Maybe it timed out for some people?

**Comment by i-need-to-tell-you-something** [comment]
I guess my issue of the [first key](https://download.opensuse.org/repositories/home:/jgeboski/xUbuntu_18.04/Release.key) working with Ansible's apt-key module and the [new key](https://build.opensuse.org/projects/home:jgeboski/public_key) not working is unrelated to this and I should go to Stack Exchange with it.

So this can be closed?

**Comment by dreamlayers** [comment]
https://jgeboski.github.io/#package-repositories has been updated to use https://build.opensuse.org/projects/home:jgeboski/public_key for the key, which is the key address that worked for me. Below that is:

> (December 2019 update: redownload the key if you’re getting key expired)

So, this has been resolved and I'm closing it.

**Comment by dreamlayers** [comment]
Key was expired again. Installing key from https://build.opensuse.org/projects/home:jgeboski/public_key again fixed the problem.
