### ISSUE TITLE
"Failed to read fixed header" on 0.9.6

### ISSUE THREAD

**Issue by josx** [dequis/purple-facebook#482]
I have read several issues on the topic ( like #410 ), but in my case started a few days ago (without any change of software versions).

Runnig Software:
- Pidgin 2.13.0-2+b1
- Libpurple 2.13.0-2+b1
- Purple-facebook a few commits above 0.9.6 (master right now)

**Comment by dequis** [comment]
1. That's not 0.9.6: `User-Agent: Facebook plugin / Purple / 0.9.5 `
2. There's an access token in there, you should revoke that immediately, ideally change your password.

**Comment by josx** [comment]
So, sorry I will.
I have compiled it again with autogen and it is working pretty well.
