### ISSUE TITLE
Unable to use this plugin on new install of Debian 10.4

### ISSUE THREAD

**Issue by assmblyreq** [dequis/purple-facebook#484]
I'm at a complete loss.  100% fresh install of Debian 10.4.  Installed packages:
pidgin-2.13.0-2+b1 (64-bit)
pidgin-awayonlock-0.5.2-1
pidgin-data-2.13.0-2
pidgin-plugin-pack-2.7.0-3
libpurple0-2.13.0-2+b1
libpurple-bin-2.13.0-2

I see no FB Messenger protocols (only XMPP) even after a full reboot. All of these were installed from the Debian PPAs. What am I missing?

**Comment by dequis** [comment]
..guessing you figured it out?
