### ISSUE TITLE
Failed to read thrift: api.c:1897 fb_api_cb_publish_pt: assertion 'fb_thrift_read_stop(thft)' failed

### ISSUE THREAD

**Issue by hendricha** [dequis/purple-facebook#495]
Hey!

I have the above error immediatly after login. The partner list does not show, but I do get messages, however most of them multiple times.

This happens with a freshly checkedout and recompiled version.

Anyone else has this? / Is there anything else I could provide to help debug this?

**Comment by dequis** [comment]
Duplicate of #494
