### ISSUE TITLE
Facebook disconnects with various error messages

### ISSUE THREAD

**Issue by ayl001** [dequis/purple-facebook#500]
Facebook plugin disconnects every some 45 sec, with different messages : "unknown error" "unknown http error" "error http 500". This way pidgin is unusable with FB :(

**Comment by dequis** [comment]
https://github.com/dequis/purple-facebook/wiki/Debugging-Logs

**Comment by ayl001** [comment]
Well I followed the line at https://github.com/dequis/purple-facebook/wiki/Debugging-Logs and got a debugging log of more than 2MB. What may I extract from there ?  I would say the last lines where facebook disconnect ? If somebody wants the full log where could I post it ?

**Comment by ayl001** [comment]
Here maybe an interesting part of the log (although it does not give more information about the error that what I saw before:
$ tail -n 150 pidgin.log 
(19:07:16) blist: Updating buddy status for 1011036965 (Facebook)
(19:07:16) blist: Updating buddy status for 100002348646370 (Facebook)
(19:07:16) blist: Updating buddy status for 573919786 (Facebook)
(19:07:16) blist: Updating buddy status for 100001713158778 (Facebook)
(19:07:16) blist: Updating buddy status for 100004370763221 (Facebook)
(19:07:16) blist: Updating buddy status for 692076828 (Facebook)
(19:07:16) blist: Updating buddy status for 1200941320 (Facebook)
(19:07:16) blist: Updating buddy status for 100016690006762 (Facebook)
(19:07:16) blist: Updating buddy status for 1621731443 (Facebook)
(19:07:16) blist: Updating buddy status for 1412160445 (Facebook)
(19:07:16) blist: Updating buddy status for 1670791810 (Facebook)
(19:07:16) blist: Updating buddy status for 1585550293 (Facebook)
(19:07:16) blist: Updating buddy status for 1662724681 (Facebook)
(19:07:16) blist: Updating buddy status for 100001586253241 (Facebook)
(19:07:16) blist: Updating buddy status for 792620981 (Facebook)
(19:07:16) blist: Updating buddy status for 100009457942665 (Facebook)
(19:07:16) blist: Updating buddy status for 1640285581 (Facebook)
(19:07:16) blist: Updating buddy status for 786543846 (Facebook)
(19:07:16) blist: Updating buddy status for 751850196 (Facebook)
(19:07:16) blist: Updating buddy status for 1244335727 (Facebook)
(19:07:16) blist: Updating buddy status for 1641341911 (Facebook)
(19:07:16) blist: Updating buddy status for 557709244 (Facebook)
(19:07:16) util: Writing file blist.xml to directory /home/abdallah/.purple
(19:07:16) util: Writing file /home/abdallah/.purple/blist.xml
(19:07:36) dbus: Need to register an object with the dbus subsystem. (If you are not a developer, please ignore this message.)
(19:07:36) dbus: The signal "drawing-tooltip" caused some dbus error. (If you are not a developer, please ignore this message.)
(19:07:37) GLib: Source ID 5286 was not found when attempting to remove it
(19:07:40) dbus: Need to register an object with the dbus subsystem. (If you are not a developer, please ignore this message.)
(19:07:40) dbus: The signal "drawing-tooltip" caused some dbus error. (If you are not a developer, please ignore this message.)
(19:07:40) GLib: Source ID 5302 was not found when attempting to remove it
(19:07:41) dbus: Need to register an object with the dbus subsystem. (If you are not a developer, please ignore this message.)
(19:07:41) dbus: The signal "drawing-tooltip" caused some dbus error. (If you are not a developer, please ignore this message.)
(19:07:43) dbus: Need to register an object with the dbus subsystem. (If you are not a developer, please ignore this message.)
(19:07:43) dbus: The signal "conversation-displayed" caused some dbus error. (If you are not a developer, please ignore this message.)
(19:07:43) gtkconv: setting active conversation on toolbar 0x55cb154f05a0
(19:07:43) prefs: /pidgin/conversations/toolbar/wide changed, scheduling save.
(19:07:43) dbus: Need to register an object with the dbus subsystem. (If you are not a developer, please ignore this message.)
(19:07:43) dbus: The signal "blist-node-extended-menu" caused some dbus error. (If you are not a developer, please ignore this message.)
(19:07:43) dbus: Need to register an object with the dbus subsystem. (If you are not a developer, please ignore this message.)
(19:07:43) dbus: The signal "conversation-extended-menu" caused some dbus error. (If you are not a developer, please ignore this message.)
(19:07:43) gtkconv: setting active conversation on toolbar 0x55cb154f05a0
(19:07:43) GLib: Source ID 5318 was not found when attempting to remove it
(19:07:44) http: Timeout reached for request 0x55cb142defb0
(19:07:44) http: Cancelling connection 0x55cb142defb0...
(19:07:44) http: releasing a socket: 0x55cb14f040c0
(19:07:44) http: destroying socket: 0x55cb14f040c0
(19:07:44) http: Request 0x55cb142defb0 performed without success.
(19:07:44) facebook: HTTP Response (0x55cb142defb0):
(19:07:44) facebook:   Response Error: Unknown HTTP error (0)
(19:07:44) connection: Connection error on 0x55cb13f1b540 (reason: 0 description: Unknown HTTP error)
(19:07:44) account: Disconnecting account sdli@icite.fr (0x55cb133f4490)
(19:07:44) connection: Disconnecting connection 0x55cb13f1b540
(19:07:44) facebook: Writing 14 (flags: 0x0)
(19:07:44) facebook:   00000000  e0 00                                             |..|
(19:07:44) facebook:   00000010
(19:07:44) gtkutils: gdk_pixbuf_new_from_file() returned nothing for file /usr/share/pixmaps/pidgin/protocols/16/skype.png: Impossible d’ouvrir le fichier « /usr/share/pixmaps/pidgin/protocols/16/skype.png » : Permission non accordée
(19:07:44) connection: Destroying connection 0x55cb13f1b540
(19:07:49) util: Writing file prefs.xml to directory /home/abdallah/.purple
(19:07:49) util: Writing file /home/abdallah/.purple/prefs.xml
(19:07:49) util: Writing file accounts.xml to directory /home/abdallah/.purple
(19:07:49) util: Writing file /home/abdallah/.purple/accounts.xml
(19:07:49) util: Writing file blist.xml to directory /home/abdallah/.purple
(19:07:49) util: Writing file /home/abdallah/.purple/blist.xml
(19:08:03) dbus: Need to register an object with the dbus subsystem. (If you are not a developer, please ignore this message.)
(19:08:03) dbus: The signal "drawing-tooltip" caused some dbus error. (If you are not a developer, please ignore this message.)
(19:08:04) GLib: Source ID 8386 was not found when attempting to remove it
(19:08:19) account: Disconnecting account 0623376817 (0x55cb133f5360)
What follow isquitting pidgin ~50 lines I skip

**Comment by dequis** [comment]
The page says where to send it, but, anyway, that snippet might be enough. It really sounds like a network issue, some firewall, proxy or whatever. Some http request is timing out. Not sure which (look for other mentions of `0x55cb142defb0` up in the same file), but there aren't many.

**Comment by ayl001** [comment]
:( I squeezed the log, my fault and now this does not disconnect. It did yesterday night and I left pidgin running, and now the connexion seems stable. The socket might have another name. Well... there are somme disco/reco in the log I have

**Comment by ayl001** [comment]
dequis, do you want me to send you another log?

**Comment by dequis** [comment]
You could, but it's not very useful information. Still boils down to your network having issues.

**Comment by ayl001** [comment]
Mmmh why don't I have such problem with other account (Jabber) and other applications? From time to time it is stable, right now I'm connected to FB OK. This /might/ be network account on my side (I'm on wifi) but why this only affects purple-facebook?

I have a scenario: could it be a problem of port forwarding? How to test it?

**Comment by ayl001** [comment]
Well this is the same problem using wire. The problem is not due to wifi, then. But I am behind the same box… It's pissing me off.

**Comment by Hark02** [comment]
(12:31:13) jabber: Sending (ssl) (xxx/73747FDF): <iq type='get' id='purple7d716a2b'><ping xmlns='urn:xmpp:ping'/></iq>
(12:31:13) jabber: Recv (ssl)(70): <iq to="xxx/73747FDF" id="purple7d716a2b" type="result"/>
(12:31:17) http: Request 045953B0 performed without success.
(12:31:17) connection: Connection error on 04FC82A0 (reason: 0 description: An unknown error occurred)
(12:31:17) account: Disconnecting account xxx (026B6DB8)
(12:31:17) connection: Disconnecting connection 04FC82A0
(12:31:17) jabber: jabber_actions: have pep: NO
(12:31:17) connection: Destroying connection 04FC82A0

**Comment by Hark02** [comment]
Facebook disconnects regularly.

**Comment by polkipop** [comment]
I've had problems with this plugin for a while, it refuses to log me in: "ERROR_QUEUE_UNDERFLOW"
It doesn't matter which computer I use, nor the network I'm on (I have tried more than ten, no firewalls blocking me). It just refuses to let me in.
It simply won't work.

**Comment by Nume1977** [comment]
> I've had problems with this plugin for a while, it refuses to log me in: "ERROR_QUEUE_UNDERFLOW"
> It doesn't matter which computer I use, nor the network I'm on (I have tried more than ten, no firewalls blocking me). It just refuses to let me in.
> It simply won't work.

Same here!

`(16:11:29) connection: Connection error on 075557F0 (reason: 0 description: ERROR_QUEUE_UNDERFLOW)`

**Comment by dequis** [comment]
Uhh, you're all mixing things here and the original issue was just a network-related timeout. There's another ticket for ERROR_QUEUE_UNDERFLOW, go there.
