### ISSUE TITLE
"User must verify their account on www.facebook.com (405)"

### ISSUE THREAD

**Issue by mvandemar** [dequis/purple-facebook#529]
This seems to be a new issue that just started today. Facebook logged me out and said I need to verify my account. I choose to have it send an email with a code, which I entered, which allowed me back in. I noticed that Pidgin was then disconnected. I told it to reconnect, got the above error, and had to re-verify to get back into Facebook on Chrome. Pidgin never reconnects, every attempt locks me out of my Facebook account in the browser. Messenger on my phone is unaffected. There does not seem to be a way to "verify" the Pidgin login, even though it's obviously the same IP address as Chrome.

**Comment by dequis** [comment]
#474
