### ISSUE TITLE
Xorg crashes when messaging on Facebook

### ISSUE THREAD

**Issue by maccagnan** [dequis/purple-facebook#530]
For some time I got a strange issue on Pidgin when using Facebook. When I write a message in the Facebook window the screen freezes and Xorg crashes.

This is the last bit of xsession-errors:

The X11 connection broke (error 1). Did the X11 server die?conky: 
X Error: Display 5629a52135a0

X connection to :0.0 broken (explicit kill or server shutdown).
X connection to :0.0 broken (explicit kill or server shutdown).
Pidgin: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.0.
--------
Devuan Daedalus up to date
Xserver 2:21.1.3-2
Pidgin 2.14.8 
Libpurple  2.14.8-1+b1

**Comment by dequis** [comment]
Yeah uhhh no, not this plugin. Ask elsewhere.
