### ISSUE TITLE
New parsing issue: unexpected identifier `taNewMessage`

### ISSUE THREAD

**Issue by jaymzh** [dequis/purple-facebook#531]
I'm getting frequent disconnects with:

```
<data>:1:12: Parse error: unexpected identifier `taNewMessage', expected value
```

**Comment by greatquux** [comment]
yes I expect this is the same as #514 but it still happens to me throughout the day. I can get it to happen by sending myself a message for sure.

**Comment by jaymzh** [comment]
yeah, this has gone back to normal amounts. I suspect a dupe of 514, combined with something going on at FB/Meta.
